ezsystems/PlatformUIBundle

Resources/config/yui.yml, Resources/public/js/views/fields/ez-time-editview.js, Resources/public/templates/fields/edit/time.hbt, Tests/js/views/fields/assets/ez-time-editview-tests.js
This is the time edit field for browsers not supporting time HTML5 input (like firefox browser for example). Time has to be fill with a HH:MM(:SS) pattern.
jira: https://jira.ez.no/browse/EZP-23745
=> EZP-23745 time edit for old browsers

Resources/public/js/views/fields/ez-keyword-editview.js, Tests/js/views/fields/assets/ez-keyword-editview-tests.js
Setting a keyword field to empty was returning [""], this was a problem because the view was displaying an empty string instead of the classic "This field is empty". Now it returns an empty array which is what we want.
However it seems that there is a bug in the REST API because the fieldValue is not correctly updated when we return an empty array ( bug has been reported at: https://jira.ez.no/browse/EZP-23912 )...
Jira: https://jira.ez.no/browse/EZP-23882?filter=-1
=> FIX/EZP-23882 Allows to set keyword field to empty

Resources/public/js/apps/ez-platformuiapp.js, Tests/js/apps/assets/ez-platformuiapp-tests.js
The goal here was to be able to enrich the routes of the application with some config elements. This is currently needed to implement the country view, but it's a generic way to do it.
jira: https://jira.ez.no/browse/EZP-22247?filter=-1
=> EZP-22247 Enrich routes with config

Resources/config/yui.yml, Resources/public/css/views/fields/edit/date.css, Resources/public/js/views/fields/ez-date-editview.js, Resources/public/templates/fields/edit/date.hbt, Tests/js/views/fields/assets/ez-date-editview-tests.js, Tests/js/views/fields/ez-date-editview.html
This is the date edit view for browsers NOT supporting date HTML5 input. The calendar used is the YUI one ( http://yuilibrary.com/yui/docs/calendar/ ). CSS is made in another pull request ( https://github.com/StephaneDiot/PlatformUIBundle-1/pull/1 ).
(without CSS)
jira : https://jira.ez.no/browse/EZP-23744
=> EZP-23744: Date edit for old browsers

Resources/public/js/apps/ez-platformuiapp.js, Resources/public/js/views/services/ez-viewservice.js, Tests/js/apps/assets/ez-platformuiapp-tests.js
The goal here is to give to the view service the route configuration. This is currently needed for the implementation of country field view.
Jira: https://jira.ez.no/browse/EZP-22247
=> EZP-22247 Give configuration to view service

Resources/public/css/theme/views/fields/edit/binarybase.css, Resources/public/css/views/fields/edit/binarybase.css, Resources/public/js/views/fields/ez-binarybase-editview.js, Resources/public/js/views/fields/ez-image-editview.js, Resources/public/templates/fields/edit/binaryfile.hbt, Resources/public/templates/fields/edit/image.hbt, Resources/public/templates/fields/edit/media.hbt, Tests/js/views/fields/assets/binarybase-tests.js, Tests/js/views/fields/assets/ez-binaryfile-editview-tests.js, Tests/js/views/fields/assets/ez-image-editview-tests.js, Tests/js/views/fields/assets/ez-keyword-view-tests.js, Tests/js/views/fields/assets/ez-media-editview-tests.js, Tests/js/views/fields/ez-binaryfile-editview.html, Tests/js/views/fields/ez-image-editview.html, Tests/js/views/fields/ez-media-editview.html
JIRA: https://jira.ez.no/browse/EZP-23789
This patch adds the ability to drag and drop a file to fill the BinaryFile, Media and Image fields. In addition, a mime type check has been added on the Image (also works with the regular file selection).
Screencast: http://youtu.be/RX40EiedAzk
Tasks:
unit tests and manual tests (IE10, Firefox and Chrome)
=> EZP-23789: As an editor, I want to be able to drag and drop a file to fill the Image, BinaryFile and Media fields

Resources/config/css.yml, Resources/config/yui.yml, Resources/public/css/theme/views/universaldiscovery.css, Resources/public/css/views/universaldiscovery.css, Resources/public/js/apps/ez-platformuiapp.js, Resources/public/js/apps/plugins/ez-universaldiscoveryplugin.js, Resources/public/js/views/ez-universaldiscoveryview.js, Resources/public/js/views/services/ez-universaldiscoveryviewservice.js, Resources/public/js/views/services/ez-viewservice.js, Resources/public/templates/universaldiscovery.hbt, Resources/views/PlatformUI/shell.html.twig, Tests/js/apps/assets/ez-platformuiapp-tests.js, Tests/js/apps/plugins/assets/ez-universaldiscoveryplugin-tests.js, Tests/js/apps/plugins/ez-universaldiscoveryplugin.html, Tests/js/views/assets/ez-universaldiscoveryview-tests.js, Tests/js/views/ez-universaldiscoveryview.html, Tests/js/views/services/assets/ez-universaldiscoveryviewservice-tests.js, Tests/js/views/services/ez-universaldiscoveryviewservice.html
JIRA: https://jira.ez.no/browse/EZP-23817
This PR provides the foundations of the **Universal Discovery Wigdet**. The universal discovery widget is interface the editors will use to pick one or several contents in the repository. For instance, it'll be used when the user wants to add some content(s) in a relation or assign a section to a content.
From a technical point of view, it will be implemented as a *side view* (like the top or left menus) but with a way for any view to trigger it (with an event) and to potentially decide what to do when the user cancels or confirms his selection.
The following screencast shows this code in action with the custom code in https://github.com/ezsystems/PlatformUIBundle/commit/47a85a45851644beaac5cdf6813edda37830cd69. This custom code just adds 2 …
=> EZP-23817: As a developer, I want to have a universal discovery widget to pick a content

Resources/public/js/views/ez-navigationhubview.js, Tests/js/views/assets/ez-navigationhubview-tests.js
JIRA: https://jira.ez.no/browse/EZP-23922 (Feedback from Gareth Arnott, a community member)
This patch removes the ability to switch from a zone ("Create", "Deliver", "Optimize") to another by hovering over the zone name. This feature was actually painful because the user might hover over a zone while he tries to reach a navigation item.
Unit test + manual test
=> Fix EZP-23922: Improve Navigation hub to prevent accidental hovers

Resources/config/yui.yml
There was a little error in the keyword field view configuration file (yui.yml)... The fieldeditview module was loaded instead of the fieldview... So well, this should be better now !
=> Fixing error on keyword view

Controller/PlatformUIController.php, Resources/config/routing.yml, Resources/config/services.yml, Resources/public/js/apps/ez-platformuiapp.js, Resources/public/js/views/services/ez-loginformviewservice.js, Resources/views/PlatformUI/shell.html.twig, Tests/js/apps/assets/ez-platformuiapp-tests.js, Tests/js/views/services/assets/ez-loginformviewservice-tests.js, composer.json
JIRA: https://jira.ez.no/browse/EZP-21265
This patch fixes a very long standing issue where the PlatformUI app was not able to reuse an already existing session and even prevented the user from login in if the user already had a session.
Tasks:
=> EZP-21265: Reuse an existing session

Resources/public/js/views/ez-locationviewview.js, Resources/public/js/views/ez-rawcontentview.js, Tests/js/views/assets/ez-locationviewview-tests.js, Tests/js/views/assets/ez-rawcontentview-tests.js
This issue follows https://github.com/ezsystems/PlatformUIBundle/pull/159 and https://github.com/ezsystems/PlatformUIBundle/pull/156 and https://github.com/ezsystems/PlatformUIBundle/pull/155 ... This is the last step to enrich fieldViews with some route configuration. This will be useful to display the country field view.
https://jira.ez.no/browse/EZP-22247
=> EZP-22247 Give route config to field views

Resources/views/SystemInfo/info.html.twig
Set missing decimal number precision parameter to 1. My VM's memory now shows as 854.5 MB which is a bit TMI, but with zero precision 1.5 GB would show as 2 GB, so I prefer this way.
https://jira.ez.no/browse/EZP-23917
=> Fix EZP-23917: PHP warning and notice in the server tab in the system info

composer.json
> https://jira.ez.no/browse/EZP-24035
Missing dependency since legacy removal.
=> Fix EZP-24035: Fatal error when accessing system info in admin panel tab

Resources/public/css/layout.css
https://jira.ez.no/browse/EZP-24120
Corrected the CSS code making the **Close** button in the `contentEditView` clickable again.
=> EZP-24120 - Close button is not clickable

Resources/public/css/theme/app.css
JIRA: https://jira.ez.no/browse/EZP-24091
Very small CSS clean up after [the upgrade to Pure 0.6](https://github.com/ezsystems/PlatformUIAssetsBundle/pull/5). The class `.pure-g-r` was removed in Pure 0.5 (and it was not used anyway).
=> EZP-24091: Removed useless CSS rule after upgrade to Pure 0.6

Gruntfile.js, Resources/config/yui.yml, Resources/public/css/modules/button.css, Resources/public/css/theme/modules/button.css, Resources/public/js/apps/ez-platformuiapp.js, Resources/public/js/views/ez-universaldiscoveryview.js, Resources/public/js/views/serverside/ez-sectionserversideview.js, Resources/public/js/views/services/ez-sectionserversideviewservice.js, Resources/translations/section.en.xlf, Resources/views/Section/list.html.twig, Resources/views/Section/view.html.twig, Tests/js/views/serverside/assets/ez-sectionserversideview-tests.js, Tests/js/views/serverside/ez-sectionserversideview.html, Tests/js/views/services/assets/ez-sectionserversideviewservice-tests.js, Tests/js/views/services/ez-sectionserversideviewservice.html
JIRA: https://jira.ez.no/browse/EZP-24065
[EZP-24065](https://jira.ez.no/browse/EZP-24065) is originally about assigning a section to a subtree but unfortunately, the REST API only provides a resource to assign a section to a content without reflecting this operation to its subtree(s). As a result, this patch only allows the developer to assign a section to some contents but the descendants of those contents in the tree won't be affected.
Screencast: http://youtu.be/29eLEuC4U-w
=> EZP-24065: As a developer, I want to be able to assign a subtree to a section

Resources/public/js/views/fields/ez-binarybase-editview.js, Resources/public/js/views/fields/ez-image-editview.js, Tests/js/views/fields/assets/ez-binaryfile-editview-tests.js, Tests/js/views/fields/assets/ez-image-editview-tests.js, Tests/js/views/fields/assets/ez-media-editview-tests.js
JIRA: https://jira.ez.no/browse/EZP-23788
Change needed after https://github.com/ezsystems/ezpublish-kernel/pull/1209 so that it's now possible to update only the alternative text without re-uploading the image. In such case, the REST API now expects the client to send an object based on the field value it provided.
unit tests updated + manual tests.
=> EZP-23788: Fix the field value when trying to update only the alt text

Resources/public/js/views/fields/ez-checkbox-editview.js, Resources/public/templates/fields/edit/checkbox.hbt, Tests/js/views/fields/assets/ez-checkbox-editview-tests.js
JIRA: https://jira.ez.no/browse/EZP-24039
As the title suggests, it's impossible to uncheck a Checkbox field. cb7dcad fixes this by making sure we correctly check the state of the checkbox input. While working on it, I also realized that the checkbox state was also wrongly set because it is based on the field definition default value instead of the actual field value. So the second commit fixes that as well.
=> EZP-24039: Impossible to uncheck a Checkbox field

Resources/public/js/views/ez-contenteditview.js, Tests/js/views/assets/ez-contenteditview-tests.js
JIRA: https://jira.ez.no/browse/EZP-24108
The preview displays a completely blank page. This is happening because the `content` was forgotten when we changed how the content, the version and the content type are passed to the different subviews of content edit (8f839f46998223657659afc6331e1f903f741f2b).
unit test + manual tests
=> Fixed EZP-24108: eZ Platform preview not working

Resources/translations/fieldtypes.en.yml
> https://jira.ez.no/browse/EZP-20347
Idea is to use Translation component for this.
Note that YAML format is used on purpose, in order to differenciate from a "real" translation file.
Example to get human readable name for `ezstring`:
```php
/** \Symfony\Component\Translation\TranslatorInterface $translator */
echo $translator->trans('ezstring.name', [], 'fieldtypes');
```
=> Fix EZP-20347: Implement an API to get the readable name of a field type from its identifier

Resources/config/yui.yml, Resources/public/js/views/fields/ez-float-view.js, Resources/public/js/views/fields/ez-integer-view.js, Tests/js/views/fields/assets/ez-float-view-tests.js, Tests/js/views/fields/assets/ez-integer-view-tests.js, Tests/js/views/fields/ez-float-view.html, Tests/js/views/fields/ez-integer-view.html
Link: https://jira.ez.no/browse/EZP-24126
Numerics fields (Integer and Floats) were using the default `_isFieldEmpty` method that considers 0 as empty. A custom one has been implemented for those fields.
=> Fix EZP-24126: Numeric fields with value 0 are considered empty

Controller/ContentTypeController.php, Form/Processor/ContentTypeFormProcessor.php, Resources/config/routing.yml, Resources/config/services.yml, Resources/public/js/apps/ez-platformuiapp.js, Resources/public/js/views/services/ez-navigationhubviewservice.js, Resources/translations/content_type.en.xlf, Resources/views/ContentType/list_content_type_groups.html.twig, Resources/views/ContentType/update_content_type.html.twig, Resources/views/ContentType/view_content_type.html.twig, Resources/views/ContentType/view_content_type_group.html.twig, Resources/views/Dashboard/dashboard.html.twig, Tests/js/views/services/assets/ez-navigationhubviewservice-tests.js, composer.json
> https://jira.ez.no/browse/EZP-24379
This PR adds ContentType management into PlatformUI.
This includes:
* List of ContentTypeGroups
* List of ContentTypes in a group
* Base view of a ContentType
* ContentType edit
* Integration in navigation hub
* Integration in admin dashboard
Depends on https://github.com/ezsystems/repository-forms/pull/16
=> Fix EZP-24379: Integrate ContentType edition with PlatformUI

Form/Type/SectionDeleteType.php, Form/Type/SectionListType.php, Form/Type/SectionType.php, Helper/SectionHelper.php, Resources/config/routing.yml, Resources/config/services.yml
* Used configureOptions() instead of setDefaultOptions in form types
* Fixed deprecations in routing.yml
* Removed usage of security context
Tested locally, with unit tests and in browser.
=> [Symfony 2.7] Removed deprecation warnings

Resources/public/css/views/fields/edit/image.css, Resources/public/css/views/fields/edit/media.css
JIRA: https://jira.ez.no/browse/EZP-23914
Fix the layout in IE10 when editing an Image or Media field. (The patch was made a while ago but for whatever reason, I forgot to create the PR...)
manual tests
=> Fixed EZP-23914: Image and Media edit views display are broken in IE10

Resources/public/js/models/ez-locationmodel.js, Resources/public/js/views/services/ez-locationviewviewservice.js, Tests/js/models/assets/ez-locationmodel-tests.js, Tests/js/views/services/assets/ez-locationviewviewservice-tests.js
Link: https://jira.ez.no/browse/EZP-24408
Needs https://github.com/ezsystems/ez-js-rest-client/pull/60 to work as it implements the new feature introduced by it in the PlatformUIBundle. It is using the newly exposed discovery service.
Manual and updated unit tests
=> EZP-24408: Use REST API discovery service

Resources/config/yui.yml, Resources/public/js/apps/plugins/ez-updatetreeplugin.js, Resources/public/js/views/ez-barview.js, Resources/public/js/views/services/ez-locationviewviewservice.js, Resources/public/js/views/services/plugins/ez-copycontentplugin.js, Resources/public/js/views/services/plugins/ez-publishdraftplugin.js, Resources/public/js/views/services/plugins/ez-savedraftplugin.js, Tests/js/apps/plugins/assets/ez-updatetreeplugin-tests.js, Tests/js/apps/plugins/ez-updatetreeplugin.html, Tests/js/views/assets/ez-barview-tests.js, Tests/js/views/services/assets/ez-locationviewviewservice-tests.js, Tests/js/views/services/plugins/assets/ez-copycontentplugin-tests.js, Tests/js/views/services/plugins/assets/ez-publishdraftplugin-tests.js, Tests/js/views/services/plugins/assets/ez-savedraftplugin-tests.js
Jira Link: https://jira.ez.no/browse/EZP-24410
We wanted the discoveryBar tree to be updated after any actions able to alter it (copy, move, delete, edit, create). This is now done with some events fired by those actions and caught by an app's plugin.
=> EZP-24410: Content tree not updated automatically after publishing content or sending content to trash

Resources/public/js/views/actions/ez-createcontentactionview.js, Resources/public/js/views/ez-actionbarview.js, Tests/js/views/actions/assets/ez-createcontentactionview-tests.js, Tests/js/views/assets/ez-actionbarview-tests.js, Tests/js/views/assets/ez-locationviewview-tests.js, Tests/js/views/ez-actionbarview.html
JIRA: https://jira.ez.no/browse/EZP-23907
Continuation of https://github.com/ezsystems/PlatformUIBundle/pull/254 as it was merged too early.
When viewing content that is not container, "Create content" button should be disabled as it shouldn't be allowed to create content inside non-container contents. The goal is to check if contentType of content is container and if it's not, disable "Create content" button.
=> EZP-23907: PlatformUI allows to create a content under non container content

Form/Processor/ContentTypeFormProcessor.php, Notification/Notification.php, Notification/NotificationMessage.php, Notification/NotificationPool.php, Notification/NotificationPoolInterface.php, Notification/TranslatableNotificationMessage.php, Resources/config/services.yml, Resources/translations/content_type.en.xlf, Resources/views/pjax_admin.html.twig, Tests/Notification/NotificationPoolTest.php
> https://jira.ez.no/browse/EZP-24450
Added a new block in Pjax base template for notifications.
This block is automatically filled by flash session messages with `notification` as identifier.
=> Fix EZP-24450: As an admin developer, I want to push notifications using a Pjax controller

Resources/public/js/views/ez-discoverybarview.js
Just removes the "Do something" button in the discovery bar, it was added as a test and stayed there for quite some time now :)
manual tests
=> Removed the "Do something" button in the discovery bar

Resources/public/js/models/ez-contentmodel.js, Tests/js/models/assets/ez-contentmodel-tests.js
This fixes a regression introduced in https://github.com/ezsystems/PlatformUIBundle/pull/251. Without this patch, it's impossible to create a new content because the Content model tries to parse a non existent version.
manual + unit
=> Make sure to parse the current version only when there's one

Resources/public/js/views/actions/ez-buttonactionview.js, Tests/js/views/actions/assets/genericbuttonactionview-tests.js
Make sure to prevent default behavior when the user uses a Button Action View, otherwise, if the view is rendered inside a form, the form is submitted. (This happening for instance in the RichText focus mode).
=> Make to sure the prevent the tap event handle the button action view

Resources/public/js/apps/plugins/ez-updatetreeplugin.js, Tests/js/apps/plugins/assets/ez-updatetreeplugin-tests.js
If you go directly to the edit content page (for instance with a browser bookmark), the publication will crash because the update tree plugin tries to use the discovery bar view but it hasn't been created yet.
This patch makes sure we handle this case.
manual test + unit test
=> Fixed a crash after publication if the discovery bar has never been instantiated

Resources/public/js/views/ez-locationviewview.js, Tests/js/views/assets/ez-locationviewview-tests.js
The `active` state is not fowarded to the location view tabs (this was forgotten in https://github.com/ezsystems/PlatformUIBundle/pull/265) as a result, the asynchronous field view (image, relation, relation list) are broken.
This patch makes sure the `active` flag value is forwarded to the tabs.
manual test + unit test
=> Make sure to forward the active state to the location view tab

Resources/config/yui.yml, Resources/public/js/apps/ez-platformuiapp.js, Resources/public/js/views/serverside/ez-contenttypeeditserversideview.js, Tests/js/views/serverside/assets/ez-contenttypeeditserversideview-tests.js, Tests/js/views/serverside/ez-contenttypeeditserversideview.html
Jira: https://jira.ez.no/browse/EZP-24502
The goal of this PR is to create the handler for button "Select Item" (for picking the default root location). Handler should call Universal Discovery Widget to allow choosing single location which will be passed back and set into the input form.
* https://jira.ez.no/browse/EZP-24446 - https://github.com/ezsystems/repository-forms/pull/31
* https://jira.ez.no/browse/EZP-24447 - https://github.com/ezsystems/repository-forms/pull/32
=> EZP-24502: implement a content type server side view (UDW for relations)

Resources/public/js/views/services/ez-serversideviewservice.js, Tests/js/views/services/assets/ez-serversideviewservice-tests.js
Jira: https://jira.ez.no/browse/EZP-24536
The goal of this story is to parse notifications taken from Pjax controller as HTML block and display them usin PlatformUI notification system.
* https://jira.ez.no/browse/EZP-24450 - As an admin developer, I want to push notifications using a Pjax controller
* PR: https://github.com/ezsystems/PlatformUIBundle/pull/260
=> EZP-24536: Parse and display the notifications send in the admin part

Resources/public/js/apps/ez-platformuiapp.js, Resources/public/js/models/ez-contentmodel.js, Resources/public/js/views/ez-locationviewview.js, Resources/public/js/views/navigation/ez-navigationitemview.js, Resources/public/js/views/services/ez-contentcreateviewservice.js, Resources/public/js/views/services/ez-contenteditviewservice.js, Resources/public/js/views/services/ez-locationviewviewservice.js, Resources/public/js/views/services/ez-navigationhubviewservice.js, Resources/public/js/views/services/plugins/ez-contentcreateplugin.js, Resources/public/templates/dashboard.hbt, Resources/public/templates/fields/view/relation.hbt, Resources/public/templates/fields/view/relationlist.hbt, Resources/public/templates/locationview.hbt, Resources/public/templates/partials/tree.hbt, Tests/js/models/assets/ez-contentmodel-tests.js, Tests/js/views/assets/ez-navigationhubview-tests.js, Tests/js/views/navigation/assets/ez-navigationitemparameterview-tests.js, Tests/js/views/navigation/assets/ez-navigationitemsubtreeview-tests.js, Tests/js/views/navigation/assets/ez-navigationitemview-tests.js, Tests/js/views/services/assets/ez-contentcreateviewservice-tests.js, Tests/js/views/services/assets/ez-locationviewviewservice-tests.js, Tests/js/views/services/assets/ez-navigationhubviewservice-tests.js, Tests/js/views/services/ez-navigationhubviewservice.html
Link: https://jira.ez.no/browse/EZP-24384
See issue.
=> EZP-24384: Add a language parameter in the viewLocation route

Resources/public/js/views/serverside/ez-contenttypeeditserversideview.js, Resources/public/js/views/serverside/ez-sectionserversideview.js
Jira: https://jira.ez.no/browse/EZP-24426
The goal of this issue is to avoid the user being thrown out from PlatformUI when redirecting from some parts admin part.
This PR fixes those issues for redirecting from assigning sections form and from edit content type form.
=> EZP-24426: Wrong URL when redirecting from forms in admin part

Resources/public/js/extensions/ez-asynchronousview.js, Tests/js/views/fields/assets/ez-relation-view-tests.js
When displaying a content in PlatformUI after a content having a filled Relation field, the following error is visible in the console:
```
Uncaught TypeError: Cannot read property 'destination' of undefined
```
this is happening because the event to get the related content is fired when the `active` attribute changes instead of being fired when the view becomes active.
=> Fixed a JS error displaying a content with a filled Relation field

ApplicationConfig/Aggregator.php, ApplicationConfig/Provider.php, ApplicationConfig/Providers/AnonymousUserId.php, ApplicationConfig/Providers/RootInfo.php, ApplicationConfig/Providers/SessionInfo.php, ApplicationConfig/Providers/Value.php, Controller/PlatformUIController.php, DependencyInjection/Compiler/ApplicationConfigProviderPass.php, EzSystemsPlatformUIBundle.php, Resources/config/services.yml, Resources/views/PlatformUI/shell.html.twig, Tests/ApplicationConfig/AggregatorTest.php, Tests/ApplicationConfig/Providers/AnonymousUserIdTest.php, Tests/ApplicationConfig/Providers/RootInfoTest.php, Tests/ApplicationConfig/Providers/SessionInfoTest.php, Tests/ApplicationConfig/Providers/ValueTest.php
> Implements https://jira.ez.no/browse/EZP-24129
> Status: approved
Adds an Aggregator, passed on to the PlatformUIController, that aggregates a bunch of `ApplicationConfigProviders`.
The existing configs were converted to their own implementation of `ApplicationConfigProvider`: `AnonymousUserId`, `CountriesInfo`, `SessionInfo`.
A compiler pass parses the `ezsystems.platformui.application_config_provider` tag, and registers them in the Aggregator. The `key` attribute of the tag is used as the namespace. 
The controller assigns the whole thing to the template as the `parameters` array.
=> EZP-24129: Application Config Provider

Features/CopyMoveDelete/MoveContent.feature
BDD scenarios for Move Content feature - https://jira.ez.no/browse/EZP-24187
The current BDD scenarios aim to reflect the behaviour of moving a content in PlatformUI
The situations reflected below are not yet reflected in BDD scenarios due clarification need
=> BDD Move Content Feature

Features/CopyMoveDelete/RemoveContent.feature
BDD scenarios for Remove Content feature - https://jira.ez.no/browse/EZP-24385
The current BDD scenarios aim to reflect the behaviour of removing a content in PlatformUI
The situations reflected below are not yet reflected in BDD scenarios
Todo:
For later follow up:
- Remove one object when the user is not allowed to.
- Remove one object that has multiple locations
- Remove multiple objects
- Untrash a trashed object
=> BDD Remove Content Feature

Controller/ContentTypeController.php, Resources/config/css.yml, Resources/public/css/modules/serverside-content.css, Resources/views/ContentType/update_content_type.html.twig, Resources/views/ContentType/view_content_type.html.twig, Resources/views/Role/update_role.html.twig
https://jira.ez.no/browse/EZP-24727
Is:
- padding to have space around content in admin part
- use pure-forms to align form elements
- some minor cleanups/sync up of code to have consistent view on context info (modified info)
Is no:
- This is not the end for content type editing, there is a much bigger story in store to display it differently, which is why some field types is looking a bit weird still here, as they will be displayed differently anyway.
Depends on https://github.com/ezsystems/repository-forms/pull/42
Screen shoots:
Bottom part of the form:
Also ready for mobile ;):
Ready for review: @glye @dpobel @yannickroger
=> EZP-24727: Admin forms improvments

Resources/public/css/theme/views/contentedit.css, Resources/public/css/views/contentedit.css, Resources/public/css/views/contenteditform.css, Resources/public/js/views/ez-contenteditview.js, Resources/public/templates/contentedit.hbt, Tests/js/views/assets/ez-contenteditview-tests.js, Tests/js/views/ez-contenteditview.html
https://jira.ez.no/browse/EZP-24626
A description of the content type should be shown when passing cursor over the header while editing or creating a content. On 'touch friendly' devices the description should be shown when tapping on header, and should unshow when tapping outside (the same rule has also been added for the technical infos).
http://youtu.be/Y97RexOHWZo
(first part is 'touch friendly' emulated, second is like in a normal browser)
=> EZP-24626 As an editor I want to see content type description when editing content

Resources/config/css.yml, Resources/config/yui.yml, Resources/public/css/views/fields/edit/isbn.css, Resources/public/js/views/fields/ez-isbn-editview.js, Resources/public/templates/fields/edit/isbn.hbt, Tests/js/views/fields/assets/ez-isbn-editview-tests.js, Tests/js/views/fields/ez-isbn-editview.html
https://jira.ez.no/browse/EZP-24613
The edit view for ISBN field. Currently the validation doesn't care about hyphenation (see ticket: https://jira.ez.no/browse/EZP-24638 ). 
This supports ISBN10 and ISBN13
note: there is currently a bug which set all the 'fieldDefinition->fieldSettings-isISBN13' to true (see ticket: https://jira.ez.no/browse/EZP-24617 )
ISBN13: http://youtu.be/hPo0-AYDwC4
ISBN10: http://youtu.be/_uJxZo3aHyg
=> EZP-24613 As an editor, I want to be able to edit the ISBN fields

Resources/public/js/views/ez-confirmboxview.js, Resources/public/js/views/ez-serversideview.js, Resources/public/templates/confirmbox.hbt, Tests/js/views/assets/ez-confirmboxview-tests.js, Tests/js/views/assets/ez-serversideview-tests.js
jira link : https://jira.ez.no/browse/EZP-24652
The goal here was to be able to launch confirm box from the server side view. The confirm box has been upgraded to be able to display some details.
http://youtu.be/ksZnmAb_UYM
=> EZP-24652 Launch confirm box from server side view

Resources/public/css/theme/views/contentedit.css, Resources/public/css/views/contentedit.css
jira link: https://jira.ez.no/browse/EZP-24757
The goal here was to change some CSS to make the content type description more readable ( see: https://github.com/ezsystems/PlatformUIBundle/pull/292 )
http://youtu.be/AEZsIKbnav0
=> EZP-24757 Change content type description to be more readable

Gruntfile.js, Resources/config/yui.yml, Resources/public/js/models/extensions/ez-contentinfo-attributes.js, Resources/public/js/models/ez-contentinfomodel.js, Resources/public/js/models/ez-contentmodel.js, Resources/public/js/models/ez-locationmodel.js, Tests/js/models/assets/ez-contentinfomodel-tests.js, Tests/js/models/assets/ez-locationmodel-tests.js, Tests/js/models/assets/model-tests.js, Tests/js/models/ez-contentinfomodel.html, Tests/js/models/ez-contentmodel.html, Tests/js/views/ez-editpreviewview.html, Tests/js/views/services/ez-locationviewviewservice.html, Tests/js/views/services/plugins/ez-contenttreeplugin.html, Tests/js/views/services/plugins/ez-objectrelationlistloadplugin.html, Tests/js/views/services/plugins/ez-objectrelationloadplugin.html
Link: https://jira.ez.no/browse/EZP-24550
The goal of this PR is to to have a ContentInfoModel that will allow retrieving ContentInfo instead of Content when needed (follow up story) leading to better performances.
Created dedicated unit test for ContentInfoModel.
Updated unit test for ContentModel and LocationModel.
=> EZP-24550: Add ContentInfo model

Resources/views/ContentType/update_content_type.html.twig, Resources/views/Role/update_role.html.twig
> https://jira.ez.no/browse/EZP-24752
Added `formnovalidate` attribute to *cancel* submit button.
=> Fix EZP-24752: Cancel buttons should be not trigger validation in PlatformUI

Resources/public/js/views/ez-locationviewview.js, Resources/public/js/views/ez-rawcontentview.js, Resources/public/js/views/services/ez-locationviewviewservice.js, Resources/public/js/views/services/ez-navigationhubviewservice.js, Resources/public/js/views/services/ez-viewservice.js, Resources/public/js/views/services/plugins/ez-contenttreeplugin.js, Resources/public/js/views/services/plugins/ez-discoverybarcontenttreeplugin.js, Resources/public/templates/locationview.hbt, Resources/public/templates/partials/tree.hbt, Tests/js/views/assets/ez-locationviewview-tests.js, Tests/js/views/services/assets/ez-locationviewviewservice-tests.js, Tests/js/views/services/assets/ez-navigationhubviewservice-tests.js
Link: https://jira.ez.no/browse/EZP-24706
ContentInfo is now available in location. The goal of this PR is to remove content loading everywhere it is no longer mandatory in order to provide better performances.
Manual test and update of existing unit tests
=> EZP-24706: Replace content loading by contentinfo

Resources/public/js/views/services/ez-serversideviewservice.js, Tests/js/views/services/assets/ez-serversideviewservice-tests.js
JIRA: https://jira.ez.no/browse/EZP-24788
This patch changes the server side view service so that it adds the custom `X-PJAX` header to allow the server side code to discriminate PJAX requests from the others.
unit tests
=> EZP-24788: Add X-PJAX header to PJAX requests

Resources/config/yui.yml, Resources/public/css/theme/alloyeditor/content.css, Resources/public/css/views/fields/edit/richtext.css, Resources/public/js/alloyeditor/plugins/focusblock.js, Resources/public/js/views/fields/ez-richtext-editview.js, Tests/js/alloyeditor/plugins/assets/ez-alloyeditor-plugin-focusblock-tests.js, Tests/js/alloyeditor/plugins/ez-alloyeditor-plugin-focusblock.html, Tests/js/views/fields/assets/ez-richtext-editview-tests.js
JIRA: https://jira.ez.no/browse/EZP-24769
This patch adds an outline around the block where the user's caret is placed to make clear which will be affected by the button in the toolbar (currently only implemented for heading).
Screencast: https://www.youtube.com/watch?v=umIHxUNKBtA
=> EZP-24769: Outline the focused block in the editor

Features/Stories/FieldTypes/IntegerFieldType.feature
Following up the integer BDD scenarios form dropped PR #211 
Todo:
=> Integer BDD Scenarios

Resources/config/yui.yml, Resources/public/css/alloyeditor/general.css, Resources/public/js/alloyeditor/toolbars/config/block-base.js, Resources/public/js/alloyeditor/toolbars/config/heading.js, Resources/public/js/alloyeditor/toolbars/config/link.js, Resources/public/js/alloyeditor/toolbars/config/paragraph.js, Resources/public/js/alloyeditor/toolbars/config/table.js, Resources/public/js/alloyeditor/toolbars/config/text.js, Resources/public/js/views/fields/ez-richtext-editview.js, Tests/js/alloyeditor/toolbars/config/assets/ez-alloyeditor-toolbar-config-block-base-tests.js, Tests/js/alloyeditor/toolbars/config/assets/ez-alloyeditor-toolbar-config-heading-tests.js, Tests/js/alloyeditor/toolbars/config/assets/ez-alloyeditor-toolbar-config-link-tests.js, Tests/js/alloyeditor/toolbars/config/assets/ez-alloyeditor-toolbar-config-paragraph-tests.js, Tests/js/alloyeditor/toolbars/config/assets/ez-alloyeditor-toolbar-config-table-tests.js, Tests/js/alloyeditor/toolbars/config/assets/ez-alloyeditor-toolbar-config-text-tests.js, Tests/js/alloyeditor/toolbars/config/assets/toolbar-config-define-tests.js, Tests/js/alloyeditor/toolbars/config/ez-alloyeditor-toolbar-config-block-base.html, Tests/js/alloyeditor/toolbars/config/ez-alloyeditor-toolbar-config-heading.html, Tests/js/alloyeditor/toolbars/config/ez-alloyeditor-toolbar-config-link.html, Tests/js/alloyeditor/toolbars/config/ez-alloyeditor-toolbar-config-paragraph.html, Tests/js/alloyeditor/toolbars/config/ez-alloyeditor-toolbar-config-table.html, Tests/js/alloyeditor/toolbars/config/ez-alloyeditor-toolbar-config-text.html, Tests/js/views/fields/assets/fake-alloyeditor-toolbarconfig.js
JIRA: https://jira.ez.no/browse/EZP-24770
This patch adds the configuration of the `styles` toolbar so that it's possible to tweak paragraphs like it's already the case for heading. While at it, I also change the positioning strategy of the heading toolbar. For both, the toolbar is placed right above its related block element.
Screencast: https://youtu.be/PKtkqvAX-vQ
=> EZP-24770: As an editor, I want to be able to configure the paragraph element

Resources/public/js/apps/ez-platformuiapp.js, Resources/public/js/views/services/ez-serversideviewservice.js, Tests/js/apps/assets/ez-platformuiapp-tests.js, Tests/js/views/services/assets/ez-serversideviewservice-tests.js
JIRA: https://jira.ez.no/browse/EZP-24787
As of https://github.com/ezsystems/PlatformUIBundle/pull/325, the Symfony error page embeds the notifications tag. This patch makes sure we use that (when available) to notify the user about a loading error instead of the *Failed to load* something message. This is done both when submitting a form and for *regular* page loading.
manual + unit tests.
=> EZP-24787: Catch and display real error messages as notification

Resources/public/css/theme/views/contentedit.css, Resources/public/css/theme/views/languageselectionbox.css, Resources/public/css/views/contentedit.css, Resources/public/css/views/languageselectionbox.css, Resources/public/js/views/actions/ez-translateactionview.js, Resources/public/js/views/ez-contenteditview.js, Resources/public/js/views/ez-languageselectionboxview.js, Resources/public/js/views/services/ez-contentcreateviewservice.js, Resources/public/js/views/services/ez-contenteditviewservice.js, Resources/public/js/views/services/ez-languageselectionboxviewservice.js, Resources/public/templates/contentedit.hbt, Resources/public/templates/languageselectionbox.hbt, Tests/js/views/actions/assets/ez-translateactionview-tests.js, Tests/js/views/assets/ez-contenteditview-tests.js, Tests/js/views/assets/ez-languageselectionboxview-tests.js, Tests/js/views/ez-contenteditview.html, Tests/js/views/ez-languageselectionboxview.html, Tests/js/views/services/assets/ez-contentcreateviewservice-tests.js, Tests/js/views/services/assets/ez-contenteditviewservice-tests.js
Jira: https://jira.ez.no/browse/EZP-23768
The goal of this one is to allow user to change language of content when creating one. Also currently it allows to switch between existing translations when editing the content.
This PR also changes a little the languageSelectionBox feature allowing to choose what languages should be included in the list: already existing translations or only new translations.
- Change language when creating content: https://youtu.be/p4VquWGLy9Q
- Change language when editing content: https://youtu.be/BS4o01TtWPs
=> EZP-23768: change language when creating content

Resources/public/js/views/services/plugins/ez-discoverybarcontenttreeplugin.js
JIRA: https://jira.ez.no/browse/EZP-24811
Regression introduced in https://github.com/ezsystems/PlatformUIBundle/commit/cca477fa6f907b197c89dfe42c4361b7edff1105 / [EZP-24706](https://jira.ez.no/browse/EZP-24706). The path now only contains the Location model since they embed the ContentInfo.
manual, this part not unit tested yet because it'll change soon
=> Fix EZP-24811: JavaScript error when loading the tree for a Location other than the root

Controller/ContentTypeController.php, Resources/config/routing_pjax.yml, Resources/translations/content_type.en.xlf, Resources/views/ContentType/view_content_type.html.twig, Resources/views/ContentType/view_content_type_group.html.twig
> https://jira.ez.no/browse/EZP-24453
Depends on https://github.com/ezsystems/repository-forms/pull/46 .
Note that it is only possible to remove ContentTypes **NOT** having Content instances (basically following what `ContentTypeService` does).
If one try to remove such ContentType, repository error will be bubbled as bad request (see https://github.com/ezsystems/ezpublish-kernel/pull/1416)
=> Fix EZP-24453: Implement ContentType removal

Resources/public/js/views/services/ez-contentcreateviewservice.js, Tests/js/views/services/assets/ez-contentcreateviewservice-tests.js
Jira: https://jira.ez.no/browse/EZP-24810
Currently user is allowed to change the language when creating the content, but when it is done, he is not notified about that.
This  PR adds notification after changing the language.
=> EZP-24810: notification when user changes language when creating the content

Resources/public/js/views/services/ez-navigationhubviewservice.js, Tests/js/views/services/assets/ez-navigationhubviewservice-tests.js
Link: https://jira.ez.no/browse/EZP-24836
Created a static entry for the "Users" menu.
Manual and updated unit tests
=> EZP-24836: Add the navigation zone item to the Users subtree

Resources/public/js/views/tabs/ez-locationviewrelationstabview.js, Resources/public/templates/tabs/relations.hbt, Tests/js/views/tabs/assets/ez-locationviewrelationstabview-tests.js
Link: https://jira.ez.no/browse/EZP-24885
The wrong id (contentId) was passed to generate the link to the related content, it is now passing mainLocationId instead.
=> Fix EZP-24885: Links to Related Content instances don't work

Resources/public/js/apps/ez-platformuiapp.js, Resources/public/js/views/ez-contenteditformview.js, Resources/public/js/views/ez-contenteditview.js, Resources/public/js/views/ez-locationviewview.js, Resources/public/js/views/ez-rawcontentview.js, Resources/public/js/views/ez-subitemlistview.js, Resources/public/js/views/fields/ez-richtext-editview.js, Tests/js/apps/assets/ez-platformuiapp-tests.js
JIRA: https://jira.ez.no/browse/EZP-24654
The patch in https://github.com/ezsystems/PlatformUIBundle/pull/349 was incomplete / buggy:
* the auth is broken because of a wrong SessionAuthAgent initialization
* the view service did not receive the configuration
* the test on that was wrongly written hiding the bug
* as a result, the field (edit) view did not have the necessary data (the country list for Country, the ckeditor plugin path for Rich edit view).
* the default ckeditor plugin path was also wrong
While at it, I also removed the `config` attribute in some views since it's now defined in the `eZ.View`.
manual tests + unit test
=> EZP-24654: Additional fixes

Resources/config/yui.yml, Resources/public/css/views/tabs/locations.css, Resources/public/js/models/ez-contentmodel.js, Resources/public/js/views/services/plugins/ez-locationcreateplugin.js, Resources/public/js/views/tabs/ez-locationviewlocationstabview.js, Resources/public/templates/tabs/locations.hbt, Tests/js/models/assets/ez-contentmodel-tests.js, Tests/js/views/services/plugins/assets/ez-locationcreateplugin-tests.js, Tests/js/views/services/plugins/ez-locationcreateplugin.html, Tests/js/views/tabs/assets/ez-locationviewlocationstabview-tests.js, Tests/js/views/tabs/ez-locationviewlocationstabview.html
Jira: https://jira.ez.no/browse/EZP-24812
The goal of this PR is to allow user to add new locations for given content by using "Add location" button from "Locations" tab in location view. When the button is clicked, Content Discovery widget is opened allowing to choose many locations where new locations need to be created.
Depending on what is the result of creating locations the behaviour is like follows:
- **Creating new locations for all selected places was successful** - user is notified about successfully added locations and locations list is being refreshed
- **Creating new locations for all selected places failed** - user is notified about each createLocation fail and summary notification informing user that it failed is also displayed
- **Creating some locations from selected …
=> EZP-24812: add location by clicking button "Add location" in location view

Resources/public/css/views/editpreview.css, Resources/public/js/views/ez-editpreviewview.js
Could not find any tests expecting the X/Y values, so should theoretically pass.
As this feature is completely broken w/o this change, I would argue this is an ok approach for now, and somewhat more reliable then calculating height anyway. Would actually be a benefit if we could rely on % width as well, but that is another topic.
review ping @dpobel
=> Fix preview height, and be relative to viewport

Resources/config/yui.yml, Resources/public/js/models/ez-contentmodel.js, Resources/public/js/views/services/plugins/ez-contentsetmainlocationplugin.js, Resources/public/js/views/tabs/ez-locationviewlocationstabview.js, Resources/public/templates/tabs/locations.hbt, Tests/js/models/assets/ez-contentmodel-tests.js, Tests/js/views/services/plugins/assets/ez-contentsetmainlocationplugin-tests.js, Tests/js/views/services/plugins/ez-contentsetmainlocationplugin.html, Tests/js/views/tabs/assets/ez-locationviewlocationstabview-tests.js, Tests/js/views/tabs/ez-locationviewlocationstabview.html
Jira: https://jira.ez.no/browse/EZP-24815
The goal of this PR is to allow user to change main location of content.
On the locations list of the content (Locations tab) the new columns is added named "Main". It contains radio button which is checked if location is main location of content.
Clicking on not-checked radio will open confirm box that will ask user for confirm the main location change. If user confirm then main location is changed to the selected one and the view location list is reloaded.
Plugin is using `updateContentMetadata` method of ez-js-rest-client's contentService and it seems that I encounter REST API bug, that throws error about not-existing location when the passed location actually exists, bug described here: https://jira.ez.no/browse/EZP-24901
So until mentioned …
=> EZP-24815: change main location of content

Resources/public/js/apps/ez-platformuiapp.js, Resources/public/js/views/services/ez-languageselectionboxviewservice.js, Tests/js/apps/assets/ez-platformuiapp-tests.js, Tests/js/views/services/assets/ez-languageselectionboxviewservice-tests.js, Tests/js/views/services/ez-languageselectionboxviewservice.html
Jira: https://jira.ez.no/browse/EZP-24865
Currently the available languages list (systemLanguageList) was hardcoded, for example languageSelectionBox was using hardcoded list of languages. This PR allows injecting languages list into app by adding to config `languages` attribute that should contain array of language objects. If config contains such language list, then it's dispatched to `systemLanguageList` attribute of app object. `systemLanguageList` contains language list but not as array anymore, but as hash indexed by languageCode.
In this PR I also make use of this improvement, by getting `systemLanguageList` app attribute for `availableTranslations` attribute of LanguageSelectionBoxView Service.
This issue is related to https://jira.ez.no/browse/EZP-24875 which covers adding …
=> EZP-24865: inject language list

Resources/config/services.yml, Rest/ContentUserGateway.php, Rest/UserFieldTypeProcessor.php
When a ContentCreate for a User is POSTed, it is handled by the ContentUserGateway.
It creates the user, using the User API, from the request, and returns the created user.
No controller is used in the process, it all happens in the event.
=> Implemented ContentCreate/UserCreate gateway

Resources/public/css/theme/views/subitemlist.css, Resources/public/css/theme/views/tabs/relations.css, Resources/public/css/views/tabs/relations.css, Resources/public/templates/subitemlist.hbt, Resources/public/templates/tabs/relations.hbt
Link: https://jira.ez.no/browse/EZP-24892
When an object has no relation, an empty table was displayed.
Also, while at it, I fixed a small display bug in a separate commit.
Manual test
=> Fix EZP-24892: The relation tab always displays table even without any relation

Resources/config/yui.yml, Resources/public/js/models/ez-locationmodel.js, Resources/public/js/views/services/plugins/ez-locationremoveplugin.js, Resources/public/js/views/tabs/ez-locationviewlocationstabview.js, Resources/public/templates/tabs/locations.hbt, Tests/js/models/assets/ez-locationmodel-tests.js, Tests/js/views/services/plugins/assets/ez-locationremoveplugin-tests.js, Tests/js/views/services/plugins/ez-locationremoveplugin.html, Tests/js/views/tabs/assets/ez-locationviewlocationstabview-tests.js, Tests/js/views/tabs/ez-locationviewlocationstabview.html
Jira: https://jira.ez.no/browse/EZP-24813
The goal of this PR is to allow the user to remove location(s) of content by selecting them from locations list (Locations tab) and clicking "Remove selected" button. After that, cnofirm box appears.
The main location's checkbox is disabled as we don't want to remove main location.
https://youtu.be/_NH-FNh1xn8
=> EZP-24813: remove locations

Resources/public/js/views/fields/ez-author-editview.js, Tests/js/views/fields/assets/ez-author-editview-tests.js
jira: https://jira.ez.no/browse/EZP-24353
When editing a already filled content with author field to empty the "is empty" message was not dislpayed.
The problem wame from the fact that an empty email is considered as valid ( when the field is not requiered ), and that it was the only check in the _getFieldValue() of the field to check if the fieldValue has a value. So when giving an empty one the value was filled by an object with 3 empty properties (name, email, id), which wasn't considered as an empty field for the view.
Solved by adding an _hasContent() check to the author list in the _getFieldValue()
=> EZP-24353 Updating author field to empty does not show empty message

Resources/public/js/views/services/ez-locationviewviewservice.js, Tests/js/views/services/assets/ez-locationviewviewservice-tests.js
Jira: https://jira.ez.no/browse/EZP-24928
After sending content to trash the app should navigate to the parent location of content which was broken. This PR solves it, and after sending content to trash the app is navigating to the parent location.
The reason of the problem was probably changed structure of the `path` attribute as it now contains eZ.Location objects.
=> Fix EZP-24928: app is correctly navigating to parent location after removing content

Resources/public/css/theme/views/fields/edit/author.css
jira: https://jira.ez.no/browse/EZP-24356
The error message of author field wasn't shown (and also the red highlight of the field definition) while editing it with wrong values. This was due to an invalid CSS rule.
=> EZP-24356 Error explanation does not show when editingt author field

Resources/public/css/views/universaldiscovery/browse.css
JIRA: https://jira.ez.no/browse/EZP-24926
when the tree is too big, the UDW is completely broken. This was initially [the case only in Firefox](https://jira.ez.no/browse/EZP-24086) but lately the bug also appears in Chrome.
manual tests (also works well in IE11)
=> Fix EZP-24926: UWD Content Tree becomes unusable with a big tree

Resources/public/js/views/serverside/ez-sectionserversideview.js, Resources/public/js/views/services/ez-sectionserversideviewservice.js, Tests/js/views/serverside/assets/ez-sectionserversideview-tests.js, Tests/js/views/services/assets/ez-sectionserversideviewservice-tests.js
Link: https://jira.ez.no/browse/EZP-24185
When assigning a content to a section, the content count was not updated. The fix refreshed the whole view (not the whole page) involving only one ajax request.
=> Fix EZP-24185: Assigned Content count not updated after assigning a section

Resources/public/css/theme/views/fieldedit.css
Little CSS fix (bold for fiedldefinition-name while editing content ) due to an error insert with the merge of https://github.com/ezsystems/PlatformUIBundle/pull/298
=> Fix Css for fielddefinition name in content edit

Resources/config/css.yml, Resources/public/css/modules/pure-grid.css
JIRA: https://jira.ez.no/browse/EZP-22567
This is a Pure Grid bug reported in https://github.com/yahoo/pure/issues/436. It comes from the fact that in Firefox Pure Grids fallbacks to an `inline-block` based grid system even though Firefox supports flexbox for a while now. This patch is a workaround so that flexbox is used when available.
More generally this brings [the question of using Pure Grid](https://jira.ez.no/browse/EZP-24963), it seems we only support browsers where we can use flexbox so at some point we should/could get rid of Pure Grids.
manual test
=> Fix EZP-22567: Incorrect display of the too high field edit views in Firefox

Resources/public/js/views/fields/ez-binaryfile-editview.js, Tests/js/views/fields/assets/ez-binaryfile-editview-tests.js
JIRA: https://jira.ez.no/browse/EZP-24958
It impossible to update BinaryFile fields in PlatformUI. This is happening because the field value of such fields has a `url` property when loading the content but this property should not be in the field value when storing a new file in the field.
manual + unit test
=> Fix EZP-24958: Impossible to update BinaryFile fields

Resources/public/js/views/fields/ez-richtext-editview.js
JIRA: https://jira.ez.no/browse/EZP-24907
This patch fixes the issue where it's impossible to create a Content with a RichText field in Firefox. This is happening because of our custom XML namespace. For a strict DOM Parser this default namespace basically means we are handling something which is not an XHTML document and then when creating a paragraph with the DOM API, it gets an `xmlns` attribute that breaks the RichText parser.
=> Fix EZP-24907: Impossible to save a Content with a RichText field in Firefox

Resources/public/templates/tabs/details.hbt
Link: https://jira.ez.no/browse/EZP-24945
We decided to remove visibility from the details tab as it is now available in the locations tab.
What it looks like now:
Manual  tests
=> Fix EZP-24495: Hiding/revealing not updating visibility in Details tab

Resources/public/js/views/ez-contenteditformview.js, Resources/public/js/views/ez-rawcontentview.js, Tests/js/views/assets/ez-contenteditformview-tests.js, Tests/js/views/assets/ez-rawcontentview-tests.js
Jira: https://jira.ez.no/browse/EZP-24806
There is a problem, when we have got for example Article created with legacy BO and we want to view it with PlatformUI. For my case it was because Article created with legacy BO hasn't got star_rating field and field definitions for that contentType is pointing that there is such field.
In general - if viewed (or edited) content object didn't contain field that was defined in content's contentType field definitions, the app was throwing error and app was blocked because of that.
This PR solves it, by checking if edited/previewed content contains a field from contentType fieldDefinitions - if yes, view for this field is built and added to field views. Otherwise app is not trying to create view for that field anymore and instead just pushes warn …
=> Fix EZP-24806: Location view of new articles is broken

Resources/public/js/alloyeditor/plugins/addcontent.js, Tests/js/alloyeditor/plugins/assets/ez-alloyeditor-plugin-addcontent-tests.js
JIRA: https://jira.ez.no/browse/EZP-24777
This patch makes sure the content we add with the `eZAddContent` command is never empty by adding a `<br>`. This prevents the JS error from happening and this is actually what CKEditor does if you hit Enter to add a paragraph for instance.
=> Fix EZP-24777: JS error when changing the heading level after adding a heading

Resources/public/js/views/fields/ez-emailaddress-editview.js, Tests/js/views/fields/assets/ez-emailaddress-editview-tests.js
Jira: https://jira.ez.no/browse/EZP-24962
In PlatformUI email address validation relies on built-in input type="email" validation and it's differrent from how it looks like in EmailAddressValidator (see https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/FieldType/Validator/EmailAddressValidator.php#L91).
The result of those differences was that PlatformUI was properly validating email address that was after that not validated through REST API call.
This patch solves it, with checking email adrress validity with the same regular expression test as it is in EmailAddressValidator.
=> Fix EZP-24962: differrent email address validation

Controller/RoleController.php
Since we changed back to the old style of role versioning, drafts of published roles have version = published role id. Unpublished role drafts have version = -1. However, the `updateRoleAction()` expects a published role id, which doesn't exist yet for new drafts.
The fix is to try to load the `$roleId` as if it was a draft id first - if that succeeds, we're done, if it fails, we proceed to load draft by role id as before.
https://jira.ez.no/browse/EZP-24990
=> Fix EZP-24990: Create a new role broken PlatformUI

Resources/public/js/views/ez-serversideview.js, Tests/js/views/assets/ez-serversideview-tests.js
JIRA: https://jira.ez.no/browse/EZP-25015
This patch fixes the form serialization done in server side view so that "multiple" select form input are correctly recognized and handled. Before this patch, only the first selected option was included in the data posted to the server.
=> Fix EZP-25015: select "multiple" not correctly serialized in ServerSideView

Resources/public/css/theme/views/fieldedit.css
jira : https://jira.ez.no/browse/EZP-25001
The Selection field dropdown was partially hidden. This was due to a "overflow: hidden" css rule introduced by me with this pull request : https://github.com/ezsystems/PlatformUIBundle/pull/298
This CSS rule can be removed because its use case has disapear with th evolution of the pull request (previously it was there because the 'is touch' description tooltip was hidden  far away on the view when not displayed, and we needed "overflow: hidden" to keep a good display of the whole view, anyway it's not anymore done this way).
=> EZP-25001 Selection field dropdown partially hidden

Resources/public/js/models/ez-contentmodel.js, Resources/public/js/models/ez-locationmodel.js, Resources/public/js/views/ez-subitemlistview.js, Resources/public/js/views/services/plugins/ez-locationsloadplugin.js, Resources/public/js/views/tabs/ez-locationviewlocationstabview.js, Tests/js/models/assets/ez-contentmodel-tests.js, Tests/js/models/assets/ez-locationmodel-tests.js, Tests/js/views/assets/ez-subitemlistview-tests.js, Tests/js/views/services/plugins/assets/ez-locationsloadplugin-tests.js, Tests/js/views/tabs/assets/ez-locationviewlocationstabview-tests.js
Link: https://jira.ez.no/browse/EZP-24964
When in the locations tabs, when changing the visibility of the location being displayed, it would not update the subitem list where most of items (unless they are already hidden) should now show "Hidden by superior".
=> Fix EZP-24964: Hiding/revealing displayed Location not updating sub items

Resources/public/js/models/ez-contenttypemodel.js, Resources/public/js/views/ez-contenteditview.js, Resources/public/js/views/ez-editactionbarview.js, Tests/js/models/assets/ez-contenttypemodel-tests.js, Tests/js/views/assets/ez-contenteditview-tests.js, Tests/js/views/assets/ez-editactionbarview-tests.js, Tests/js/views/ez-contenteditview.html
JIRA: https://jira.ez.no/browse/EZP-25016
This patch hides the *Save* button when editing a user because the UserService does not support draft for users. I also realized without a draft of user, we can not have a preview, so I removed the preview buttons as well.
Together with https://github.com/ezsystems/PlatformUIBundle/pull/401, this should offer a correct User content handling in PlatformUI.
manual test + unit test
=> EZP-25016: Hide the "Save" button when editing users

Resources/public/js/views/ez-editpreviewview.js, Tests/js/views/assets/ez-editpreviewview-tests.js
Jira : https://jira.ez.no/browse/EZP-24927
The preview title was empty when displaying a preview. Now it can be correctly display with the associated languageCode.
:warning:  But to see the preview title you need to have saved your draft before ! This is due to the fact that there isn't a version of the content before saving it (we can't use currentVersion neither). https://jira.ez.no/browse/EZP-24931 is related to the same problem.
=> EZP-24927_Preview_title_empty

Resources/public/css/theme/views/navigationhub.css, Resources/public/css/views/navigationhub.css
JIRA: https://jira.ez.no/browse/EZP-24055
Before the patch (IE 11, Firefox, Chrome):
After the patch (IE 11, Firefox, Chrome):
=> Fix EZP-24055: Navigation hub is badly rendered in IE

Resources/public/js/alloyeditor/plugins/focusblock.js, Tests/js/alloyeditor/plugins/assets/ez-alloyeditor-plugin-focusblock-tests.js, Tests/js/alloyeditor/plugins/ez-alloyeditor-plugin-focusblock.html
JIRA: https://jira.ez.no/browse/EZP-24971
This patch fixes an issue where the class used to style the focused element in the editor is not correctly removed when the RichText edit view retrieves the editor's content. As visible in the patch, it also contains a workaround for [a bug in the RichText parser not accepting an empty `class` attribute](https://jira.ez.no/browse/EZP-25028)...
=> Fix EZP-24971: Remaining is-block-focused class in the saved richtext html

Resources/views/Role/view_role.html.twig
This just removes the links for now, since other issues are more important. To be fixed later with follow-up: https://jira.ez.no/browse/EZP-25030
https://jira.ez.no/browse/EZP-24948
=> Fix EZP-24948: clicking on user groups name in role details view raises notification error

Resources/public/js/models/extensions/ez-contentinfo-attributes.js, Resources/public/js/models/ez-restmodel.js, Tests/js/models/assets/ez-restmodel-tests.js
JIRA: https://jira.ez.no/browse/EZP-24986
Before this patch and since https://github.com/ezsystems/PlatformUIBundle/commit/d658524c640454fcdf4648ccdca7b8428730f020 it was impossible to create a content in Safari. This was happening because the Content model has an invalid date as default value for the attribute `publishedDate` and the date setter does not validate its input so an invalid date is put in this attribute and Safari throws when calling `toJSON` on that.
So this patch changes the default value and makes the date setter a bit more robust against its input.
unit tests + manual test by @sunpietro (thanks !)
=> EZP-24986: Unable to create a new content using PlatformUI in Safari

Resources/public/js/views/ez-contenteditformview.js, Resources/public/js/views/ez-contenteditview.js, Resources/public/js/views/ez-fieldeditview.js, Tests/js/views/assets/ez-fieldeditview-tests.js, Tests/js/views/fields/assets/ez-richtext-editview-tests.js, Tests/js/views/fields/assets/getfield-tests.js
Jira: https://jira.ez.no/browse/EZP-24625
When editing the content in another language than main language the app has been notifying about error after trying to publish the content. It was specific for contents that have non-translatable fields, for example default folder's `show_children` attribute.
This PR solves it, checking for each field if it's translatable or not. If yes, languageCode for that field is set to given one, otherwise languageCode is set to mainLanguageCode of the content.
=> Fix EZP-24625: impossible to edit the content in another language than main language code

Resources/public/js/views/services/plugins/ez-publishdraftplugin.js, Tests/js/views/services/plugins/assets/ez-publishdraftplugin-tests.js
Jira: https://jira.ez.no/browse/EZP-25035
When content is being published in PlatformUI, user is being notified about that publishing process has started but after it is successfully finished app is just navigating to the published content without changing notification state to `done`. This PR fixes that issue.
=> Fix EZP-25035: notify user about content was successfully published

Resources/public/js/views/fields/ez-richtext-editview.js, Tests/js/views/fields/assets/ez-richtext-editview-tests.js
Link: https://jira.ez.no/browse/EZP-24967
YUI generates ids. We avoid using it for xml parsing and we now remove them along with any ids (as we don't need them).
=> Fix EZP-24967: Saved RichText content has auto-generated YUI ids

Controller/ContentTypeController.php, Controller/RoleController.php, Controller/SectionController.php
These affected forms all assume that a submit button has been clicked. This is not the case when you have pressed the enter key instead. In that case I now pass `null` for action, meaning that only the default form action is dispatched.
Note: The forms behave a bit differently because actions are set up differently. When pressing enter, the role and content type edit forms save and reload. The section and content type group forms save and close.
https://jira.ez.no/browse/EZP-24942
Also required: https://github.com/ezsystems/repository-forms/pull/53
=> Fix EZP-24942: Press <Enter> in repository form raises a notification error

Resources/public/js/views/fields/ez-binaryfile-editview.js, Tests/js/views/fields/assets/ez-binaryfile-editview-tests.js
Link: https://jira.ez.no/browse/EZP-25040
An outdated mime type was provided when updating a File. Since the API is not using this mime type we remove it (instead of updating it).
Unit test and manual
=> Fix EZP-25040: Wrong mimeType is sent after updating a binary file

Resources/public/css/views/fields/edit/author.css, Resources/public/templates/fields/edit/authorinput.hbt
jira: https://jira.ez.no/browse/EZP-24356
The error message was partially hidden when longer than a row ( without description attached to the author field ). This is now fixed by altering the authorInput edit field template, now each input of the author (name and email) have it's own row element, instead of having the two on one row element.
=> Fix EZP-24356: author error  message display problem

Resources/public/js/views/ez-universaldiscoveryview.js, Resources/public/js/views/universaldiscovery/ez-universaldiscoverybrowseview.js, Resources/public/js/views/universaldiscovery/ez-universaldiscoverymethodbaseview.js, Resources/public/js/views/universaldiscovery/ez-universaldiscoveryselectedview.js, Tests/js/views/assets/ez-universaldiscoveryview-tests.js, Tests/js/views/universaldiscovery/assets/ez-universaldiscoverybrowseview-tests.js, Tests/js/views/universaldiscovery/assets/ez-universaldiscoveryselectedview-tests.js
Jira: https://jira.ez.no/browse/EZP-24989
Currently UDW allows to pick up any readable content. This PR allows developer to provide to `contentDiscover` event `isSelectable` function inside config object. `isSelectable` function should return bool value depending on that if content is selectable or not. `isSelectable` function receives selected content struct:
```javascript
{
'contentInfo': eZ.ContentInfo,
'contentType': eZ.ContentType,
'location': eZ.Location
}
```
So basing on selection developer can decide if selected content is allowed for selection or not, for example if selected content is container.
If function return `FALSE` then content is not selectable.
What's more, following @dpobel's instructions, the `isAlreadySelected` function is now passed to the method view so we can …
=> EZP-24989: Restrict the possible selection made through the UDW

Resources/public/js/views/fields/ez-emailaddress-editview.js, Tests/js/views/fields/assets/ez-emailaddress-editview-tests.js
Jira: https://jira.ez.no/browse/EZP-25051
It fixes regression introduced by https://jira.ez.no/browse/EZP-24962 where email address field was always required, no matter if it was defined to be required or not.
This PR changes the validation mechanism to check valid with regexp only if field is not empty.
=> Fix EZP-25051: email address is always required

Resources/public/js/views/services/ez-contenteditviewservice.js, Tests/js/views/services/assets/ez-contenteditviewservice-tests.js
Jira: https://jira.ez.no/browse/EZP-25048
When creating the content inside another newly created content the languageCode is not passed in the request so languageCode for content edit view service is empty - this happends in eZ Studio.
This PR solves it by setting the fallback to the mainLanguageCode of the content if languageCode param is not passed in the request.
=> Fix EZP-25048: set fallback languageCode if it is not passed in the request

Resources/public/js/views/services/ez-locationviewviewservice.js, Resources/public/js/views/services/plugins/ez-copycontentplugin.js, Resources/public/js/views/services/plugins/ez-locationcreateplugin.js, Tests/js/views/services/assets/ez-locationviewviewservice-tests.js, Tests/js/views/services/plugins/assets/ez-copycontentplugin-tests.js, Tests/js/views/services/plugins/assets/ez-locationcreateplugin-tests.js
Jira: https://jira.ez.no/browse/EZP-24973
Currently, when creating new location for content, copying content or moving content to new location, there is possibility to select non-container with UDW.
This PR solves it by defining new `isSelectable` function which is checking in mentioned cases wether the selected content is container.
On the screencast (available here: https://youtu.be/sndSxmLihmI) you can see how restricting selection in UDW basing on non-container type is done.
First part shows how it behaves when creating new locations for content (multiple selection mode). Second and third part show how it behave for single selection mode (relatively copy and move content).
=> Fix EZP-24973: forbid non-containers to be selected as parent location through UDW for add new location, copy and move

Resources/public/js/views/fields/ez-relationlist-editview.js, Tests/js/views/fields/assets/ez-relationlist-editview-tests.js
Jira: https://jira.ez.no/browse/EZP-24993
Currently, when new custom content type is being created and it contains relations list field, there is possibility to select as relations the content that content type is not allowed for it.
This PR solves it by checkin in `isSelectable` UDW's method if selected content's content type is one the allowed content types list.
=> Fix EZP-24993: restrict possible UDW selection to defined in relations list allowed content types

Form/Processor/PolicyFormProcessor.php
> https://jira.ez.no/browse/EZP-25079
This basically adds a default redirect response.
When publishing the policy, this response will be overriden by the one defined in `processSavePolicy()`.
Note that the policy draft was updated in repository-forms (see [related PR on repository-forms](https://github.com/ezsystems/repository-forms/pull/57)).
=> Fix EZP-25079: When saving a new policy draft module/function choice is lost

Resources/public/js/views/fields/ez-richtext-editview.js, Resources/public/templates/fields/edit/richtext.hbt, Tests/js/views/fields/assets/ez-richtext-editview-tests.js, Tests/js/views/fields/ez-richtext-editview.html
JIRA: https://jira.ez.no/browse/EZP-25031
Before, this patch, if a user uses Backspace in an empty RichText field, the editor is completely messed up. This is happening because the editor is configured on a non editable element containing the root `section` element which is made editable. As a result, the `section` element can be removed.
To avoid that, this patch changes the way the editor is configured so that the `section` becomes the *editor element* so that it can not be removed. As a benefit, this avoids having to deal with the custom namespace like I did in [EZP-24907](https://jira.ez.no/browse/EZP-24907) / https://github.com/ezsystems/PlatformUIBundle/pull/382
manual test + unit tests
=> Fix EZP-25031: Inconsistent editor state after <Backspace>

Resources/public/js/models/ez-contentmodel.js, Tests/js/models/assets/ez-contentmodel-tests.js
JIRA: https://jira.ez.no/browse/EZP-25091
Requires https://github.com/ezsystems/ez-js-rest-client/pull/68
This patch makes sure we set the "always available" flag value based on the `defaultAlwaysAvailable` value set in the content type when creating a content item.
=> Fix EZP-25091: "always available" flag is always set on content creation

Resources/config/yui.yml, Resources/public/js/models/ez-contentinfomodel.js, Resources/public/js/models/ez-contentmodel.js, Resources/public/js/views/services/ez-contenteditviewservice.js, Tests/js/models/assets/ez-contentinfomodel-tests.js, Tests/js/models/assets/ez-contentmodel-tests.js, Tests/js/views/services/assets/ez-contenteditviewservice-tests.js, Tests/js/views/services/assets/fake-models.js
JIRA: https://jira.ez.no/browse/EZP-24766
It's impossible to translate a content without the "always available" flag. This issue was "hidden" because of [EZP-25091](https://jira.ez.no/browse/EZP-25091) (see https://github.com/ezsystems/ez-js-rest-client/pull/68 and https://github.com/ezsystems/PlatformUIBundle/pull/431).
So basically, this patch adds the loading of the content info to check if the content exists and then adds the necessary logic so that no matter if the content is always available or not, it can be translated.
=> EZP-25091: Impossible to translate a content without the the always available flag

Resources/public/js/views/ez-contenteditformview.js, Resources/public/js/views/ez-contenteditview.js, Resources/public/js/views/ez-fieldeditview.js, Resources/public/js/views/fields/ez-author-editview.js, Resources/public/js/views/services/ez-contenteditviewservice.js, Tests/js/views/assets/ez-contenteditview-tests.js, Tests/js/views/fields/assets/ez-author-editview-tests.js, Tests/js/views/fields/assets/getfield-tests.js, Tests/js/views/services/assets/ez-contenteditviewservice-tests.js
jira : https://jira.ez.no/browse/EZP-24050
The goal here was to be able to see the first author of a new content with an empty author field, prefilled by the current use.
http://youtu.be/ZuW6X613VPQ
=> Fix EZP-24050: The first author is prefilled when the content is new

Resources/public/js/views/fields/ez-dateandtime-editview.js, Resources/public/js/views/fields/ez-time-editview.js, Resources/public/js/views/fields/ez-time-view.js, Tests/js/views/fields/assets/ez-dateandtime-editview-tests.js, Tests/js/views/fields/assets/ez-dateandtime-view-tests.js, Tests/js/views/fields/assets/ez-time-view-tests.js, Tests/js/views/fields/ez-dateandtime-view.html, Tests/js/views/fields/ez-time-view.html
Link: https://jira.ez.no/browse/EZP-24040
This PR contains two fixes for Date and Time attributes
The time is now stored and displayed in UTC. It doesn't have to be timezone aware are it's just a plain data.
The API stores DateAndTime fields in UTC format and doesn't store the timezone. This patch converts back and forth UTC to local time in order to display something meaningful to the user.
(Lots of) manual test. Updated Unit test. It is at the moment not possible to automate more testing because of locale limitation in the headless browser used to run our unit tests.
=> Fix EZP-24040: Date/Time attributes are not timezone friendly

Resources/public/js/apps/ez-platformuiapp.js, Resources/public/js/models/ez-contentmodel.js, Resources/public/js/models/ez-versionmodel.js, Resources/public/js/views/services/ez-contenteditviewservice.js, Resources/public/js/views/services/plugins/ez-discarddraftplugin.js, Resources/public/js/views/services/plugins/ez-publishdraftplugin.js, Tests/js/models/assets/ez-versionmodel-tests.js, Tests/js/views/services/assets/ez-contenteditviewservice-tests.js, Tests/js/views/services/plugins/assets/ez-discarddraftplugin-tests.js, Tests/js/views/services/plugins/assets/ez-publishdraftplugin-tests.js
JIRA: https://jira.ez.no/browse/EZP-25133
requires: https://github.com/ezsystems/ez-js-rest-client/pull/69
This patch adds a route to be able to edit a draft version of a content. It also cleans up the way the editor is redirected to be easier to tweak from a PlatformUI extension bundle and it also decouples a bit the publish draft and discard draft plugins from the content edit view service.
Manual and unit tests.
=> EZP-25133: Allow to edit a draft version of a content

Resources/public/js/views/services/plugins/ez-publishdraftplugin.js, Tests/js/views/services/plugins/assets/ez-publishdraftplugin-tests.js
Jira : https://jira.ez.no/browse/EZP-25154
When publishing a content, when successing, a second notification saying that the content has been published is appearing next to the first one saying that the content is being published.
Instead of doing 2 notifications, the first notification should be updated.
The bug came from the fact when we are creating a new content, it has no contentId so the notification identifier could not match and that's why we have a second notification instead of replacing the first one.
-  [x] Unit tests
-  [x] Manual tests
=> Fix EZP-25154: Update notification when creating new  content

Resources/public/js/views/ez-editpreviewview.js, Tests/js/views/assets/ez-editpreviewview-tests.js, Tests/js/views/ez-editpreviewview.html
JIRA: https://jira.ez.no/browse/EZP-25130
In a clean install, if the editor edits the eZ Publish root content and tries to preview it, the preview iframe displays a 404 page. This is happening because this object has only one version which number is 6 and the preview is generated for a version with `versionNo` set to 1 because no version has been created yet. This is kind of related to [EZP-24931](https://jira.ez.no/browse/EZP-24931) but in that case, we can detect the issue and generate the preview of the current version instead. This will also allow to easily reuse the preview component while viewing a content (outside of the editing process) (see https://jira.ez.no/browse/EZP-24740)
=> Fix EZP-25130: 404 when previewing default eZ Publish object

Gruntfile.js, Resources/config/yui.yml, Resources/public/js/alloyeditor/processors/base.js, Resources/public/js/alloyeditor/processors/removeids.js, Resources/public/js/alloyeditor/processors/xhtml5edit.js, Resources/public/js/views/fields/ez-richtext-editview.js, Tests/js/alloyeditor/processors/assets/ez-editorcontentprocessorbase-tests.js, Tests/js/alloyeditor/processors/assets/ez-editorcontentprocessorremoveids-tests.js, Tests/js/alloyeditor/processors/assets/ez-editorcontentprocessorxhtml5edit-tests.js, Tests/js/alloyeditor/processors/ez-editorcontentprocessorbase.html, Tests/js/alloyeditor/processors/ez-editorcontentprocessorremoveids.html, Tests/js/alloyeditor/processors/ez-editorcontentprocessorxhtml5edit.html, Tests/js/views/fields/assets/ez-richtext-editview-tests.js, Tests/js/views/fields/ez-richtext-editview.html
JIRA: https://jira.ez.no/browse/EZP-25161
It's impossible to save a content item with a RichText field in Firefox (nor in IE11). This is happening because of the way we build the XHTML5Edit version of the RichText field and especially because of our usage of a namespace in this format...
To avoid that, we are kind of forced to build the XML by concatenating strings... While at it, I also refactored this part by delegating the editor's content clean up to a set of dedicated components (`EditorContentProcessors`).
unit tests and manual tests in Chrome, Firefox and IE11.
=> Fix EZP-25161: Impossible to publish a content with a Richtext field with Firefox

Resources/public/js/views/ez-subitemlistview.js, Tests/js/views/assets/ez-subitemlistview-tests.js
jira: https://jira.ez.no/browse/EZP-25175
When a folder had as many children as a multiple of its subitems list limit per page, the subitems list would not show if you try to go to the last page. The reason of that is incorrect calculation for offset for last page which fails in case when total number of results is multiplication of page limit.
- Manual tests
- Unit tests
=> Fix EZP-25175: Setting incorrect pagination offset in subitems view

Resources/public/js/views/universaldiscovery/ez-universaldiscoverysearchview.js, Tests/js/views/universaldiscovery/assets/ez-universaldiscoverysearchview-tests.js
Jira: https://jira.ez.no/browse/EZP-25177
While investigating the problem I found 2 things that were involved in generating the problem:
- this._fireLocationSearch was triggered on change of 2 attributes: `offset` and `searchText` so there were 2 almost simultaneus calls when new search was started - one with changed searchText (but still with old offset) and just after that the second one with reseted offset. So displayed results can be randomly from first or second search...
To solve this one I have stopped listening on `offsetChange` and call `this._fireLocationSearch` for every page change.
- As there is locationSearch triggered on `searchTextChange` event so when the view is being reset the problems also happens. So just after UDW was being closed the …
=> Fix EZP-25177: search result persist after UDW reloads

Resources/public/css/layout.css, Resources/public/css/theme/views/notification.css, Resources/public/css/views/notificationhub.css, Resources/public/js/apps/plugins/ez-positionplugin.js, Resources/public/js/views/ez-notificationhubview.js, Resources/views/PlatformUI/shell.html.twig, Tests/js/apps/plugins/assets/ez-positionplugin-tests.js, Tests/js/views/assets/ez-notificationhubview-tests.js
Jira: https://jira.ez.no/browse/EZP-25076 and https://jira.ez.no/browse/EZP-25147
This PR solves the problem with positioning edit content preview view when triggered while displaying notifications by moving notifications to the bottom of the screen.
YT: https://youtu.be/bWgrP-YVN4U
In first part you can see current (improper) behavior. After presenting that I'm switching branch in the background and reloading the app so after that you can see behavior within the patch. What's more you can see example of how the notifications are added to the notifications container after patch (they are added from bottom to top).
On the video you can notice that the Symfony toolbar is overlapping first (the lowest) notification.
=> EZP-25076: Move notifications to the bottom

Resources/public/js/alloyeditor/processors/xhtml5edit.js, Tests/js/alloyeditor/processors/assets/ez-editorcontentprocessorxhtml5edit-tests.js
JIRA: https://jira.ez.no/browse/EZP-25188
yet again an HTML parsing issue to generate the xhtml5edit version of a RichText field, this time because the RichText editor generates some HTML5 while the parser expects something that looks like *XHTML5*.
manual (IE11, Firefox, Chrome) + unit tests
=> Fix EZP-25188: Error 406 on publishing richtext content with embedded image

Resources/public/css/views/contentedit.css
Jira: https://jira.ez.no/browse/EZP-25191
As described in Jira issue, action bar is badly rendered in Edge browser. It is rendered positioned to the top left.
It seems that Edge is interpreting `postition: fixed` without `left` or `right` attributes in different way that other browsers. It is positioning such object without relation to other objects in the same container so the effect is the same as it would have `left: 0;`.
This PR sets `right` attribute so action bar is positioned to the right edge of the screen.
Manual in: IE Edge (12), IE 11, Chrome, Firefox, Safari, Yandex
=> Fix EZP-25191: action bar rendering in Edge

Resources/public/js/views/actions/ez-buttonactionview.js, Resources/public/js/views/actions/ez-previewactionview.js, Resources/public/js/views/ez-contenteditview.js, Resources/public/js/views/ez-editpreviewview.js, Resources/public/js/views/services/plugins/ez-savedraftplugin.js, Tests/js/views/actions/assets/ez-previewactionview-tests.js, Tests/js/views/assets/ez-contenteditview-tests.js, Tests/js/views/assets/ez-editpreviewview-tests.js, Tests/js/views/services/plugins/assets/ez-savedraftplugin-tests.js
JIRA: https://jira.ez.no/browse/EZP-24931
This patch fixes the issue where the preview would give expected and wrong result if the draft was not saved yet. Basically, when the user wants a preview, the generated event is transformed into a save draft event and the callback of this one actually triggers the preview.
Screencast: http://youtu.be/gw7RrHRu1D8
=> Fix EZP-24931: Unexpected result in the preview if the draft has not been saved

Resources/public/css/alloyeditor/general.css
JIRA: https://jira.ez.no/browse/EZP-25182
Make sure the "add content" toolbar is displayed in focus mode.
manual tests
=> Fix EZP-25182: RichText "Add content" toolbar doesn't appear in focus mode

Resources/public/css/alloyeditor/buttons/labeled-button.css, Resources/public/css/theme/alloyeditor/general.css
JIRA: https://jira.ez.no/browse/EZP-25189
Replaces https://github.com/ezsystems/PlatformUIBundle/pull/462
This is fixing a display issue in IE11 (and Edge) because of IE10+ specific rule setting a fixed height in the AlloyEditor CSS (we can not really change that in our skin).
While at it, I also fixed a small gap between the toolbar tail and the toolbar itself.
manual test in IE11, Chrome and Firefox (currently installing a VM to test with Edge)
=> Fix EZP-25189: Richtext tollbar container doesn't render correctly on IE11/Edge

Resources/config/yui.yml, Resources/public/js/views/ez-dashboardview.js, Resources/public/js/views/ez-studiopluspresentationview.js, Resources/public/js/views/ez-studiopresentationview.js
Link: https://jira.ez.no/browse/EZP-25233
This issue was introduced when the parameter was added to the `uiSetHeight` method.
https://github.com/ezsystems/PlatformUIBundle/commit/15b15eb8605b225afb37cded5257f947011bd20c#diff-b264e14fcac4d2600fa40aab505b968bR39
When called in an event, the parameter was by default an event facade, meaning not a Number as expected. This patch makes sure the method is called with `0` as parameter. I also added missing dependencies (it worked without them because they were called by other modules).
Thanks @dpobel for the big hint on this one.
Manual test. This part of the code is not unit tested as window resize is not easy to simulate.
=> Fix EZP-25233: Two scrollbar on iframes

Resources/public/css/theme/views/actions/button.css, Resources/public/js/views/actions/ez-buttonactionview.js, Resources/public/templates/createcontentaction.hbt, Tests/js/views/actions/assets/ez-buttonactionview-tests.js, Tests/js/views/actions/ez-buttonactionview.html
JIRA: https://jira.ez.no/browse/EZP-25209
The issue is about styling the buttons in the bar views when they are disabled and especially the "Create" button. While working on that, I also discovered that the *disabled logic* was actually implemented in the template for the create button and not implemented at all in the generic button.
So this PR fixes EZP-25209 (in c5043f7) and makes sure the button action view implements the disabled logic instead of relying on the template.
=>  Fix EZP-25209: Create button seems available even if it's not

Resources/views/ContentType/edit_content_type_group.html.twig, Resources/views/ContentType/update_content_type.html.twig, Resources/views/Language/edit.html.twig, Resources/views/Role/edit_policy.html.twig, Resources/views/Role/update_role.html.twig, Resources/views/Section/edit.html.twig
> Jira: https://jira.ez.no/browse/EZP-25225
This PR removes trash icon from the cancel button in the edit content type view.
While fixing that I've checked another serverside views and there are also the same issue, so I have removed the trash icon from cancel button also in following views (all are in admin panel):
- edit content type group
- edit language
- edit role
- edit role's policies
- edit section
=> Fix EZP-25225: remove trash icon from cancel button in contenttype edit view

Resources/config/yui.yml, Resources/public/css/views/actions/translate.css, Resources/public/js/apps/plugins/ez-registerlanguagehelpersplugin.js, Resources/public/js/views/actions/ez-translateactionview.js, Resources/public/templates/contentedit.hbt, Resources/public/templates/languageselectionbox.hbt, Resources/public/templates/languageswitcher.hbt, Resources/public/templates/tabs/details.hbt, Resources/public/templates/translateaction.hbt, Tests/js/apps/plugins/assets/ez-registerlanguagehelpersplugin-tests.js, Tests/js/apps/plugins/ez-registerlanguagehelpersplugin.html, Tests/js/views/actions/assets/ez-translateactionview-tests.js, Tests/js/views/actions/assets/genericbuttonactionview-tests.js
> Jira: https://jira.ez.no/browse/EZP-24866
This PR introduces handlebars helper which returns language name basing on given language code. It takes its from app attribute `systemLanguageList`. If there is no language in that attribute with given language code then the helper returns unformated language code (that's kind of fallback in case of not having language in `systemLanguageList` attribute, which shouldn't happened).
What's more with this PR described `language_name` helper is being used in the templates where language code is being displayed, so in these places from now we will see language name.
Moreover, logic of displaying hint for Translate Action button was changed also.
YT: https://youtu.be/x99U5lXJpwc (bit outdated, currently …
=> EZP-24866: display language name instead of language code

Resources/public/js/views/ez-fieldeditview.js, Resources/public/js/views/ez-fieldview.js, Tests/js/views/assets/ez-fieldeditview-tests.js, Tests/js/views/assets/ez-fieldview-tests.js, Tests/js/views/assets/genericfieldview-tests.js, Tests/js/views/fields/assets/ez-author-view-tests.js, Tests/js/views/fields/assets/ez-binaryfile-view-tests.js, Tests/js/views/fields/assets/ez-checkbox-view-tests.js, Tests/js/views/fields/assets/ez-country-view-tests.js, Tests/js/views/fields/assets/ez-date-view-tests.js, Tests/js/views/fields/assets/ez-dateandtime-view-tests.js, Tests/js/views/fields/assets/ez-float-view-tests.js, Tests/js/views/fields/assets/ez-image-view-tests.js, Tests/js/views/fields/assets/ez-integer-view-tests.js, Tests/js/views/fields/assets/ez-keyword-view-tests.js, Tests/js/views/fields/assets/ez-maplocation-view-tests.js, Tests/js/views/fields/assets/ez-relation-view-tests.js, Tests/js/views/fields/assets/ez-relationlist-view-tests.js, Tests/js/views/fields/assets/ez-richtext-view-tests.js, Tests/js/views/fields/assets/ez-selection-view-tests.js, Tests/js/views/fields/assets/ez-time-view-tests.js, Tests/js/views/fields/assets/ez-url-view-tests.js, Tests/js/views/fields/assets/ez-user-view-tests.js, Tests/js/views/fields/assets/ez-xmltext-view-tests.js
> Jira: https://jira.ez.no/browse/EZP-25192
To ease a bit BDD tests, this PR adds `data-field-definition-identifier` attribute to field views and field edit views.
=> EZP-25192: add field definition identifier to the dom for field views and field edit views

Controller/RoleController.php, Resources/views/Role/view_role.html.twig
> Fixes https://jira.ez.no/browse/EZP-25264
Disable the edit limitations button when the policy cannot have limitations, thus we avoid showing the user an empty edit form.
The general way of doing things is taken from https://jira.ez.no/browse/EZP-23733
The limitation checker line is taken from `editPolicyAction()`.
=> Fix EZP-25264: Policy "Edit limitations" button should be disabled when there is nothing to edit

Resources/config/yui.yml, Resources/public/js/views/actions/ez-movecontentactionview.js, Resources/public/js/views/ez-actionbarview.js, Tests/js/views/actions/assets/ez-movecontentactionview-tests.js, Tests/js/views/actions/ez-movecontentactionview.html, Tests/js/views/assets/ez-actionbarview-tests.js
> Jira: https://jira.ez.no/browse/EZP-25229
This PR fixes the bug when "Move" action button was not disabled for locations of 1st level of content tree ("Content Structure", "Media Library", "Users"). This patch disables "Move" action button for those locations.
=> Fix EZP-25229: disable move action button if given location is the location from 1st level of content tree

Resources/public/css/theme/views/tree.css, Resources/public/js/views/ez-treeview.js, Tests/js/views/assets/ez-treeview-tests.js
> Jira: https://jira.ez.no/browse/EZP-25162
Currently when there is no content created, when opening the content tree the empty space so user don't know that there is no content. This PR provides short message "The Content Tree is empty" in the place of the tree when the tree is empty.
YT: https://youtu.be/e0dQnY19p0U
=> EZP-25162: display info about empty content tree

Resources/public/js/apps/ez-platformuiapp.js, Tests/js/apps/assets/ez-platformuiapp-tests.js
jira: https://jira.ez.no/browse/EZP-25104
When logout then login with a different user, the navigation hub wasn't showing the right user. This was due to the fact that the sideviews weren't destroyed properly when logout.
- Manual tests
- Unit tests
=> Fix EZP-25104: Wrong user name in navigation hub after logout and login with different user

Resources/public/css/theme/views/fields/edit/binarybase.css
jira: https://jira.ez.no/browse/EZP-25215
Due to some recent changes in Chrome, max-height CSS rule isn't working anymore in flexbox for Chrome browser. This was giving us some strange behaviour for field like image or media, with a bad element positioning. This was fixed mostly by forcing the height to '0' instead of max-height: '0'
- Manual tests on differents browsers
=> Fix EZP-25215: Positioning problem on chrome for fields using binarybase

Resources/config/css.yml, Resources/config/yui.yml, Resources/public/css/modules/breadcrumbs.css, Resources/public/css/theme/modules/breadcrumbs.css, Resources/public/css/theme/views/locationview.css, Resources/public/css/theme/views/tabs/locations.css, Resources/public/css/views/locationview.css, Resources/public/js/views/services/plugins/ez-objectrelationsloadplugin.js, Resources/public/js/views/tabs/ez-locationviewrelationstabview.js, Resources/public/templates/locationview.hbt, Resources/public/templates/tabs/relations.hbt, Tests/js/views/services/plugins/assets/ez-objectrelationsloadplugin-tests.js, Tests/js/views/tabs/assets/ez-locationviewrelationstabview-tests.js
> Jira: https://jira.ez.no/browse/EZP-24841
Currently in the related content tab there are being displayed only names of related contents linked with their main location. This PR changes it to display breadcrumbs instead.
=> EZP-24841: display breadcrumbs in the related content tab

Resources/public/js/views/fields/ez-user-editview.js, Tests/js/views/fields/assets/ez-user-editview-tests.js
jira: https://jira.ez.no/browse/EZP-25266
When editing an already existing user there was a check to see if the login was available. Of course this check was always matching the current user edited and throwing an error "this login is already taken"
- Manual tests
- Unit tests
=> EZP-25266: Removing isLoginAvailable check when editing an already existing user

Resources/public/js/apps/ez-platformuiapp.js, Resources/public/js/apps/plugins/ez-registerlanguagehelpersplugin.js, Resources/public/js/views/ez-contenteditformview.js, Resources/public/js/views/ez-contenteditview.js, Resources/public/js/views/services/ez-contentcreateviewservice.js, Tests/js/apps/assets/ez-platformuiapp-tests.js, Tests/js/apps/plugins/assets/ez-registerlanguagehelpersplugin-tests.js, Tests/js/views/assets/ez-contenteditformview-tests.js, Tests/js/views/assets/ez-contenteditview-tests.js, Tests/js/views/services/assets/ez-contentcreateviewservice-tests.js
JIRA: https://jira.ez.no/browse/EZP-25296
This PR enhances https://github.com/ezsystems/PlatformUIBundle/pull/484. It is still about displaying the language name instead of the language code when switching from one language to another after creating a new content.
Changes made on original https://github.com/ezsystems/PlatformUIBundle/pull/484 code:
* improved the naming of various methods
* improved the unit to correctly cover the switching code
* make sure the language name is displayed in the notification as well
=> Fix EZP-25296: display language name after changing language when creating content

Form/Processor/RoleFormProcessor.php
> Fixes https://jira.ez.no/browse/EZP-25203
> Also required: https://github.com/ezsystems/repository-forms/pull/65
Let the default action call the save role action. Let the save role action both save and publish.
=> Fix EZP-25203: Pressing <Enter> when creating a role saves the role but don't publish it

Resources/config/services.yml
JIRA: https://jira.ez.no/browse/EZP-25370 (sub-task of https://jira.ez.no/browse/EZP-25135)
With this patch the PlatformUI Application receives the `image_variations` setting which is the very first step before being able to change the image variation in the RichText editor.
manual tests
=> EZP-25370: Provide image variations config the PlatformUI App

Resources/config/yui.yml, Resources/public/css/theme/alloyeditor/content.css, Resources/public/js/alloyeditor/buttons/list.js, Resources/public/js/alloyeditor/buttons/list.jsx, Resources/public/js/alloyeditor/plugins/addcontent.js, Resources/public/js/views/fields/ez-richtext-editview.js, Tests/js/alloyeditor/buttons/assets/ez-alloyeditor-button-list-tests.jsx, Tests/js/alloyeditor/buttons/ez-alloyeditor-button-list.html, Tests/js/alloyeditor/plugins/assets/ez-alloyeditor-plugin-addcontent-tests.js
JIRA: https://jira.ez.no/browse/EZP-25359
This patch adds a button to the add content toolbar to add an unordered list in the RichText editor.
Screencast:
[![Adding an unordered list in the RichText editor](http://img.youtube.com/vi/YdNzqTaA2-8/0.jpg)](http://www.youtube.com/watch?v=YdNzqTaA2-8)
=> EZP-25359: Add a button to add an unordered list in the RichText editor

Resources/public/css/layout.css
jira : https://jira.ez.no/browse/EZP-23756
When in loading mode, user should not be able to click or hover on anything. This is done with "pointer-events: none" CSS rule.
- Manual tests
=> EZP-23756: When in loading mode, we should not be able to click or hover

Resources/public/js/views/fields/ez-dateandtime-editview.js, Resources/public/js/views/fields/ez-dateandtime-view.js, Resources/public/js/views/fields/ez-time-editview.js, Resources/public/js/views/fields/ez-time-view.js, Tests/js/views/fields/assets/ez-dateandtime-editview-tests.js, Tests/js/views/fields/assets/ez-dateandtime-view-tests.js, Tests/js/views/fields/assets/ez-time-editview-tests.js, Tests/js/views/fields/assets/ez-time-view-tests.js
Link: https://jira.ez.no/browse/EZP-25375
This PR fixes storing and displaying Time and DateAndTime field type with an empty time stamp.
When adding a Time with the value `00:00` it generates a timestamp with the value 0.
The code what checking if the value was set with a:
```javascript
// Please don't be 0 or I'll do something stupid :)
if (timestamp) {
//update
} else {
return null;
}
```
So `null` was returned for a valid timestamp (`0`)
With this patch I found another issue in the kernel when updating a Time with 00:00 https://github.com/ezsystems/ezpublish-kernel/pull/1565
In order to decide if a field is empty or not I added an overriden `isFieldEmpty` in the views and created an equivalent method on the editviews (made the code more readable to me having a dedicated method).
Manual …
=> Fix EZP-25375: Timestamps 0 are not handled properly

Resources/public/css/theme/views/tabs/locations.css, Resources/public/css/views/tabs/locations.css
Improves a bit the locations list display so that the path is aligned correctly.
Before:
After:
manual tests
=> Improved the Locations list display

Controller/SystemInfoController.php, Resources/config/services.yml, Resources/translations/systeminfo.en.xlf, Resources/views/SystemInfo/info.html.twig
~~Also move over version info from the other data source to not duplicate this, means first tab is now called Bundles. @bdunogier only alternative I see regarding the interface is simply deprecate it and rely on the class instead as long as we know we will have to change this over time.*~~~
https://jira.ez.no/browse/EZP-23932
Updated: Simple approach here for 16.02, while @glye works on a more proper approach for 16.04 in separate bundle.
*Bundles tab has been renamed from hard coded "eZ Platform" and if composer info is available will give version of platform ui and kernel from it:*
*New tab listing all packages, most important info is added, including link if defined:*
=> EZP-23932: Show appropriate version information

Features/Context/SubContext/Authentication.php
After https://jira.ez.no/browse/EZP-25446 has been merged ( #513 ) the Behat functions iLogout and iShouldBeLoggedIn became outdated causing scenarios to fail at start.
This PR adds an extra click in the user profile area and changes the logout link identification.
=> Update Behat login functions to match the new user profile

Tests/js/models/assets/ez-restmodel-tests.js
Trying to avoid random failures in REST model tests. Those failures can happen if the 2 compared date objects were not created in the same milliseconds. With this patch, the test will fail only if the dates were not created in the same second, this can still happen but that is 1000 times less likely :)
=> Fixed: avoid random failures in the REST model tests

Resources/public/css/views/tabs/details.css, Resources/public/js/models/ez-locationmodel.js, Resources/public/js/views/services/ez-locationviewviewservice.js, Resources/public/js/views/tabs/ez-locationviewdetailstabview.js, Resources/public/templates/tabs/details.hbt, Tests/js/models/assets/ez-locationmodel-tests.js, Tests/js/views/services/assets/ez-locationviewviewservice-tests.js, Tests/js/views/tabs/assets/ez-locationviewdetailstabview-tests.js, Tests/js/views/tabs/ez-locationviewdetailstabview.html
jira: https://jira.ez.no/browse/EZP-25450
The goal here is to be able to set ordering method for sub item lists.
By default there are 4  "**standard**" sortField types: "Priority", "Content name", "Modification date", "Publication date". They'll always be selectable in the location detail tab view.
But when creating the content type you can select (as it was done with legacy) between 9 sortField type: Content name, Content type name, Content type identifier, Location depth, Location path, Location priority, Modification date, Publication date, Section.
If the selected sortField is not in the "**standard**" ones the location detail tab view will also allow to select this one. (So you can have 5 sortField instead of 4...)
:warning: Currently a bug in the REST API is forcing new contents …
=> EZP-25450: Set ordering method for sub items listing

Resources/public/js/views/ez-usermenuitemfireeventview.js, Resources/public/js/views/ez-usermenuview.js, Tests/js/views/assets/ez-usermenuitemfireeventview-tests.js, Tests/js/views/assets/ez-usermenuview-tests.js
**Jira ticket:** https://jira.ez.no/browse/EZP-25503
=> EZP-25503: The user profile menu stays after opening Notifications form

.ez.yml, .travis.yml, bin/travis/prepare_behat.sh
- Enable travis testing on 1.2
- Pull ezplatform 1.2.0 when testing on behat.
=> [travis] Configured for 1.2 branch

Resources/public/css/layout.css
Replaces https://github.com/ezsystems/PlatformUIBundle/pull/526
=> EZP-25546: Pointer events block scrolling after loading is finished in Google Chrome

.ez.yml, Features/Context/SubContext/CommonActions.php, Resources/public/js/views/services/ez-navigationhubviewservice.js, Tests/js/views/services/assets/ez-navigationhubviewservice-tests.js, composer.json
Link: https://jira.ez.no/browse/EZP-25128
Before this patch. When clicking on a top menu item (like "Content") sub items of this menu would be displayed. With this patch, on top of the existing behavior, the first item is automatically opened.
Also, I fixed a few typos I ran into in separate commits.
Manual and automated
=> EZP-25128: Automatically navigate to 1st item of a zone

.travis.yml, bin/travis/travis-php.ini
> 1.2 version of https://github.com/ezsystems/PlatformUIBundle/pull/539 (passed on master)
> Approved "if travis passes"
Travis is failing on [master](https://travis-ci.org/ezsystems/PlatformUIBundle/builds/119515363) because of memory limit on composer install.
This change disables xdebug, and runs composer without a memory limit (many alternatives were tried until that solution was reached. it works, unlike the many alternatives).
=> Travis memory errors

Features/Context/SubContext/Authentication.php
Jira ticket: https://jira.ez.no/browse/EZP-25646
Since the hiding nav-bar has been introduced in Studio (https://github.com/ezsystems/StudioUIBundle/pull/502) the behat AfterScenario step from Authentication started failing every now and then with this error:
This PR adds one extra step in the logout method which sets focus on the user profile (which now hides together with the nav-bar) before clicking it.
=> EZP-25646: Adjust logout method in behat scenarios to hiding nav-bar

Controller/SystemInfoController.php, Helper/SystemInfoHelper.php, Helper/SystemInfoHelperInterface.php, Resources/config/default_settings.yml, Resources/config/services.yml, Resources/translations/systeminfo.en.xlf, Resources/views/SystemInfo/info.html.twig, Resources/views/ez-support-tools/info/composer.html.twig, Resources/views/ez-support-tools/info/database.html.twig, Resources/views/ez-support-tools/info/hardware.html.twig, Resources/views/ez-support-tools/info/php.html.twig, Resources/views/ez-support-tools/info/symfony_kernel.html.twig, composer.json
> Implement https://jira.ez.no/browse/EZP-25653
> Platform PR: https://github.com/ezsystems/ezplatform/pull/104
Continued from https://github.com/ezsystems/PlatformUIBundle/pull/542
Updated `prepare_behat.sh` according to @bdunogier advice.
=> Fix EZP-25653: Use eZSupportTools in PlatformUI

Controller/RoleController.php, Resources/config/routing_pjax.yml, Resources/config/services.yml, Resources/public/js/views/serverside/ez-roleserversideview.js, Resources/public/js/views/services/ez-roleserversideviewservice.js, Resources/translations/role.en.xlf, Resources/views/Role/assign_role_by_section.html.twig, Resources/views/Role/view_role.html.twig, Tests/js/views/serverside/assets/ez-roleserversideview-tests.js, Tests/js/views/serverside/ez-roleserversideview.html, Tests/js/views/services/assets/ez-roleserversideviewservice-tests.js, Tests/js/views/services/ez-roleserversideviewservice.html
jira: https://jira.ez.no/browse/EZP-25009
The goal is to be able to assign a role to a user or user group with a section and subtree limitation.
:warning: the redirection is not implemented after the role is assigned. Seems it will wait for https://jira.ez.no/browse/EZP-25442
:warning:² <s>Currently it is working with IDs instead of URIs for REST request to assign role to user with limitation. It's not what we are expecting from the REST API. This will be changed when https://github.com/ezsystems/ezpublish-kernel/pull/1569 will be finnish. So it shouldn't be merged before.</s>  Now it's done !
- Manual tests
- Unit tests
=> EZP-25009: Role assignement with section & subtree limitations

Resources/public/js/views/fields/ez-dateandtime-editview.js, Tests/js/views/fields/assets/ez-dateandtime-editview-tests.js, Tests/js/views/fields/ez-dateandtime-editview.html
Link: https://jira.ez.no/browse/EZP-25530
Firefox doesn't support (yet ?)  `get('valueAsNumber')`. This patch refactors a bit to use the input's value and parses it until we improve the general behavior of DateAnd time field on Firefox in [EZP-23925](https://jira.ez.no/browse/EZP-23925)
Manual test on FF and chrome.
=> Fix EZP-25530: Allow saving DateAndTime on Firefox

Resources/public/css/theme/views/actions/button.css, Resources/public/js/apps/plugins/ez-updatetreeplugin.js, Resources/public/js/models/ez-contentmodel.js, Resources/public/js/views/ez-actionbarview.js, Resources/public/js/views/services/ez-locationviewviewservice.js, Tests/js/apps/plugins/assets/ez-updatetreeplugin-tests.js, Tests/js/models/assets/ez-contentmodel-tests.js, Tests/js/views/assets/ez-actionbarview-tests.js, Tests/js/views/services/assets/ez-locationviewviewservice-tests.js
Fixes: https://jira.ez.no/browse/EZP-25642
> Status: work-in-progress
I will need some guide to finish this properly. This tries to delete content insteand of sending content to trash when the content is user type. i have some questions about the code i've written specially for the the testing part. 
Is that the right way to check this? I mean, i'm duplicating lot of code there. Is there any way to extend tests here like we do with phpunit? 
Second. Do we need another icon for deleting or the trash one is enough?
manual and unit tests > in progress
ping @bdunogier @dpobel @StephaneDiot @yannickroger
=> Fix EZP-25642: Change "Send to Trash Button" to "Delete" button for users

Resources/public/js/views/fields/ez-country-editview.js, Tests/js/views/fields/assets/ez-country-editview-tests.js
jira: https://jira.ez.no/browse/EZP-25349
When editing a content with a country field the selection filter was displaying the alpha code instead of the the country name. This bad behaviour came from the fact that the country list (with the names of the countries) was loaded a bit after the field was filled.
To avoid that, we, now, use directly the countryList of the config instead of filling (too lately !) an attribute for the country list. This also means that the attribute countryList ins now **deprecated** and will be removed in PlatformUI 2.0
=> EZP-25349: Editing with country loads value incorrectly

Resources/public/js/views/ez-fieldeditview.js, Resources/public/js/views/fields/ez-date-editview.js, Resources/public/js/views/fields/ez-maplocation-editview.js, Resources/public/js/views/fields/ez-richtext-editview.js, Resources/public/js/views/fields/ez-selection-editview.js, Resources/public/templates/fields/edit/image.hbt, Tests/js/views/assets/ez-fieldeditview-tests.js, Tests/js/views/fields/assets/ez-country-editview-tests.js, Tests/js/views/fields/assets/ez-date-editview-tests.js, Tests/js/views/fields/assets/ez-maplocation-editview-tests.js, Tests/js/views/fields/assets/ez-richtext-editview-tests.js, Tests/js/views/fields/assets/ez-selection-editview-tests.js, Tests/js/views/fields/ez-date-editview.html
JIRA: https://jira.ez.no/browse/EZP-25666
When switching language after creating a content, the field edit views are *rerendered* to take into account the new language but some field edit views do not support this *rerendering*. This patch fixes that by adding a lifecycle method to the base field edit view which is called after the rerendering of a field edit view when it is already in the active state. This gives an opportunity to correctly reinitialize any UI widget used for input. This is what is done for RichText, MapLocation, Selection (Country) and Date (for browsers not supporting date input). For Image, this is just about updating the template to take that case into account.
manual tests + unit test
=> EZP-25666: Can't edit some fields after switching language

Resources/public/js/views/fields/ez-binarybase-editview.js, Tests/js/views/fields/assets/ez-binaryfile-editview-tests.js, Tests/js/views/fields/assets/ez-image-editview-tests.js, Tests/js/views/fields/assets/ez-media-editview-tests.js
jira: https://jira.ez.no/browse/EZP-25641
Image, media file and binary file fields were disapearing when translating a content.
This behaviour came from the fact that currently if we are not updating the file attached to one of these fields, this means "no changes" and we were not returning a new fieldValue (so we are using the already filled one). This was done not to send the same file again and again.
But when translating a content the field value is not filled, but the file attached to the field is loaded (without activating the 'updated' flag). So when we are publishing the content with the new translation, those fields, were not saved.
To make it work with translation, we now check that the file is not updated **and that the language code of the current exist in the translations …
=> EZP-25641: Image, binary and media file missing when translating a conten

Resources/public/js/views/ez-languageselectionboxview.js, Tests/js/views/assets/ez-languageselectionboxview-tests.js
jira: https://jira.ez.no/browse/EZP-25332
The cancel handler of the language selection box was missing a 'prevent default' behaviour. the result was that it was changing the URI
=> EZP-25332: When closing language selection box it change URI

Resources/public/css/theme/views/subitem/list.css, Resources/public/js/views/services/plugins/ez-searchplugin.js, Resources/public/js/views/subitem/ez-subitemlistview.js, Resources/public/templates/subitem/list.hbt, Tests/js/views/services/plugins/assets/ez-searchplugin-tests.js, Tests/js/views/subitem/assets/ez-subitemlistview-tests.js
JIRA: https://jira.ez.no/browse/EZP-25425
After sending a Location to the trash, the parent Location HTTP cache is not correctly cleared, as a result the REST API reports a wrong number of child and this puts the subitem list view in an inconsistent state. The cache issue is being handled in [EZP-25003](https://jira.ez.no/browse/EZP-25003) but this patch makes the subitem list a bit more robust against such inconsistencies.
=> EZP-25425: Make SubitemListView more robust against inconsistencies

Resources/config/yui.yml, Resources/public/js/views/services/plugins/ez-discoverybarcontenttreeplugin.js, Tests/js/views/services/plugins/assets/ez-discoverybarcontenttreeplugin-tests.js
JIRA: https://jira.ez.no/browse/EZP-25404
This patch fixes the content tree which was broken when displaying the Trash. This was happening because the Content Tree was build upon the assumption that the main view would always provide a Location and its path which could be used to build the Content Tree. With the Trash, this assumption is not satisfied so basically this patch adds the handling of the case where we have no Location provided by the main view and in such case, we build the tree from the Location id provided in the root REST response.
manual test + unit tests (the coverage of the DiscoveryBar Content Tree plugin is now decent, around 85%).
=> Fix EZP-25404: Broken content tree when displaying the Trash

Resources/public/js/views/services/plugins/ez-publishdraftplugin.js, Tests/js/views/services/plugins/assets/ez-publishdraftplugin-tests.js
Link: https://jira.ez.no/browse/EZP-25426
When clicking multiple times on the publish button, multiple content could be created.
This patch disabled the button after the first click and reenables it after the loading.
Manual and unit test update
=> Fix EZP-25426: Mashing Publish creates more than one content

Resources/public/js/apps/plugins/ez-updatetreeplugin.js, Resources/public/js/views/services/ez-trashviewservice.js, Tests/js/apps/plugins/assets/ez-updatetreeplugin-tests.js, Tests/js/views/services/assets/ez-trashviewservice-tests.js
JIRA: https://jira.ez.no/browse/EZP-25716
This patch makes sure the tree is refreshed after restoring an item.
=> Fix EZP-25716: Content tree not updated after restoring an item from the trash

Resources/public/js/views/fields/ez-image-editview.js, Tests/js/views/fields/assets/ez-image-editview-tests.js
JIRA: https://jira.ez.no/browse/EZP-25208
This patch makes sure the Image edit view does not accept SVG document as [the Image field type does not support SVG](https://jira.ez.no/browse/EZP-25422).
=> Fix EZP-25208: Do not accept SVG document in Image edit view

Resources/public/js/views/fields/ez-date-editview.js, Tests/js/views/fields/assets/ez-date-editview-tests.js
JIRA: https://jira.ez.no/browse/EZP-25459
The Date edit view does not correctly handle a timestamp to zero. This patch makes sure, we correctly handle that case even if at the moment, it's impossible to get that because in such case case [the REST API gives a null fieldValue](https://jira.ez.no/browse/EZP-25719).
unit tests and manual tests
=> Fix EZP-25459: Date edit view considers 0 as empty

Resources/public/css/theme/modules/form.css, Resources/public/css/theme/views/subitem/list.css, Resources/public/css/views/subitem/list.css
jira: https://jira.ez.no/browse/EZP-25695
Some letters in capital could not be fully seen in edit inputs. The CSS changes to fix this were breaking some CSS for the priority inputs of the subitems list. That's why I had to make some changes in subitemlist stylesheet also.
- manually tested
=> FIx EZP-25695: Letters can not be fully seen in admin part input

Resources/public/css/theme/views/languageswitcher.css
jira: https://jira.ez.no/browse/EZP-25509
The language switcher expandable area was appearing under the action bar on the right. This was correct by giving the area a correct Z-index.
- manually tested
=> EZP-25509: The language switcher appears under the action bar

Resources/public/css/theme/views/actions/button.css
jira: https://jira.ez.no/browse/EZP-25577
Clicking on preview in the edit action bar isn't doing anything. Before cursor was a "hand" (meaning you should be able to click) when hovering "Preview", now it's the standard pointer to avoid confusion
- manually tested
=> EZP-25577: When clicking on the word preview I do not get preview

Controller/ContentTypeController.php, Tests/Controller/ContentTypeControllerTest.php
> Fixes https://jira.ez.no/browse/EZP-25672
Ensure that the language we use exists in the content type.
Migrated from https://github.com/ezsystems/PlatformUIBundle/pull/550 on master.
=> Fix EZP-25672: Content Type controller should use Languages more wisely

Resources/public/js/views/ez-universaldiscoveryview.js, Resources/public/js/views/services/plugins/ez-contenttreeplugin.js, Resources/public/js/views/services/plugins/ez-discoverybarcontenttreeplugin.js, Resources/public/js/views/services/plugins/ez-universaldiscoverycontenttreeplugin.js, Resources/public/js/views/universaldiscovery/ez-universaldiscoverybrowseview.js, Resources/public/js/views/universaldiscovery/ez-universaldiscoverymethodbaseview.js, Tests/js/views/assets/ez-universaldiscoveryview-tests.js, Tests/js/views/services/plugins/assets/ez-universaldiscoverycontenttreeplugin-tests.js, Tests/js/views/universaldiscovery/assets/ez-universaldiscoverybrowseview-tests.js
jira: https://jira.ez.no/browse/EZP-24917
The goal here is to be able to start the tree of the Universal Discovery Widget's browseview at a given location. To do that you must give to the config of the 'contentDiscover' event, a parameter called 'startingLocationId' containing a locationId.
Example: 
```
this.fire('contentDiscover', {
config: {
title: "title",
startingLocationId : '/api/ezp/v2/content/locations/1/2/54/55/56/57'
contentDiscoveredHandler: function()),
cancelDiscoverHandler: otherFunction()),  
},
});
```
Unit and manual tests
=> EZP:24917 Start UDW at a given location

Resources/public/js/models/ez-contentmodel.js, Tests/js/models/assets/ez-contentmodel-tests.js
Link: https://jira.ez.no/browse/EZP-25804
When updating the main location id of a content, the view was not refreshed.
This was happening because we would not update (or reload) the content (which stores the mainLocationId information), but only the locations. This patch updates the content with the content in order to refresh the main location id selector.
Manual and unit tests.
=> Fix EZP-25804: Updating main location doesn't refresh the view

Tests/js/views/assets/ez-confirmboxview-tests.js
I'm not creating a jira issue for this, let me know if you need it though. 
Looks we had a infiltrate in our Tests. :)
This just remove a call to console.log
ping @dpobel @yannickroger
=> Removed console.log call in the confirmboxview test

Resources/config/yui.yml, Resources/public/js/alloyeditor/buttons/embed.js, Resources/public/js/alloyeditor/buttons/embed.jsx, Resources/public/js/alloyeditor/buttons/image.js, Resources/public/js/alloyeditor/buttons/image.jsx, Resources/public/js/alloyeditor/plugins/addcontent.js, Resources/public/js/alloyeditor/plugins/embed.js, Resources/public/js/alloyeditor/toolbars/ezadd.js, Resources/public/js/alloyeditor/toolbars/ezadd.jsx, Resources/public/js/views/fields/ez-richtext-editview.js, Tests/js/alloyeditor/plugins/assets/ez-alloyeditor-plugin-addcontent-tests.js, Tests/js/alloyeditor/plugins/assets/ez-alloyeditor-plugin-embed-tests.js, Tests/js/alloyeditor/plugins/ez-alloyeditor-plugin-embed.html, Tests/js/alloyeditor/toolbars/assets/ez-alloyeditor-toolbar-ezadd-tests.jsx, Tests/js/alloyeditor/toolbars/ez-alloyeditor-toolbar-ezadd.html, Tests/js/views/fields/assets/ez-richtext-editview-tests.js
JIRA: https://jira.ez.no/browse/EZP-25705
The JIRA issue is actually about two issues:
1. it's not possible to add anything between 2 embeds
2. it's not possible to complete an unordered list if you put an embed in the last list item.
This patch only fixes the first issue for now and this can be seen as 3 steps:
1. make sure the *add* toolbar (the plus button on the left) is available and correctly positioned when an embed receives the focus. This was not the case previously because an embed is represented in the editor by a CKEditor widget and this widget is not editable (`contenteditable` set to false) so the default AlloyEditor `add` toolbar assumes we can't add anything. To avoid that, we now use an `ezadd` toolbar which basically extend the default one to not check the content …
=> Fix EZP-25705: Can't add anything between 2 embeds

Features/Standard/SubitemGrid.feature, Resources/public/js/models/ez-contenttypemodel.js, Resources/public/js/views/ez-subitemboxview.js, Resources/public/js/views/services/ez-locationviewviewservice.js, Tests/js/models/assets/ez-contenttypemodel-tests.js, Tests/js/views/assets/ez-subitemboxview-tests.js, Tests/js/views/services/assets/ez-locationviewviewservice-tests.js
JIRA: https://jira.ez.no/browse/EZP-25794
This patch changes the subitem so that the subitem grid view is displayed by default when the Content Type of the Content item being viewed belongs to the *Media* Content Type Group (phew :)).
Note: the *Media* Content Type Group id is hardcoded in the Subitem Box view (the view responsible for allowing the user to change the type of subitem view to display and to decide which one to display by default), I assume it's safe to do that this way since it's something that can not really change. Also, it's perfectly possible to write a plugin for the Subitem Box view to implement additional rules if needed.
=> EZP-25794: Display the subitem grid view by default when in media

Resources/public/js/views/subitem/ez-asynchronoussubitemview.js, Tests/js/views/subitem/assets/ez-asynchronoussubitemview-tests.js
Additional patch needed for https://jira.ez.no/browse/EZP-25794 (and https://jira.ez.no/browse/EZP-25662)
This patch makes sure we don't try to search for the subitems on a Location that does not have any. This is a small performance improvement but this also fixes a JavaScript error issued because we were trying to disable the *Load More* button which is not generated in that case.
unit test + manual test
=> EZP-25794: Avoid searching for subitems when there's none

DependencyInjection/Configuration.php, DependencyInjection/Configuration/PlatformUIMapper.php, Resources/config/default_settings.yml, Resources/views/PlatformUI/shell.html.twig, Tests/DependencyInjection/EzPlatformUIExtensionTest.php
It should be possible to add custom JavaScript files to Platform UI, for example various libraries like jQuery and so on.
One use case is developing custom field edit interfaces, for example for `eztags` field type.
=> EZP-25581: Add possiblity to include custom JS files in Platform UI

Resources/public/js/models/extensions/ez-contentinfo-attributes.js, Resources/public/js/models/ez-contentinfomodel.js, Resources/public/js/views/dashboard/ez-dashboardblockallcontentview.js, Resources/public/templates/dashboard/allcontent.hbt, Tests/js/models/assets/ez-contentinfomodel-tests.js, Tests/js/views/dashboard/assets/ez-dashboardblockallcontentview-tests.js
Now that [EZP-25842](https://jira.ez.no/browse/EZP-25842) / https://github.com/ezsystems/ezpublish-kernel/pull/1678, it is not necessary to load the *full* Content item to render the *all content* draft, the ContentInfo contains everything we need.
=> Remove the loading of the Content to build the all content block

Resources/public/js/views/dashboard/ez-dashboardblockallcontentview.js, Resources/public/js/views/services/plugins/ez-searchplugin.js, Tests/js/views/dashboard/assets/ez-dashboardblockallcontentview-tests.js, Tests/js/views/services/plugins/assets/ez-searchplugin-tests.js
Now that [EZP-24315](https://jira.ez.no/browse/EZP-24315) / https://github.com/ezsystems/ezpublish-kernel/pull/1677 is implemented, this patch makes sure the Content items displayed in the *All Content* Dashboard block are the last modified ones.
manual test + unit test
=> Sort the Content items by modified date in All Content block

Resources/public/js/views/services/ez-roleserversideviewservice.js, Tests/js/views/services/assets/ez-roleserversideviewservice-tests.js
Link: https://jira.ez.no/browse/EZP-25817
The platform UI used to send invalid subtree limitation that were missing a `/` at the end. That is what this patch is fixing. It can easily be reproduced with https://github.com/ezsystems/ezpublish-kernel/pull/1671 applied (as the REST API will send an error).
=> Fix EZP-25817: Invalid subtree path when assigning role with subtree limitation

Resources/public/js/apps/plugins/ez-updatetreeplugin.js, Resources/public/js/views/services/plugins/ez-locationswapplugin.js, Tests/js/apps/plugins/assets/ez-updatetreeplugin-tests.js, Tests/js/views/services/plugins/assets/ez-locationswapplugin-tests.js
JIRA: https://jira.ez.no/browse/EZP-25921
This was forgotten in #592 
=> Fix EZP-25921: refresh the Content Tree after swapping Location

Resources/public/css/theme/views/dashboard/asynchronous.css, Resources/public/js/views/dashboard/ez-dashboardblockasynchronousview.js, Resources/public/templates/dashboard/mycontent.hbt, Resources/public/templates/dashboard/mydrafts.hbt, Tests/js/views/dashboard/assets/ez-dashboardblockasynchronousview-tests.js
JIRA: https://jira.ez.no/browse/EZP-25885
This patch makes sure we don't display an empty table in the My Drafts dashboard block when the user has no draft. Actually, it introduces a `loading` flag in the Asynchronous Dashboard Block *abstract* view so that we can differentiate the case where we are waiting for the drafts to be loaded from the case where there's no draft.
Also while working on that issue, I've realized the My Content block has exactly the same problem, so this patch also fixes it the same way:
=> EZP-25885: My Drafts block displays an empty table if there's no drafts

Resources/config/yui.yml, Resources/public/js/alloyeditor/plugins/addcontent.js, Resources/public/js/alloyeditor/plugins/embed.js, Resources/public/js/alloyeditor/plugins/focusblock.js, Resources/public/js/alloyeditor/toolbars/ezadd.js, Resources/public/js/alloyeditor/toolbars/ezadd.jsx, Tests/js/alloyeditor/buttons/ez-alloyeditor-button-embed.html, Tests/js/alloyeditor/buttons/ez-alloyeditor-button-embedhref.html, Tests/js/alloyeditor/buttons/ez-alloyeditor-button-image.html, Tests/js/alloyeditor/buttons/ez-alloyeditor-button-imagehref.html, Tests/js/alloyeditor/buttons/ez-alloyeditor-button-imagevariation.html, Tests/js/alloyeditor/plugins/assets/ez-alloyeditor-plugin-addcontent-tests.js, Tests/js/alloyeditor/plugins/assets/ez-alloyeditor-plugin-focusblock-tests.js, Tests/js/alloyeditor/plugins/ez-alloyeditor-plugin-addcontent.html, Tests/js/alloyeditor/plugins/ez-alloyeditor-plugin-embed.html, Tests/js/alloyeditor/plugins/ez-alloyeditor-plugin-focusblock.html, Tests/js/alloyeditor/plugins/ez-alloyeditor-plugin-removeblock.html
JIRA: https://jira.ez.no/browse/EZP-25705
Make sure it's impossible to add an embed inside a list item.
=> EZP-25705: Prevent embed elements from being added in a list item

Resources/config/yui.yml, Resources/public/css/theme/modules/loadmorepagination.css, Resources/public/js/apps/plugins/ez-updatetreeplugin.js, Resources/public/js/extensions/ez-loadmorepagination.js, Resources/public/js/models/ez-locationmodel.js, Resources/public/js/views/services/ez-locationviewviewservice.js, Resources/public/js/views/services/plugins/ez-contenttreeplugin.js, Resources/public/js/views/services/plugins/ez-discoverybarcontenttreeplugin.js, Resources/public/js/views/services/plugins/ez-searchplugin.js, Resources/public/js/views/services/plugins/ez-universaldiscoverycontenttreeplugin.js, Resources/public/js/views/subitem/ez-asynchronoussubitemview.js, Resources/public/js/views/subitem/ez-subitemlistmoreview.js, Tests/js/apps/plugins/assets/ez-updatetreeplugin-tests.js, Tests/js/extensions/assets/ez-loadmorepagination-tests.js, Tests/js/models/assets/ez-locationmodel-tests.js, Tests/js/views/services/assets/ez-locationviewviewservice-tests.js, Tests/js/views/services/plugins/assets/ez-contenttreeplugin-tests.js, Tests/js/views/services/plugins/assets/ez-discoverybarcontenttreeplugin-tests.js, Tests/js/views/services/plugins/assets/ez-searchplugin-tests.js, Tests/js/views/services/plugins/assets/ez-universaldiscoverycontenttreeplugin-tests.js, Tests/js/views/services/plugins/ez-discoverybarcontenttreeplugin.html, Tests/js/views/services/plugins/ez-universaldiscoverycontenttreeplugin.html, Tests/js/views/subitem/assets/ez-asynchronoussubitemview-tests.js, Tests/js/views/subitem/assets/ez-subitemgridview-tests.js, Tests/js/views/subitem/assets/ez-subitemlistmoreview-tests.js
JIRA: https://jira.ez.no/browse/EZP-24998
This patch makes sure the Content Tree and the Subitem views receives the Location lists sorted as indicated by the parent Location `sortOrder` and `sortField` property.
Screencast:
[![](https://img.youtube.com/vi/tDhFK7X5P5U/0.jpg)](http://www.youtube.com/watch?v=tDhFK7X5P5U "Click to play on Youtube.com")
5 sort clauses seem to not be fully implemented server side (see also https://github.com/ezsystems/PlatformUIBundle/pull/622/files#diff-3d4c2abab2b4c380f20d2e09ec804e3cR367):
* (Location)Priority https://jira.ez.no/browse/EZP-25907
* (Location)Path https://jira.ez.no/browse/EZP-25911
* (Location)Depth https://jira.ez.no/browse/EZP-25910 (ok this one is a bit stupid in that case, but can still be set the sort field for a Location)
* Content Type …
=> EZP-24998: Order of the elements when doing a search is wrong (and random)

Resources/public/js/views/fields/richtext/ez-richtext-resolveembed.js, Tests/js/views/fields/richtext/assets/ez-richtext-resolveembed-tests.js, Tests/js/views/fields/richtext/assets/ez-richtext-resolveimage-tests.js, Tests/js/views/fields/richtext/ez-richtext-resolveembed.html, Tests/js/views/fields/richtext/ez-richtext-resolveimage.html
JIRA: https://jira.ez.no/browse/EZP-25941
Avoid doing a search request to resolve the *embed* and *embed image* when there's none.
Replaces a part of #623 
=> Fix EZP-25941: Avoid empty search when there's no embed/image

Resources/public/css/views/universaldiscovery.css
JIRA: https://jira.ez.no/browse/EZP-24941
A part of the UDW can appear if the user decreases the height of the viewport. This is happening because of the way we are hiding the UDW (with the sliding transition). This patch just makes sure the UDW is really invisible for the user.
manual tests
=> EZP-24941: UDW becomes visible when decreasing the height of the viewport

Resources/public/js/models/ez-contentmodel.js, Resources/public/js/models/ez-versionmodel.js, Resources/public/js/views/services/plugins/ez-discarddraftplugin.js, Tests/js/models/assets/ez-contentmodel-tests.js, Tests/js/models/assets/ez-versionmodel-tests.js, Tests/js/views/services/plugins/assets/ez-discarddraftplugin-tests.js
JIRA: https://jira.ez.no/browse/EZP-25148
When a Content item only has a DRAFT version (right after creating a Content item and clicking on *Save* for instance), this version (and the corresponding Content item) stays in the repository even if the user clicks on *Discard draft*. This patch makes sure in such case we remove the Content item because removing the version alone is not allowed since it's the last version of the Content item.
=> Fix EZP-25148: Stale draft after canceling a content creation

Resources/public/js/views/services/plugins/ez-searchplugin.js, Tests/js/views/services/plugins/assets/ez-searchplugin-tests.js
JIRA: https://jira.ez.no/browse/EZP-25961
Replaces the second part of #623
When loading the Content items after a Location search, the `ContentIdCriterion` is starting with a comma which produces a fatal with ProgreSQL. This patch makes sure we avoid this extra comma.
=> Fix EZP-25961: Extra comma when loading Content after a Location search

Resources/public/js/apps/ez-platformuiapp.js, Tests/js/apps/assets/ez-platformuiapp-tests.js
JIRA: https://jira.ez.no/browse/EZP-25980
If you send to trash a container Content item without any sub-items, you'll get a JavaScript error while you are redirected to the parent Location. This is happening because the subitem views subscribe to the `sortFieldChange` and `sortOrderChange` events and the corresponding attribute are updated in the redirection process.
This patch makes sure the active state of the view is updated earlier so that before loading the parent Location, the views become inactive and then refresh is ignored.
=> Fix EZP-25980: Trashing a container Content item without sub-items raises a JavaScript error

Resources/config/yui.yml, Resources/public/js/apps/ez-platformuiapp.js, Resources/public/js/apps/plugins/ez-universaldiscoveryplugin.js, Resources/public/js/views/ez-contenteditview.js, Tests/js/apps/assets/ez-platformuiapp-tests.js, Tests/js/apps/ez-platformuiapp.html, Tests/js/apps/plugins/assets/ez-universaldiscoveryplugin-tests.js, Tests/js/views/assets/ez-contenteditview-tests.js
jira : https://jira.ez.no/browse/EZP-25874 
The fix here is that  when the UDW is launched, pressing esc in edit mode or pressing the back button of the browser don't change the view which is "behind" the UDW.
The hash is also keeped and the  browser history as well.
=> EZP-25874 ESC and back while discovering exits content edit

Resources/public/js/alloyeditor/buttons/embed.js, Resources/public/js/alloyeditor/buttons/embed.jsx, Resources/public/js/alloyeditor/buttons/embedhref.js, Resources/public/js/alloyeditor/buttons/embedhref.jsx, Resources/public/js/alloyeditor/buttons/image.js, Resources/public/js/alloyeditor/buttons/image.jsx, Resources/public/js/alloyeditor/buttons/imagehref.js, Resources/public/js/alloyeditor/buttons/imagehref.jsx, Resources/public/js/alloyeditor/buttons/mixins/embeddiscovercontent.js, Resources/public/js/extensions/ez-processable.js, Resources/public/js/views/fields/richtext/ez-richtext-resolveembed.js, Resources/public/js/views/fields/richtext/ez-richtext-resolveimage.js, Tests/js/alloyeditor/buttons/assets/ez-alloyeditor-button-embed-tests.jsx, Tests/js/alloyeditor/buttons/assets/ez-alloyeditor-button-embedhref-tests.jsx, Tests/js/alloyeditor/buttons/assets/ez-alloyeditor-button-image-tests.jsx, Tests/js/alloyeditor/buttons/assets/ez-alloyeditor-button-imagehref-tests.jsx, Tests/js/extensions/assets/ez-processable-tests.js, Tests/js/views/fields/assets/ez-richtext-view-tests.js, Tests/js/views/fields/richtext/assets/ez-richtext-resolveembed-tests.js, Tests/js/views/fields/richtext/assets/ez-richtext-resolveimage-tests.js, Tests/js/views/fields/richtext/ez-richtext-resolveembed.html, Tests/js/views/fields/richtext/ez-richtext-resolveimage.html
JIRA: https://jira.ez.no/browse/EZP-26011
Requires https://github.com/ezsystems/content-on-the-fly-prototype-bundle/pull/15
To render the embed elements and the images in the RichText editor a search is done to load the corresponding Content(Info). Right after creating a Content, the search index might not be up to date yet, as a result the embed or the image added based on a Content that was just created with the Content on the Fly feature can not be done.
To avoid that, this patch changes the way the embed/image tag is rendered right after the usage of the Universal Discovery Widget to use the selection provided by the UDW instead of searching for the Content(Info).
=> EZP-26011: Content on the Fly embeds unreliable with the Solr Bundle

Resources/public/js/views/ez-usermenuitemfireeventview.js, Tests/js/views/assets/ez-usermenuitemfireeventview-tests.js
As discussed on PR #653 the event name should be exposed in order to the improve element searching in behat tests.
jira: https://jira.ez.no/browse/EZP-26121
=> EZP-2612: Expose the event name in the markup generated by UserMenuItemFireEventView

Resources/public/js/views/navigation/ez-navigationitemview.js, Tests/js/views/navigation/assets/ez-navigationitemview-tests.js
As discussed on PR #653 the navigation items identifier should be exposed in order to the improve element searching in behat tests.
jira: https://jira.ez.no/browse/EZP-26120
=> EZP-26120: Expose the navigation items identifier in the navigation hub

Resources/public/js/alloyeditor/plugins/yui3.js, Tests/js/alloyeditor/plugins/assets/ez-alloyeditor-plugin-yui3-tests.js
JIRA: https://jira.ez.no/browse/EZP-26145
In Online Editor, some operations can not be undone, especially the removal of some text in the middle of a paragraph. This is happening because while doing that, we are also cleaning up some auto-generated ids and this seems to confuse the *undo manager*. To avoid that, before cleaning up the ids, the undo manager is locked so that the cleanup is not part of the undo stack.
=> EZP-26145: Unable to undo in the RichText editor

Resources/public/js/views/fields/ez-richtext-editview.js, Tests/js/views/fields/assets/ez-richtext-editview-tests.js
Link: https://jira.ez.no/browse/EZP-26117
When editing a content with a mandatory richtext field (such as article). If only an single embed is present, the field is still considered empty.
=> Fix EZP-26117: Required richtext not validated as filled with single embed

Resources/public/js/views/actions/ez-translateactionview.js, Resources/public/js/views/confirmbox/ez-draftconflictview.js, Resources/public/js/views/dashboard/ez-dashboardblockasynchronousview.js, Resources/public/js/views/ez-fieldeditview.js, Resources/public/js/views/ez-view.js, Resources/public/js/views/fields/ez-binarybase-editview.js, Resources/public/js/views/fields/ez-image-editview.js, Resources/public/js/views/fields/ez-media-editview.js, Resources/public/js/views/serverside/ez-contenttypeeditserversideview.js, Resources/public/js/views/serverside/ez-roleserversideview.js, Resources/public/js/views/serverside/ez-sectionserversideview.js, Resources/public/js/views/tabs/ez-locationviewdetailstabview.js, Resources/public/js/views/tabs/ez-locationviewlocationstabview.js, Resources/public/js/views/tabs/ez-locationviewversionstabview.js, Resources/public/js/views/universaldiscovery/ez-universaldiscoverysearchview.js, Tests/js/views/assets/ez-view-tests.js, Tests/js/views/ez-view.html
Link: https://jira.ez.no/browse/EZP-26236
This is a very technical YUI related bug.
When the container is created in the initializer, events added later on (like the initializer of a view inheriting from the first one) are not attached to the view.
This patch makes sure to attach the events to the DOM if a container already exists.
Unit tests and basic sanity.
=> Fix EZP-26236: Events are lost if container is created in initializer

Features/Context/PlatformUI.php, Features/Context/SubContext/Authentication.php
On slow machine / when debug is enabled, and on empty cache.
Also cleanup iShouldBeLoggedIn to not do nested spin after #520 _(findWithWait uses spin underneath, having two nested does not increase the timeout)_.
=> [Behat] Increase spin time to try to avoid failure on first step

Resources/public/js/apps/ez-platformuiapp.js, Resources/public/js/apps/plugins/ez-notificationhubplugin.js, Tests/js/apps/assets/ez-platformuiapp-tests.js, Tests/js/apps/plugins/assets/ez-notificationhubplugin-tests.js
JIRA: https://jira.ez.no/browse/EZP-26179
This patch improves PlatformUI to better check the user session and react to an expired session.
The app change makes sure we always check the user session on "page loading", this adds a request on each page but it's the only way to have the status of the session.
In addition to that, a check is added to the error notification to verify if the error happens because of an expired session. This is a cheap way of doing that will only be in 1.4 and 1.5. In master (1.6), this will be made a bit differently with a dedicated error API to decouple the UI notification from the actual error handling.
=> EZP-26179: UI Stability issues due to session loss

Controller/ExceptionController.php
> Fixes [EZP-26083](http://jira.ez.no/browse/EZP-26083)
From Symfony 2.8.0, TwigBundle's `ExceptionController::findTemplate()` method doesn't return a `TemplateReferenceInterface` anymore, but a string.
This changes PlatformUIBundle's custom controller to handle both object and string templates.
=> Fix EZP-26083: handle change of behaviour in Twig's ExceptionController

Resources/public/js/models/ez-contentmodel.js, Tests/js/models/assets/ez-contentmodel-tests.js, Tests/js/views/services/plugins/assets/ez-objectrelationloadplugin-tests.js
Link: https://jira.ez.no/browse/EZP-26357
In the field(edit)view of relation list we would load every relation attached to the object instead of the one mentioned in the field.
For the relation field, we would load the relation from the content relations instead of the field relation.
Unfortunately, the content ids stored in the field are API ids and not REST ids, this should be fixed in [EZP-23000](https://jira.ez.no/browse/EZP-23000) but for 1.5 we need to generate the REST id ourselves.
=> Fix EZP-26357: RelationList field displays related objects for all translations

Resources/public/js/views/fields/ez-richtext-editview.js, Tests/js/views/fields/assets/ez-richtext-editview-tests.js
JIRA: https://jira.ez.no/browse/EZP-26135
This is yet again a problem about XML vs. HTML. Basically in PlatformUI, we use the `xhtml5edit` representation of the RichText fields. This `xhtml5edit` is an XML dialect closed to XHTML and then HTML, but some details confuse browser parsers mainly the auto-closed tag like `<br/>` and `<div/>` (for embeds). So this patch introduces a better transformation from `xhtml5edit` to HTML.
=> EZP-26135: Line breaks added in richtext editor when editing content twice

Gruntfile.js, Resources/config/yui.yml, Resources/public/js/models/structs/ez-fielderrordetails.js, Resources/public/js/views/ez-contenteditformview.js, Resources/public/js/views/ez-contenteditview.js, Resources/public/js/views/ez-fieldeditview.js, Resources/public/js/views/services/plugins/extensions/ez-draftserversidevalidation.js, Resources/public/js/views/services/plugins/ez-publishdraftplugin.js, Resources/public/js/views/services/plugins/ez-savedraftplugin.js, Tests/js/extensions/assets/ez-draftserversidevalidation-tests.js, Tests/js/models/structs/assets/ez-fielderrordetails-tests.js, Tests/js/models/structs/ez-fielderrordetails.html, Tests/js/views/assets/ez-contenteditformview-tests.js, Tests/js/views/assets/ez-contenteditview-tests.js, Tests/js/views/assets/ez-fieldeditview-tests.js, Tests/js/views/services/plugins/assets/ez-publishdraftplugin-tests.js, Tests/js/views/services/plugins/assets/ez-savedraftplugin-tests.js, Tests/js/views/services/plugins/ez-publishdraftplugin.html, Tests/js/views/services/plugins/ez-savedraftplugin.html
jira : https://jira.ez.no/browse/EZP-26240
The goal here was to be able to give the field edit views the error messages coming from the server side. Currently to see those "server side error messages" you must overpass the application validation so you have to disable it to see the feature.
https://youtu.be/8sVKlcpDBcY
=> EZP-26240: Update editing UI with server side validation

Resources/public/js/models/ez-contentmodel.js, Tests/js/models/assets/ez-contentmodel-tests.js, Tests/js/views/services/plugins/assets/ez-objectrelationloadplugin-tests.js
Link: https://jira.ez.no/browse/EZP-23000
In https://github.com/ezsystems/ezpublish-kernel/pull/1787 REST ids have been added to relation fields. This PR uses this new functionality to remove a workaround introduced in 1.5.
Manual and unit tests update.
=> EZP-23000: Object relation(s) field value should provides REST id(s)

Resources/public/js/views/universaldiscovery/ez-universaldiscoverysearchview.js, Resources/public/templates/universaldiscovery/search.hbt, Tests/js/views/universaldiscovery/assets/ez-universaldiscoverysearchview-tests.js
JIRA: https://jira.ez.no/browse/EZP-26336
This patch fixes an issue in the search UDW method where the first search never returns anything even if the REST API response contains some results. Then following searches have a wrong result count. This is happening because the rendering of the search result is triggered by the change of the search result list attribute but the result count attribute is updated afterwards.
manual test + unit tests
=> Fix EZP-26336: Inconsistent behaviour of the search UDW method

Resources/public/js/alloyeditor/plugins/embed.js, Tests/js/alloyeditor/plugins/assets/ez-alloyeditor-plugin-embed-tests.js
JIRA: https://jira.ez.no/browse/EZP-26241
This is happening only in Firefox and the JavaScript error is due to the fact that the editor and the widget do not have the focus yet. So this patch makes sure the editor and widget have the focus.
Unit tests + manual tests in Firefox and Chrome
=> Fix EZP-26241: JS error when giving the focus to the editor by clicking on an embed

Resources/public/templates/subitem/griditem.hbt
Link: https://jira.ez.no/browse/EZP-26036
Removed static Icon as it is not needed.
Basic sanity on grid
=> Fix EZP-26036: Double content type icon in the grid view

Resources/public/js/views/ez-universaldiscoveryview.js, Resources/public/js/views/universaldiscovery/ez-universaldiscoverysearchview.js, Tests/js/views/universaldiscovery/assets/ez-universaldiscoverysearchview-tests.js
JIRA: https://jira.ez.no/browse/EZP-26433
This is a regression caused by https://github.com/ezsystems/PlatformUIBundle/pull/686. This is happening because in some cases the view attributes are reset, this process includes the `multiple` attribute which then contains its default value (`false`) instead of the configured value. By fixing that, I also figured out that the Content item not always available (while it should if we want to display an image field when there's one). This is also fixed by forcing  `loadContent` to be true. (This parameter is now useless, it'll be deprecated shortly in https://jira.ez.no/browse/EZP-26434).
=> Fix EZP-26433: Impossible to select a Content in the UDW search method if the UDW is configured to allow a multiple selection

Resources/public/js/alloyeditor/plugins/removeblock.js, Tests/js/alloyeditor/plugins/assets/ez-alloyeditor-plugin-removeblock-tests.js, Tests/js/alloyeditor/plugins/ez-alloyeditor-plugin-removeblock.html
JIRA: https://jira.ez.no/browse/EZP-26016
This patch just makes sure we don't try to give the focus to an *internal* element generated by the widget CKEditor plugin which results in a JavaScript error because this element is later removed from the document.
=> Fix EZP-26016: JavaScript error when removing an embed if it's the last element in the editor

Resources/public/js/models/ez-locationmodel.js, Tests/js/models/assets/ez-locationmodel-tests.js
Link: https://jira.ez.no/browse/EZP-26246
When hiding/revealing a location, the `hidden` was updated in the PlatformUI but not the `invisible`. In order not to duplicate the business logic (that is more complicated for `invisible`) we just update the PlatformUI in memory `location` with the result of the REST response.
Manual test and updated unit tests.
=> Fix EZP-26246: Wrong visibility status after refresh

Resources/public/js/views/ez-contenteditview.js, Resources/public/js/views/services/ez-contenteditviewservice.js, Resources/public/templates/contentedit.hbt, Tests/js/views/assets/ez-contenteditview-tests.js, Tests/js/views/services/assets/ez-contenteditviewservice-tests.js
jira : https://jira.ez.no/browse/EZP-26318
Fixed a bug that when we delete a user that had created some contents, we couldn't edit those content anymore. That was because owner of the content wasn't found and was needed in the content edit view.
=> EZP-26318: Deleting user breaks content created by that user

Resources/public/js/alloyeditor/buttons/mixins/embedalign.js, Resources/public/js/alloyeditor/buttons/mixins/embedalign.jsx, Resources/public/js/alloyeditor/plugins/embed.js, Tests/js/alloyeditor/plugins/assets/ez-alloyeditor-plugin-embed-tests.js
JIRA: https://jira.ez.no/browse/EZP-26020
After aligning an embed or an image, the (+) button disappears. This patch fixes that by making sure the `editorInteraction` event is fired when changing the alignment of a widget so that AlloyEditor knows on which element the user was acting and then can react accordingly.
=> Fix EZP-26020: (+) sign disappears after aligning an embed/image

Resources/public/js/views/fields/ez-richtext-editview.js, Tests/js/views/fields/assets/ez-richtext-editview-tests.js
JIRA: https://jira.ez.no/browse/EZP-26355
When pasting an URL in Online Editor, the editor has a weird behavior. This is happening because AlloyEditor dev recently added a plugin (`ae_embed`) that implements [the oEmbed API](http://oembed.com/) so when pasting an URL the editor tries to create a widget which does not play well with our own customizations. So for now the solution is to disable `ae_embed`. (We'll maybe re-introduce that when we have custom tags)
=> Fix EZP-26355: Cannot paste an URL in a RichText field

Resources/config/yui.yml, Resources/public/js/alloyeditor/processors/emptyembed.js, Resources/public/js/alloyeditor/processors/removeanchors.js, Resources/public/js/views/fields/ez-richtext-editview.js, Tests/js/alloyeditor/processors/assets/ez-editorcontentprocessorremoveanchors-tests.js, Tests/js/alloyeditor/processors/ez-editorcontentprocessorremoveanchors.html, Tests/js/views/fields/assets/ez-richtext-editview-tests.js
JIRA: https://jira.ez.no/browse/EZP-26384
This patch makes sure the anchors (`a` element without `href` attribute) are removed from the RichText field value since we don't support anchors (yet).
manual tests + unit tests.
=> Fix EZP-26384: Fail to save a Content item with a RichText field containing an anchor

Resources/public/js/views/fields/ez-richtext-editview.js
JIRA: https://jira.ez.no/browse/EZP-26492
That's a regression from https://github.com/ezsystems/PlatformUIBundle/pull/683 because in Edge (happens also in IE11), `document.implementation.createHTMLDocument` expects a parameter while in others browser, this parameter is not mandatory.
The fix just removes this call as it's not necessary since `document` is already an HTML document.
=> Fix EZP-26492: Impossible to edit a Content with a RichText field in Edge

Resources/public/templates/fields/view/media.hbt
Link: https://jira.ez.no/browse/EZP-26486
Firefox doesn't update the video if the link doesn't change. So we are adding the id of the video in order to force the refresh.
Example of generated URL: `http://ezp.local/content/download/84/322?id=video/aa5ef523f7825634e10dbacb065c1507.webm`
=> Fix EZP-26486: In Firefox, media view doesn't update the video

Resources/config/yui.yml, Resources/public/js/alloyeditor/plugins/paste.js, Resources/public/js/views/fields/ez-richtext-editview.js, Tests/js/alloyeditor/plugins/assets/ez-alloyeditor-plugin-paste-tests.js, Tests/js/alloyeditor/plugins/ez-alloyeditor-plugin-paste.html, Tests/js/views/fields/assets/ez-richtext-editview-tests.js
JIRA: https://jira.ez.no/browse/EZP-26390
Before this patch, the paste behavior was not configured so the AlloyEditor/CKEditor was applying [the `semantic-content` filter](http://docs.ckeditor.com/#!/guide/dev_advanced_content_filter-section-filtering-pasted-and-dropped-content) in Webkit/Blink based browser when pasting unless the code was detected as coming from the Word.
This patch configures and tweaks the paste behaviour:
* it adds a custom paste filter to match what we actually support server side and in the RichText editor (so this filter is also applied with others browsers)
* it applies the previous paste filter even if the pasted code is detected as coming from Word (the `pastefromword` plugin keeps a lots of div, that's exactly the customer issue)
* it adds an additional …
=> EZP-26390: Fail to save Content item after pasting

Tests/js/alloyeditor/plugins/assets/ez-alloyeditor-plugin-embed-tests.js
The upgrade to AlloyEditor 1.2.4 broke the unit tests (caused by a change in the "placeholder" plugin). This patch removes the failing tests as the place where the HTML code is inserted is handled by another plugin, instead we just make sure the insertion of a new embed calls the API exposed by this plugin.
TravisCI seems to be happy :champagne:
=> Fixed embed unit tests to not fail with AlloyEditor 1.2.4

Resources/public/js/apps/plugins/ez-registerlanguagehelpersplugin.js, Resources/public/templates/contentedit.hbt, Resources/public/templates/fields/edit/binaryfile.hbt, Resources/public/templates/fields/edit/media.hbt, Resources/public/templates/fields/view/binaryfile.hbt, Resources/public/templates/fields/view/media.hbt, Resources/public/templates/loginform.hbt, Resources/public/templates/searchlistview.hbt, Resources/public/templates/subitem/grid.hbt, Resources/public/templates/subitem/listmore.hbt, Resources/public/templates/universaldiscovery/confirmedlist.hbt, Resources/public/templates/universaldiscovery/search.hbt, Resources/translations/contentedit.en.xlf, Resources/translations/fieldedit.en.xlf, Resources/translations/fieldview.en.xlf, Resources/translations/login.en.xlf, Resources/translations/search.en.xlf, Resources/translations/subitem.en.xlf, Resources/translations/universaldiscovery.en.xlf, Tests/Translation/HandleBarsExtractorTest.php, Tests/js/apps/plugins/assets/ez-registerlanguagehelpersplugin-tests.js, Translation/HandleBarsExtractor.php
JIRA: https://jira.ez.no/browse/EZP-26431
This patch brings the ability to translate strings containing some parameters. The `translate` Handlebars helper now accepts named parameters that can be used in the strings. The Handlebars dumper has been changed to correctly handle those extra parameters and the corresponding strings have been added to the translation files.
=> EZP-26431: Allow strings with parameters to be translated

Resources/config/yui.yml, Resources/public/js/views/ez-barview.js, Tests/js/views/assets/ez-barview-tests.js, Tests/js/views/ez-barview.html
Link: https://jira.ez.no/browse/EZP-26469
Scrolling was not taken into account in the calculation to hide items from the left/right menus.
=> Fix EZP-26469: Items hidden from barview after scrolling

Resources/public/js/external/ez-translator.js, Resources/public/js/views/ez-actionbarview.js, Resources/public/js/views/ez-discoverybarview.js, Resources/public/js/views/ez-navigationhubview.js, Resources/public/js/views/services/ez-navigationhubviewservice.js, Tests/js/assets/ez-translator.js, Tests/js/external/assets/ez-translator-tests.js, Tests/js/external/assets/translator.js, Tests/js/views/assets/ez-discoverybarview-tests.js, Tests/js/views/services/assets/ez-navigationhubviewservice-tests.js
Link: https://jira.ez.no/browse/EZP-26430
This patch provides a shortcut `Y.eZ.trans` for `Y.eZ.Translator.trans` so it is shorter and provides a better developer experience. Note that the only supported way of adding translation strings will be to use the shortcut. Also the upcoming Translation Dumper (the other part of this story) will only detect the shortcut.
=> EZP-26430: Provide a shortcut to Y.Translator.trans()

Resources/public/js/views/navigation/ez-navigationitemsubtreeview.js, Tests/js/views/navigation/assets/ez-navigationitemsubtreeview-tests.js
The route matcher for ez-navigationitemsubtreeview is matching the incomplete id.
Example for location id 1/57 location 1/5 is also matched.
By adding a delimiter('/') we guarantee that only the full id is match and also the subitems.
=> EZP-26546: ez-navigationitemsubtreeview route matcher should only match the full id

Resources/public/js/views/services/plugins/ez-contenttreeplugin.js, Resources/public/js/views/services/plugins/ez-searchplugin.js, Tests/js/views/services/plugins/assets/ez-contenttreeplugin-tests.js
> issue: https://jira.ez.no/browse/EZP-24695
1. As agreed with PM, we will the limit of current tree menu to 100 for now until the real
paging support is added sometime next year. Thus reduce likelihood this is hitting
people.
2. However with limit increased, the content type always re-loading issue gets amplified, so make sure code takes care about only loading each and every content type value once. _This should solve the content type loading issue ok for now, and we can rather improve uppon it with more caching etc later._ e.g. The extreme case is reduction of backend requests from 25 to 2 on Projects folder in tree menu with platform demo data.
Todo:
=> EZP-24695: Increase tree view limit to 100 & avoid loading same types in parallel

Resources/public/js/views/services/plugins/extensions/ez-draftserversidevalidation.js, Tests/js/extensions/assets/ez-draftserversidevalidation-tests.js
JIRA: https://jira.ez.no/browse/EZP-26543
This patch fixes a regression introduced in [EZP-26240](https://jira.ez.no/browse/EZP-26240) / https://github.com/ezsystems/PlatformUIBundle/pull/672. Basically when a draft saving fails, the failure does not necessary come from a validation error on fields, as a result the error response might not contain any field error detail so this patch just adds a check to avoid a JavaScript error.
=> EZP-26543: Infinite loading when publishing/saving/previewing an unallowed content

Resources/public/js/views/ez-fieldview.js, Resources/public/js/views/ez-rawcontentview.js, Resources/public/js/views/fields/ez-relation-editview.js, Resources/public/js/views/fields/ez-relation-view.js, Resources/public/js/views/fields/ez-relationlist-editview.js, Resources/public/js/views/fields/ez-relationlist-view.js, Resources/public/js/views/services/plugins/ez-objectrelationloadplugin.js, Resources/public/js/views/services/plugins/ez-objectrelationsloadplugin.js, Tests/js/views/assets/ez-rawcontentview-tests.js, Tests/js/views/fields/assets/ez-relation-editview-tests.js, Tests/js/views/fields/assets/ez-relation-view-tests.js, Tests/js/views/fields/assets/ez-relationlist-editview-tests.js, Tests/js/views/fields/assets/ez-relationlist-view-tests.js, Tests/js/views/services/plugins/assets/ez-objectrelationloadplugin-tests.js, Tests/js/views/services/plugins/assets/ez-objectrelationsloadplugin-tests.js, Tests/js/views/services/plugins/ez-objectrelationloadplugin.html
JIRA: https://jira.ez.no/browse/EZP-26614
Fixes the issue found in https://github.com/ezsystems/PlatformUIBundle/pull/724 about Relation and Relations field rendering in the new Content Peek view.
Basically, this patch changes the events used to load related Content items to now require a source Content item instead of relying on the object referenced by the `content` attribute of the view service. This allows the plugins handling those events to work with view services not having the `content` attribute. This also implies injecting the Content item to the field views and while at it I also inject the Content Type  to be consistent with the field edit views.
unit test + manual tests
=> EZP-26614: Relation and Relations fields not rendered in the Content Peek View

DependencyInjection/Compiler/TranslationDomainsExtensionsPass.php, DependencyInjection/EzPlatformUIExtension.php, DependencyInjection/PlatformUIExtension.php, EzSystemsPlatformUIBundle.php, Resources/config/services.yml, Resources/views/PlatformUI/shell.html.twig, Tests/DependencyInjection/Compiler/TranslationDomainsExtensionsPassTest.php, composer.json
> Implements [EZP-26428](http://jira.ez.no/browse/EZP-26428)
Any bundle that extends PlatformUI and wants to register custom translation domains can expose the translation domains it uses in templates.
To do so, one must make the the Symfony Container Extension from a bundle implement `EzSystems\PlatformUIBundle\DependencyInjection\PlatformUIExtension`. Then implement the `getTranslationDomains` method in the extension, making it return an array of domains (ex: "return ['domain_one', 'domain_two']).
```php
// src/MyBundle/DependencyInjection/MyExtension.php
namespace MyBundle\DependencyInjection;
use EzSystems\PlatformUIBundle\DependencyInjection\PlatformUIExtension;
class MyExtension extends Extension implements PlatformUIExtension
{
public function getTranslationDomains()
{
return …
```
=> Implemented EZP-26428: Extensions can register their translation domains

ApplicationConfig/Providers/InterfaceLanguages.php, Tests/ApplicationConfig/Providers/InterfaceLanguagesTest.php
JIRA: https://jira.ez.no/browse/EZP-26669
With this patch, only the first language provided by the browser is considered and if it's something like `language_COUNTRY`, the `language` alone is also added to the list before the configured default locale.
=> EZP-26669: Align the JavaScript translate strategy on the Symfony one

Resources/public/templates/subitem/listmore.hbt
JIRA: https://jira.ez.no/browse/EZP-26618
Fixes a small regression, in this template, there's no `subitemCount` variable, `location.childCount` has to be used.
manual tests
=> Fix EZP-26618: Missing total number of subitems

Resources/public/js/views/tabs/ez-locationviewrelationstabview.js, Tests/js/views/tabs/assets/ez-locationviewrelationstabview-tests.js
JIRA: https://jira.ez.no/browse/EZP-26657
`loadObjectRelations` event without the `content` parameter was deprecated in https://github.com/ezsystems/PlatformUIBundle/pull/725 but this one was forgotten.
=> Fix EZP-26657: Deprecation log in the console when viewing a Content

Resources/public/css/views/universaldiscovery.css, Resources/public/css/views/universaldiscovery/selected.css
Link: https://jira.ez.no/browse/EZP-26485
On firefox the scroll bars are not working. This leads to push the buttons outside the screen on smaller window/resolution.
This patch fixes the issue by adding:
```css
min-height: 0;
```
To flex containers. The selected answers from this link explains it correctly: https://stackoverflow.com/questions/28636832/firefox-overflow-y-not-working-with-nested-flexbox
Also removed vendor's prefix as they are not needed.
Manual test on firefox and chrome
=> Fix EZP-26485: Scrollbar not working on firefox for the udw selected view

Resources/config/yui.yml, Resources/public/css/views/universaldiscovery/selected.css, Resources/public/templates/universaldiscovery/selected.hbt
Link: https://jira.ez.no/browse/EZP-26599
- Moved the select button up so scrolling is not needed.
- Add an ellipsis when the content name is too long.
Manual tests
=> EZP-26599: Improve selected view

Resources/public/js/views/fields/ez-relation-editview.js, Resources/public/js/views/fields/ez-relationlist-editview.js, Tests/js/views/fields/assets/ez-relation-editview-tests.js, Tests/js/views/fields/assets/ez-relationlist-editview-tests.js
JIRA: https://jira.ez.no/browse/EZP-24994
To fully work, this patch requires https://github.com/ezsystems/ezpublish-kernel/pull/1833 (without it, it has no effect)
This patch makes sure the UDW is run with the correct `startingLocationId` parameter when filling a Relations or Relation field with a default Location/selection root.
manual test + unit tests
=> EZP-24994: "Default Location" is not being honored when using the UDW for "Relations List" and "Relation" fields

Resources/public/js/alloyeditor/toolbars/ezadd.js, Resources/public/js/alloyeditor/toolbars/ezadd.jsx, Tests/js/alloyeditor/toolbars/assets/ez-alloyeditor-toolbar-ezadd-tests.jsx
JIRA: https://jira.ez.no/browse/EZP-25318
This patch makes sure the (+) button is not available when there's a text selection in Online Editor. This is to avoid the user to think the selection will be used to create a new element while the selection is just replaced by what is created.
=> EZP-25318: Having the (+) button while selecting text is misleading

Resources/public/css/views/languageswitcher.css
jira : https://jira.ez.no/browse/EZP-26677
Language switcher dropdown box was partially hidden with language composed by little string
https://youtu.be/dtcl5Z4OGzk
Manually tested
=> EZP-26677: Language switcher dropdown

bin/travis/prepare_behat.sh, composer.json
Added a setting in composer.json to indicate which ezplatform branch should be taken to run behat tests. This will fix behat tests in 1.6 of PlatformUI and avoid having (/forgetting) to change `prepare_behat.sh` script.
=> Fix: make sure TravisCI uses the correct ezplatform branch to run behat tests

Resources/public/css/theme/modules/embed.css, Resources/public/js/alloyeditor/processors/emptyembed.js, Resources/public/js/views/fields/richtext/ez-richtext-resolveembed.js, Resources/public/js/views/fields/richtext/ez-richtext-resolveimage.js, Tests/js/alloyeditor/processors/assets/ez-editorcontentprocessoremptyembed-tests.js, Tests/js/views/fields/richtext/assets/ez-richtext-resolveembed-tests.js, Tests/js/views/fields/richtext/assets/ez-richtext-resolveimage-tests.js
JIRA: https://jira.ez.no/browse/EZP-26475
This patch adds some checks when loading the embedded Content so that the embed does not keep on displaying "Loading" when a Content cannot be loaded. This can happen in different scenarios:
* the user does not have right to read the embedded Content item
* the Content item was removed (even if in this case, the RichText content should have been updated see https://jira.ez.no/browse/EZP-23540)
* the Content item is in the Trash
* the embed represents an Image but the Content item image field is empty
* the embed represents an Image but there was an error loading the image variation
Screencast:
[![](https://img.youtube.com/vi/WVRN39iD9iM/0.jpg)](http://www.youtube.com/watch?v=WVRN39iD9iM "Click to play on Youtube.com")
=> EZP-26475: Infinite loader if embed Content item is unreachable

Form/Processor/ContentTypeFormProcessor.php
https://jira.ez.no/browse/EZP-25298
When you update a content type, two notifications are displayed : 
- one for the draft
- one for the publish
As the publish notification indicates that draft has been saved and published, this PR remove the draft saved notification
Go on a content type edition page and clic on the 'ok' button
Manually
=> EZP-25298 : Too many notifications when updating a Content Type

DependencyInjection/Configuration.php, Resources/config/yui.yml
https://jira.ez.no/browse/EZP-26750
Updated the PlatformUI configuration validation by setting the default value to `combine` property from `yui.yml` files.
After this fix, all the `yui.yml` files that add new JS modules or override existing ones will have the `combine: true` value even when they are omitted.
=> EZP-26750: When combine: true is not defined in any extensions yui.yml file default becomes false reducing performance

DependencyInjection/EzPlatformUIExtension.php, Matcher/PjaxRequest.php, Resources/config/services.yml, Resources/config/views.yml, Resources/views/content/line.html.twig, Tests/Matcher/PjaxRequestTest.php
https://jira.ez.no/browse/EZP-26719
Right now content link on selectroot fielddescription render a front url.
This PR implement a matcher to remove the link on pjax pages so only the name is displayed
- unit test
- manually
composer require ezsystems/platform-ui-bundle:dev-EZP-26719-implement-viewpjaxmatcher-tofix-whitepagelink
=> EZP-26719 : Implement pjax view matcher

Resources/public/js/views/services/plugins/ez-searchplugin.js, Tests/js/views/services/plugins/assets/ez-searchplugin-tests.js
> issue: https://jira.ez.no/browse/EZP-26749
> Regression caused by #723
Not detected on normal tree view as content is not loaded there, in UDW they are, and missing limit on search for content items means it is limited to 25 even if more locations where previously loaded.
Todo:
=> EZP-26749: Error in UDW when displaying 25 or more objects per container

Resources/public/js/alloyeditor/buttons/blockremove.js, Resources/public/js/alloyeditor/buttons/blockremove.jsx, Resources/public/js/alloyeditor/plugins/removeblock.js, Tests/js/alloyeditor/buttons/assets/ez-alloyeditor-button-blockremove-tests.jsx, Tests/js/alloyeditor/plugins/assets/ez-alloyeditor-plugin-removeblock-tests.js
JIRA: https://jira.ez.no/browse/EZP-26019
This patch makes sure the next sibling (or previous sibling element) is correctly focused when an element is removed. There were 2 issues when the newly focused element is an embed or a list.
Screencast:
[![](https://img.youtube.com/vi/hWPqvRkwDZ4/0.jpg)](http://www.youtube.com/watch?v=hWPqvRkwDZ4 "Click to play on Youtube.com")
=> EZP-26019: After deleting an element, the next one is not always focused

Resources/public/js/views/services/ez-searchviewservice.js, Resources/public/js/views/services/plugins/ez-searchplugin.js, Tests/js/views/services/assets/ez-searchviewservice-tests.js, Tests/js/views/services/plugins/assets/ez-searchplugin-tests.js
JIRA: https://jira.ez.no/browse/EZP-26325
PR against https://github.com/ezsystems/PlatformUIBundle/pull/712
**WIP** do a Content search instead of Location search when searching in PlatformUI.
=> EZP-26325: Content search instead of Location search

Resources/public/js/models/ez-contentmodel.js, Resources/public/js/models/ez-locationmodel.js, Resources/public/js/views/dashboard/ez-dashboardblockallcontentview.js, Resources/public/js/views/dashboard/ez-dashboardblockmycontentview.js, Resources/public/js/views/fields/richtext/ez-richtext-resolveembed.js, Resources/public/js/views/fields/richtext/ez-richtext-resolveimage.js, Resources/public/js/views/services/ez-searchviewservice.js, Resources/public/js/views/services/plugins/ez-contenttreeplugin.js, Resources/public/js/views/services/plugins/ez-searchplugin.js, Resources/public/js/views/subitem/ez-asynchronoussubitemview.js, Resources/public/js/views/universaldiscovery/ez-universaldiscoverysearchview.js, Tests/js/models/assets/ez-contentmodel-tests.js, Tests/js/models/assets/ez-locationmodel-tests.js, Tests/js/views/dashboard/assets/ez-dashboardblockallcontentview-tests.js, Tests/js/views/dashboard/assets/ez-dashboardblockmycontentview-tests.js, Tests/js/views/fields/richtext/assets/ez-richtext-resolveembed-tests.js, Tests/js/views/fields/richtext/assets/ez-richtext-resolveimage-tests.js, Tests/js/views/services/assets/ez-searchviewservice-tests.js, Tests/js/views/services/plugins/assets/ez-contenttreeplugin-tests.js, Tests/js/views/services/plugins/assets/ez-searchplugin-tests.js, Tests/js/views/services/plugins/assets/ez-universaldiscoverycontenttreeplugin-tests.js, Tests/js/views/subitem/assets/ez-asynchronoussubitemview-tests.js, Tests/js/views/universaldiscovery/assets/ez-universaldiscoverysearchview-tests.js, composer.json
Jira: https://jira.ez.no/browse/EZP-26325
The goal here was to be able to use query and filter Query properties instead of criteria. By using this users will now be able, while using Solr, to get search results sorted with relevancy.
BTW you need to have a ez-JS-REST-client up to date with https://github.com/ezsystems/ez-js-rest-client/pull/80 (hopefully merged soon).
- unit tests
=> EZP-26325: Use query and filter in PlatformUI

Resources/public/css/views/confirmbox.css
Link: https://jira.ez.no/browse/EZP-26515
When to many draft are present, the bottom of the list is hidden bellow the screen limit. This patch adds a scrollbar when the list is too long.
Manual tests on firefox and chrome
=> Fix EZP-26515: Unable to select an old draft to edit if there are too many

DependencyInjection/EzPlatformUIExtension.php, Resources/public/css/theme/views/contenteditform.css, Resources/public/templates/contenteditform.hbt, Resources/public/templates/rawcontent.hbt
jira: https://jira.ez.no/browse/EZP-26183
In content view and edit view the field group name wasn't displayed or translated.
Manually tested
=> Fix EZP-26183: FieldTypes groups names not displayed

Resources/public/css/views/universaldiscovery/selected.css, Resources/public/templates/universaldiscovery/selected.hbt
Link: https://jira.ez.no/browse/EZP-26776
This PR fixes 2 things on the selected view:
- The name of the selected item is now always displayed. Since #736 we added the ellipsis (along with `overflow:hidden`) it was masked by the rest of the content. In order to fix that, I added a div container around it.
- In some small screen configuration, the list of metadata information could be too small to be used (like 1 line and a scroll bar. This patch sets a minimum height for it in order to fix it.
On firefox:
Manual test on Firefox and Chrome
=> Fix EZP-26776: UDW's selected view doesn't display enough scrollbars

Twig/TwigYuiExtension.php
https://jira.ez.no/browse/EZP-26768
When combine: false is set in yui.yml file it tries to download YUI3 from external Yahoo CDNs.
This is broken on HTTPS.
Even if combine option is false, YUI uses the combo loading for it's own files. If comboBase and root are not set, YUI will load from http://yui.yahooapis.com with an hard coded 'http'.
Setting this options allows to load YUI internal files from ezcombo every project files are loaded separately.
- Set combine option to false in `plateform-ui-bundle/Resources/config/yui.yml`.
- Clear cache + dump assets
- Try to load the ez dashboard on HTTPS
-> the dashboard or login screen should appear normally
(Before this fix it's blocked on loading with JS errors) 
composer require ezsystems/platform-ui-bundle:dev-EZP-26768-yui-loading-https
=> Fix EZP-26768 : YUI3 from external Yahoo CDNs

Resources/config/css.yml, Resources/public/css/modules/breadcrumbs.css, Resources/public/css/views/contentedit.css, Resources/public/css/views/dashboard-blocks.css, Resources/public/css/views/field.css, Resources/public/css/views/fields/edit/relationlist.css, Resources/public/css/views/fields/view/relationlist.css, Resources/public/css/views/locationview.css, Resources/public/css/views/tabs/locations.css, Resources/public/css/views/tabs/relations.css, Resources/public/css/views/trash.css, Resources/public/templates/contentedit.hbt, Resources/public/templates/dashboard/allcontent.hbt, Resources/public/templates/dashboard/mycontent.hbt, Resources/public/templates/dashboard/mydrafts.hbt, Resources/public/templates/fields/edit/relationlist.hbt, Resources/public/templates/fields/view/field.hbt, Resources/public/templates/fields/view/relationlist.hbt, Resources/public/templates/locationview.hbt, Resources/public/templates/tabs/locations.hbt, Resources/public/templates/tabs/relations.hbt, Resources/public/templates/trash.hbt
Link: https://jira.ez.no/browse/EZP-26592
When using a long content name. It is often truncated or worse it pushes some buttons out of the screen. This PR tries to fix most of these behaviors.
Manual tests on firefox and chrome
=> Fix the behavior with long content name

Resources/public/js/models/extensions/ez-contentinfo-base.js, Resources/public/js/models/ez-versionmodel.js, Resources/public/js/views/services/plugins/extensions/ez-draftserversidevalidation.js, Tests/js/extensions/assets/ez-draftserversidevalidation-tests.js, Tests/js/models/assets/ez-versionmodel-tests.js, Tests/js/models/extensions/assets/ez-contentinfo-base-tests.js, Tests/js/views/services/plugins/assets/ez-savedraftplugin-tests.js
jira: https://jira.ez.no/browse/EZP-26550
Goal here was to remove JS error when trying to edit an unallowed content. This was produce because _sortVersions method couldn't handle the case with no versions. This is solved using Y.array.each instead of Object.forEach ( because Y.array.each is smarter and check if array is empty before iterating )
While solving this bug, another one was revealed : version model wasn't returning response on error while creating or updating... This is now fixed.
https://youtu.be/8YapcakQ_NI
=> Fix EZP-26550: Infinite loading when editing unallowed content

Resources/views/PlatformUI/shell.html.twig
> [EZP-26828](http://jira.ez.no/browse/EZP-26828)
Adds the javascript code that integrates [Crowdin's in-context translation UI](https://crowdin.com/page/in-context-localization).
To trigger translations, the ach-UG translation, specific to crowdin, must be installed. It can be done by running `composer require ezplatform-i18n/ezplatform-i18n_ach_ug`. The requirement will be added to ezsystems/ezplatform by default.
To trigger the in-context UI, https://github.com/ezsystems/ezpublish-kernel/pull/1889 is required.
Would allow any project to use in-context translation.
=> Crowdin in-context translation integration

ApplicationConfig/Providers/RootInfo.php, composer.json
Symfony's AssetsHelper was changed recently. It has a backward compatibility feature that enforces
a legacy behaviour when all 3 arguments are defined. The fix is to set arguments 2 and 3
to null (their default value) in order to enter this BC layer.
=> Fixed travis failures in RootInfoTest

Tests/Twig/Fixtures/functions/ez_editorial_yui_config.test, Tests/Twig/TwigYuiExtensionTest.php
Jira : https://jira.ez.no/browse/EZP-26868
Fix test failure introduced by EZP-26768.
Add root and comboBase default value added to fix the previous one + enable second route in router mock.
Should return travis to green
=> EZP-26768 : fix EZP-26768 unit tests

.travis.yml, Tests/ApplicationConfig/Providers/RootInfoTest.php, bin/travis/setupphpunit.sh, composer.json
> Fixes [EZP-26881](https://jira.ez.no/browse/EZP-26881)
With Symfony `3`, the test for `RootInfo` fails. Detailed description of a probable cause of the problem and solution will be provided in a consecutive comment.
**TODO**:
=> EZP-26881: Update usage of AssetHelper to symfony 3.x

Resources/public/js/views/subitem/ez-subitemlistmoreview.js, Tests/js/views/subitem/assets/ez-subitemlistmoreview-tests.js
Link: https://jira.ez.no/browse/EZP-26897
When the default sort order is not displayable in the subitem list (for example LocationPath). The view freezes.
This happens because we are trying to apply a CSS class on a non existing column.
Manual tests on Chrome/Firefox and unit test.
=> EZP-26897: Display broken when subitems sorted by not displayed column

Resources/public/css/theme/views/serverside.css, Resources/translations/content_type.en.xlf, Resources/views/ContentType/view_content_type.html.twig
Link: https://jira.ez.no/browse/EZP-26734
Adds accordions on the main titles of the Content Type View and adds an `additional information` button to display the field's information.
It will not work on IE/Edge for now because HTML5 `details/summary` is not implemented yet.
Screencast: https://drive.google.com/file/d/0B5amepf6EkXbejlUTFp5NnM4ZzA/view?usp=sharing
Another video about accordion: https://www.youtube.com/watch?v=cZFUNo9qOBE
Manual test on Firefox and Chrome
=> EZP-26734: Accordion on main titles of ContentTypeView

ApplicationConfig/Providers/RootInfo.php, Resources/config/services.yml, Resources/config/yui.yml, Tests/ApplicationConfig/Providers/RootInfoTest.php
> Follow-up to [EZP-26881](https://jira.ez.no/browse/EZP-26881) and #782 
It turns out there's more to AssetsHelper issue than just unit test. I expected that but couldn't find any relevant info until I tried to compile Symfony 3 container for eZ Platform 2.0.
The `@templating.helper.assets` service has been deprecated and got removed in Symfony `3.x`. It needs to be replaced with `@assets.packages` service.
**TODO**:
=> Replace deprecated templating.helper.assets with assets.packages service

Resources/config/yui.yml, Resources/public/css/alloyeditor/buttons/linkedit.css, Resources/public/css/external/alloy-editor-ez.css, Resources/public/css/theme/alloyeditor/buttons/linkedit.css, Resources/public/css/theme/alloyeditor/content.css, Resources/public/js/alloyeditor/buttons/linkedit.js, Resources/public/js/alloyeditor/buttons/linkedit.jsx, Resources/public/js/alloyeditor/toolbars/config/link.js, Resources/sass/alloy/skin.scss, Resources/translations/onlineeditor.en.xlf, Tests/js/alloyeditor/buttons/assets/ez-alloyeditor-button-linkedit-tests.jsx, Tests/js/alloyeditor/buttons/ez-alloyeditor-button-linkedit.html, Tests/js/alloyeditor/toolbars/config/assets/ez-alloyeditor-toolbar-config-link-tests.js
JIRA: https://jira.ez.no/browse/EZP-26517
Gives the ability to pick a Content (Location actually) with the UDW to create an internal link.
Screencast:
[![](https://img.youtube.com/vi/3tX3kVFpOKA/0.jpg)](http://www.youtube.com/watch?v=3tX3kVFpOKA "Click to play on Youtube.com")
=> EZP-26517: As an editor, I want to be able to add/edit internal links in Rich Text field

Resources/public/js/views/ez-contenttypeselectorview.js, Resources/public/js/views/services/ez-contentcreateviewservice.js, Resources/public/js/views/services/plugins/ez-contentcreateplugin.js, Tests/js/views/services/assets/ez-contentcreateviewservice-tests.js, Tests/js/views/services/plugins/assets/ez-contentcreateplugin-tests.js
jira: https://jira.ez.no/browse/EZP-26862
PlatformUI was always creating content with the default create language of the app. Now we can set a languageCode to the createContent event to force a content creation on a given language.
Manually and unit tested
=> Fix EZP-26862 Content create with forced language

Resources/config/yui.yml, Resources/public/js/views/universaldiscovery/ez-universaldiscoveryfinderexplorerlevelview.js, Resources/public/templates/universaldiscovery/explorerlevel.hbt, Tests/js/views/universaldiscovery/assets/ez-universaldiscoveryfinderexplorerlevelview-tests.js, Tests/js/views/universaldiscovery/ez-universaldiscoveryfinderexplorerlevelview.html
jira: https://jira.ez.no/browse/EZP-26323
First step in scaling the finder explorer to large amount of items. Currently it will load items 50 by 50 when user is scrolling into the level view.
The next step ( in another PR ) will be to manage to unload from the DOM the previously loaded item which are far from the viewport.
https://youtu.be/iBiHOR2_1hI
=> EZP-25552: Gradually loads items in Explorer

Resources/config/yui.yml, Resources/public/css/theme/views/fields/view/richtext.css, Resources/public/js/apps/ez-platformuiapp.js, Resources/public/js/views/fields/ez-richtext-view.js, Resources/public/js/views/fields/richtext/ez-richtext-locationlink.js, Resources/public/js/views/services/ez-navigationhubviewservice.js, Resources/public/js/views/services/plugins/ez-searchplugin.js, Tests/js/apps/assets/ez-platformuiapp-tests.js, Tests/js/views/fields/assets/ez-richtext-view-tests.js, Tests/js/views/fields/ez-richtext-view.html, Tests/js/views/fields/richtext/assets/ez-richtext-locationlink-tests.js, Tests/js/views/fields/richtext/ez-richtext-locationlink.html, Tests/js/views/services/assets/ez-navigationhubviewservice-tests.js, Tests/js/views/services/plugins/assets/ez-searchplugin-tests.js
JIRA: https://jira.ez.no/browse/EZP-26899
This patch makes sure internal links (`ezlocation://`) links are usable in PlatformUI. If an internal link points to a removed Location or a Location the user is not able to see, the link is just disabled.
Screencast:
[![](https://img.youtube.com/vi/DsnYWMh2pgs/0.jpg)](http://www.youtube.com/watch?v=DsnYWMh2pgs "Click to play on Youtube.com")
unit test + manual tests
=> EZP-26899: Handle internal links when displaying RichText fields

Resources/public/css/views/universaldiscovery/finder.css
Additional fix for https://jira.ez.no/browse/EZP-26323 to make sure level views can be scrolled. It's the same fix as in https://github.com/ezsystems/PlatformUIBundle/pull/741
=> EZP-26323: Make sure Finder Level views gets a scrollbar in Firefox

Resources/translations/ezrepoforms_content_type.en.xlf, Resources/translations/ezrepoforms_content_type.fr_FR.xlf
> [EZP-26755](https://jira.ez.no/browse/EZP-26755)
This particular translation string is defined in platform-ui-bundle, but the translation was in repository-forms. It was lost during the regeneration of strings. This copies the translations to platform-ui.
=> Fix EZP-26755: Content type edit title is not displayed

Resources/public/templates/universaldiscovery/search.hbt, Resources/translations/universaldiscovery.en.xlf
JIRA: https://jira.ez.no/browse/EZP-26918
"Result list" was forgotten in the template update process for translations.
manual tests
=> Fix EZP-26918: "Result list" are not translatable in UDW

Resources/public/templates/tabs/details.hbt, Resources/translations/locationview.en.xlf
JIRA: https://jira.ez.no/browse/EZP-26841
The translation was not dumped because the space between `{{` and `translate` was an non breakable space. (I also fixed the typo in the translation id).
manual tests
=> Fix EZP-26841: Translation message not displayed in sort direction list

Resources/public/js/views/ez-universaldiscoveryview.js, Resources/public/js/views/services/ez-universaldiscoveryviewservice.js, Resources/public/js/views/universaldiscovery/ez-universaldiscoveryfinderexplorerlevelview.js, Resources/public/js/views/universaldiscovery/ez-universaldiscoveryfinderexplorerview.js, Resources/public/js/views/universaldiscovery/ez-universaldiscoveryfinderview.js, Resources/public/js/views/universaldiscovery/ez-universaldiscoverymethodbaseview.js, Tests/js/views/assets/ez-universaldiscoveryview-tests.js, Tests/js/views/services/assets/ez-universaldiscoveryviewservice-tests.js, Tests/js/views/universaldiscovery/assets/ez-universaldiscoveryfinderexplorerlevelview-tests.js, Tests/js/views/universaldiscovery/assets/ez-universaldiscoveryfinderexplorerview-tests.js, Tests/js/views/universaldiscovery/assets/ez-universaldiscoveryfinderview-tests.js, Tests/js/views/universaldiscovery/ez-universaldiscoveryfinderexplorerlevelview.html
JIRA: https://jira.ez.no/browse/EZP-26872
replaces https://github.com/ezsystems/PlatformUIBundle/pull/799
This patch brings the support of the starting Location id UDW parameter to the Finder method.
Screencast:
[![](https://img.youtube.com/vi/pltFbLCkIE0/0.jpg)](http://www.youtube.com/watch?v=pltFbLCkIE0 "Click to play on Youtube.com")
=> EZP-26872: Add support for starting Location id in the UDW Finder

Resources/public/js/alloyeditor/plugins/paste.js, Tests/js/alloyeditor/plugins/assets/ez-alloyeditor-plugin-paste-tests.js
JIRA:  https://jira.ez.no/browse/EZP-26978
`colspan` and `rowspan` attributes were forgotten while (re-)adding support for pasting tables in https://github.com/ezsystems/PlatformUIBundle/pull/801 ([EZP-26884](https://jira.ez.no/browse/EZP-26884)). This patch makes sure we keep those attributes on `td` or `th` elements.
=> Fix EZP-26978: colspan and rowspan attributes stripped out when pasting

Resources/public/js/views/universaldiscovery/ez-universaldiscoveryfinderexplorerlevelview.js, Tests/js/views/universaldiscovery/assets/ez-universaldiscoveryfinderexplorerlevelview-tests.js
jira: https://jira.ez.no/browse/EZP-26997
After 100 items Finder  couldn't load more items and the levelview. This was due to the fact that we weren't watching scroll event after loading the 50 first additional items. This is now fixed
=> Fix EZP-26997: Finder gradual loading fix

Features/Context/PlatformUI.php, Features/Context/SubContext/CommonActions.php
Jira ticket: https://jira.ez.no/browse/EZP-26945
Added implementation of Behat methods for handling the finder explorer.
=> [Behat] EZP-26945: Update sentence related to handling the UDW

Resources/public/js/apps/ez-platformuiapp.js, Resources/public/js/views/ez-navigationhubview.js, Tests/js/apps/assets/ez-platformuiapp-tests.js, Tests/js/views/assets/ez-locationviewview-tests.js, Tests/js/views/assets/ez-navigationhubview-tests.js
jira : https://jira.ez.no/browse/EZP-26044 and https://jira.ez.no/browse/EZP-26470
The first goal of this fix was to correct the bug where navigation hub was hiding upper part of the screen. After investigation the opposite effect (screen was moved down) was also found in some cases.
To fix those effects I had to correct https://jira.ez.no/browse/EZP-26470 (which is basically that navigating between diferent location view were keeping the scroll offset instead of reseting it). So this pull request is fixing both https://jira.ez.no/browse/EZP-26044 and https://jira.ez.no/browse/EZP-26470
=> EZP-26044: Handle height change and scroll on navigation

Resources/public/js/models/ez-trashitemmodel.js, Resources/public/js/views/ez-trashview.js, Resources/public/js/views/services/ez-trashviewservice.js, Resources/public/templates/trash.hbt, Resources/translations/trash.en.xlf, Tests/js/models/assets/ez-trashitemmodel-tests.js, Tests/js/views/assets/ez-trashview-tests.js, Tests/js/views/ez-trashview.html, Tests/js/views/services/assets/ez-trashviewservice-tests.js
Link: https://jira.ez.no/browse/EZP-25478
When a subtree was deleted, in the trash, it was not possible to restore a subitem of this subtree because its parent had been deleted. With this patch, you can now select a new parent for these items in the trash.
Screencast: https://drive.google.com/file/d/0B5amepf6EkXbTTduR1BuaHJmWmc/view
=> EZP-25478: Restore items whose original location has been deleted

.php_cs, ApplicationConfig/Aggregator.php, DependencyInjection/EzPlatformUIExtension.php, Features/Context/Fields.php, Features/Context/PlatformUI.php, Features/Context/Role.php, Features/Context/Users.php, Tests/ApplicationConfig/Providers/InterfaceLanguagesTest.php, Tests/js/apps/assets/ez-platformuiapp-tests.js, Tests/js/views/services/assets/ez-viewservice-tests.js, Tests/js/views/subitem/assets/ez-subitemlistview-tests.js, Twig/TwigYuiExtension.php
=> Fixed CS errors after ezrobot update

Controller/Rest/ContentController.php
Link: https://jira.ez.no/browse/EZP-27050
When editing and publishing a new draft, a draft is left behind.
This patch makes sure a draft is not created when we edit a user.
Manual test
=> Fix EZP-27050: Draft is kept after editing and publishing user

Resources/config/yui.yml, Resources/public/css/theme/views/subitem/listitem.css, Resources/public/js/views/subitem/ez-subitemlistitemview.js, Resources/public/templates/subitem/listitem.hbt, Resources/public/templates/subitem/listmore.hbt, Resources/translations/subitem.en.xlf, Tests/js/views/ez-searchlistview.html, Tests/js/views/subitem/assets/ez-subitemlistitemview-tests.js, Tests/js/views/subitem/ez-subitemlistitemview.html
Link: https://jira.ez.no/browse/EZP-27113
Adds the possibility to edit a content from the sub item list. If a draft is present, the draft conflict screen will be displayed.
Screencast: https://drive.google.com/file/d/0B5amepf6EkXbeUpQNVltZk9hQm8/view
Manual test and updated unit test
=> EZP-27113: Add edit button to sub-item list

.travis.yml, Resources/config/yui.yml, Resources/public/css/theme/views/actions/button.css, Resources/public/css/theme/views/universaldiscovery/explorerlevel.css, Resources/public/js/apps/plugins/ez-updatetreeplugin.js, Resources/public/js/models/structs/ez-contenttree.js, Resources/public/js/views/actions/ez-treeactionview.js, Resources/public/js/views/ez-discoverybarview.js, Resources/public/js/views/ez-treeview.js, Resources/public/js/views/ez-universaldiscoveryview.js, Resources/public/js/views/services/ez-discoverybarviewservice.js, Resources/public/js/views/services/ez-universaldiscoveryviewservice.js, Resources/public/js/views/services/plugins/ez-contenttreeplugin.js, Resources/public/js/views/services/plugins/ez-discoverybarcontenttreeplugin.js, Resources/public/js/views/services/plugins/ez-universaldiscoverycontenttreeplugin.js, Resources/public/js/views/universaldiscovery/ez-universaldiscoveryfinderexplorerlevelview.js, Resources/public/js/views/universaldiscovery/ez-universaldiscoveryfinderexplorerview.js, Resources/public/js/views/universaldiscovery/ez-universaldiscoveryfinderview.js, Resources/public/templates/universaldiscovery.hbt, Resources/translations/bar.en.xlf, Resources/translations/universaldiscovery.en.xlf, Tests/js/views/assets/ez-discoverybarview-tests.js, Tests/js/views/assets/ez-universaldiscoveryview-tests.js, Tests/js/views/ez-universaldiscoveryview.html, Tests/js/views/services/assets/ez-discoverybarviewservice-tests.js, Tests/js/views/services/ez-discoverybarviewservice.html, Tests/js/views/universaldiscovery/assets/ez-universaldiscoveryfinderexplorerlevelview-tests.js, Tests/js/views/universaldiscovery/assets/ez-universaldiscoveryfinderexplorerview-tests.js, Tests/js/views/universaldiscovery/assets/ez-universaldiscoveryfinderview-tests.js
jira: https://jira.ez.no/browse/EZP-26992
This PR regroup https://jira.ez.no/browse/EZP-27008 , https://jira.ez.no/browse/EZP-27009 , https://jira.ez.no/browse/EZP-27010 .
So this actually replace the content tree on the discovery bar by a content browser based on the UDW. Furthermore now we can add to the `contentDiscover` event (the event which launch the UDW)  two new parameters : 
- `minDiscoverDepth` which is an integer defining the depth of the root where we start discovering contents. The level views above this depth are disabled.
- `confirmLabel` which works as the `title` parameter, but allows, instead of defining the title, to define the label of the confirm button.
https://youtu.be/F8kMeZk6g7k
=> Feature EZP-26992:  Content browse finder based

Resources/public/js/views/fields/ez-binarybase-editview.js, Tests/js/views/fields/assets/binarybase-tests.js
Link: https://jira.ez.no/browse/EZP-27147
When fixing the fields in #788 I forgot to prevent from drag and dropping on binary fields. So goal of this PR is to fix that.
Manual test and completed unit tests
=> Fix EZP-27147: Not translatable binary fields can be updated using drag&drop

composer.json
I forgot to update this line when releasing 1.7.
1.8 is not affected.
=> Fixed the base branch of ezplatform for behat in 1.7

Resources/public/js/views/fields/ez-richtext-editview.js, Tests/js/views/fields/ez-richtext-editview.html
JIRA: https://jira.ez.no/browse/EZP-27174
This message was simply forgotten...
manual test
=> Fix EZP-27174: RichText "This field is required" message not translated

Resources/public/js/alloyeditor/plugins/embed.js, Tests/js/alloyeditor/plugins/assets/ez-alloyeditor-plugin-embed-tests.js
JIRA: https://jira.ez.no/browse/EZP-27114
When trying to add something after an embed (or an image), the page scrolls to an above position. This is happening because the `ezadd` toolbar receives the focus while it's not at the correct position and the browser tries to make it visible in its viewport. This incorrect position is due to the fact the embed plugin does not correctly report the position of the embed tag when the users clicks on it. So this patch fixes the *region* object created by the embed plugin to take into account the scroll for all its properties.
=> Fix EZP-27114: Using (+) button in Online Editor makes page scroll to top when an embed/image has the focus

Resources/public/js/views/dashboard/ez-dashboardblockasynchronousview.js, Tests/js/views/dashboard/assets/ez-dashboardblockasynchronousview-tests.js, Tests/js/views/dashboard/assets/ez-dashboardblockmydraftsview-tests.js, Tests/js/views/dashboard/ez-dashboardblockmydraftsview.html
JIRA: https://jira.ez.no/browse/EZP-26709
This patch fixes the error handling on the my drafts dashboard block. It first makes sure the `loading` flag is set to false in case of error. In addition, the retry button was not working as expected, the patch also fixes that.
=> Fix EZP-26709: Incorrect error handling in the my draft block on the dashboard

Resources/public/js/views/services/ez-discoverybarviewservice.js, Tests/js/views/services/assets/ez-discoverybarviewservice-tests.js
jira : https://jira.ez.no/browse/EZP-27144
When a user wanted to browse with the finder the current location where he currently was this was resulting in an infinite loading. Now the user can only select another location than the one he is on ( or cancel to stay on it obviously )
https://youtu.be/w5M2Wfygc_8
Manually and unit tested
=> Fix EZP-27144: Current location not viewable when content browsing

Resources/public/css/views/universaldiscovery/explorer.css
**Jira ticket**: [https://jira.ez.no/browse/EZP-27240](https://jira.ez.no/browse/EZP-27240)
**Description**:
Now, Content browser works as expected. 
Safari requires **display: flex** and **flex:1** on all nested elements to work properly.
=> Fix EZP-27240: Content browser does not display data on Safari

Resources/public/js/apps/ez-platformuiapp.js, Resources/public/js/views/services/ez-discoverybarviewservice.js, Tests/js/apps/assets/ez-platformuiapp-tests.js, Tests/js/views/services/assets/ez-discoverybarviewservice-tests.js
jira : https://jira.ez.no/browse/EZP-27143
This PR fixes 2 things:
- You can now choose the destination of the content you want to create without raising an error. This is done by using the mainLanguageCode from the contentInfo instead of the content ( which wasn't setted in COF )
- The parameters of the UDW are now correctly reseted when launching a new instance of the UDW when we select the location where we want to create the content. Basically this allows to not have the mininimum depth root or a custom label when selecting the location.
Manually and unit tested
=> Fix EZP-27143 Fixed custom UDW to work with content on the fly.

Resources/translations/trash.en.xlf
JIRA issue: https://jira.ez.no/browse/EZP-27252
This PR fixes missing `%` for count parameter in source/target translation of `items.permanently.deleted` key in `/Resources/translations/trash.en.xlf`
> * On the admin interface, go to trash and click on "Empty the trash";
> * After trash is deleted, the following message is displayed at the bottom: 
> %count items were permanently deleted.
> ...which does not reflect the number of contents deleted - see attached screenshot.
=> Fix EZP-27252: Wrong message when deleting trash content

Resources/public/js/views/fields/ez-time-view.js, Tests/js/views/fields/assets/ez-time-view-tests.js
Link: https://jira.ez.no/browse/EZP-27219
The time fields were displayed in the platformUI in the timezone of the browser, while it should be displayed in UTC. This is a regression introduced by #767 when we localized the format of the date in 1.8.0.
This patch just enables what was used before but in the context of the new localized way.
=> Fix EZP-27219: Time fields are displayed in the browser's timezone

Resources/public/js/views/ez-universaldiscoveryview.js, Tests/js/views/assets/ez-universaldiscoveryview-tests.js
JIRA: https://jira.ez.no/browse/EZP-27059
We can now launch the UDW with an 'old' and/or 'wrong' visible method set. This will now use the defaultVisibleMethod (currently 'finder')
=> Fix EZP-27059: UDW should work without correct visible method

Resources/public/js/views/fields/ez-date-editview.js
JIRA: https://jira.ez.no/browse/EZP-26951
2 different strings are used for the exact same purpose. This patch makes sure, we only use one.
Open question: is it OK BC wise to remove a translation or should we still keep it in the translation file ?
unit tests
=> EZP-26951: Duplicated messages in error messages

Resources/public/js/views/universaldiscovery/ez-universaldiscoveryfinderexplorerview.js, Resources/public/js/views/universaldiscovery/ez-universaldiscoveryfinderview.js, Tests/js/views/universaldiscovery/assets/ez-universaldiscoveryfinderexplorerview-tests.js, Tests/js/views/universaldiscovery/assets/ez-universaldiscoveryfinderview-tests.js
JIRA: https://jira.ez.no/browse/EZP-27233
The selected content wasn't correctly resetted while changing tab from finder, it now works as expected
=> Fix EZP-27233: Unable to select finder items after changing tab

Resources/public/js/views/serverside/ez-contenttypeeditserversideview.js, Tests/js/views/serverside/assets/ez-contenttypeeditserversideview-tests.js
JIRA: https://jira.ez.no/browse/EZP-27316
This is a regression introduced in EZP-25002. This is happening because the patch in #739 makes the selection options be indexed starting from 1 while the Selection field type expects the options to be indexed starting from 0.
Note: This PR is created against 1.7 even if the bug does not affect eZ Platform 1.7 because the code responsible for the bug is in PlatformUI 1.7 but it is only really used with repository forms 1.6 which comes with eZ Platform 1.9 (and 1.8).
Note 2:  For 1.9, the exact same patch can be used
=> Fix EZP-27316: Error publishing with a filled ezselection field

Resources/config/services.yml, Resources/public/js/services/ez-googlemapapiloader.js, Resources/public/js/views/fields/ez-maplocation-editview.js, Resources/public/js/views/fields/ez-maplocation-view.js, Tests/js/services/assets/ez-googlemapapiloader-tests.js, Tests/js/views/fields/assets/ez-maplocation-editview-tests.js, Tests/js/views/fields/assets/ez-maplocation-view-tests.js
> Issue: https://jira.ez.no/browse/EZP-26068
> Depends on: https://github.com/ezsystems/ezpublish-kernel/pull/1820
Q:
- Is it ok to use dependency injection on method instead of setApiKey() as was originally discussed? Only value I see with setter injection is if there is a possibility to avoid views having to deal with this logic in the future, but this optional argument does not hinder that.
- Which tests should be adjusted on the views?
- And how can I avoid the jshint error below given the identifier comes from yml config _(I afaik can't inject the key only unless I create a custom application config class just for the google key)_
=> EZP-26068: Fix Google Maps to inject api key

Resources/public/js/views/fields/ez-maplocation-editview.js, Resources/public/js/views/fields/ez-maplocation-view.js, Tests/js/views/fields/assets/ez-maplocation-editview-tests.js, Tests/js/views/fields/assets/ez-maplocation-view-tests.js
Currently google maps won't show up in eZ Platform UI because the configuration is not read correctly. Fixed by correcting typo.
Rebased on 1.7 branch
=> Fix displaying google map in eZ Platform UI when there is a key specified in configuration

Resources/public/js/views/services/plugins/ez-contenteditplugin.js, Tests/js/views/services/plugins/assets/ez-contenteditplugin-tests.js
> JIRA issue: https://jira.ez.no/browse/EZP-27274
This PR fixes not working "Edit" button in Search Results.
> * eZ Platform clean install
> * Login as admin
> * Create an article
> * Search for the article
> * Click on the "Edit"-Button in the result list => no action fired
Manual
=> Fix EZP-27274: In the search result list the "Edit" button does not work

Resources/views/Role/view_role.html.twig
> JIRA: https://jira.ez.no/browse/EZP-25896
This PR removes extra comma on the limitation list:
> * Go to Roles in the admin ui.
> * Click "Editor" under the name column.
> * Select the "Users and Groups using the <Editor> role" tab
> 
> You will see that some limitations end with a comma
=> Fix EZP-25896: Extra comma on the limitation list

Resources/views/Role/update_role.html.twig
> JIRA: https://jira.ez.no/browse/EZP-27365
This PR fix missing english translation for notification displayed when user try to submit invalid data in the role update form. In similar at it was in this case: https://github.com/ezsystems/PlatformUIBundle/pull/850
**Posibility to reproduce this bug is depends on https://github.com/ezsystems/repository-forms/pull/122.**
1. On the admin UI go to content type edit form 
2. Try to create role with duplicated name e.g Editor 
3. Save changes 
4. Message displayed on the bottom contains `form.validation_error` instead of human readable text "Invalid form data"
Manual
=> Fix EZP-27365: Wrong translation domain in update_role.html.twig

bower.json, package.json
JIRA: https://jira.ez.no/browse/EZP-27375
Just make sure to use stable releases of webcomponentsjs polyfill (1.0), Polymer (2.0) and Web Component Tester (6.0)
come on TravisCI!
=> EZP-27375: Upgraded to Polymer 2.0 and last stable release of associated packages

Features/Context/PlatformUI.php
Jira issue: https://jira.ez.no/browse/EZEE-1487
I've changed the visibility of waitWhileLoading method (it's required in one of the PRs) and removed unused method parameter.
This issue has 3 related PRs, the visibility change is required by usage of this method in Form Builder PR. PRs:
Form builder: https://github.com/ezsystems/ezstudio-form-builder/pull/150 (most important)
StudioUI: https://github.com/ezsystems/StudioUIBundle/pull/774
FlexWf: https://github.com/ezsystems/flex-workflow/pull/79 (minor changes)
=> EZEE-1487: Add form scenarios 

Rest/UserFieldTypeProcessor.php
**TIcket:** https://jira.ez.no/browse/EZP-27399
This change is a bit redundant ( https://github.com/ezsystems/ezpublish-kernel/pull/1995 ), but still required due to fact there can only be one field type Processor at the time and this one overwrites Kernel one.
=> EZP-27399: Prevent password hash being returned in by rest

Tests/Twig/TwigYuiExtensionTest.php
This fixes https://jira.ez.no/browse/EZP-27438
Together with PHP 7.x Twig is coming in 2.x version which is a BC break comparing to Twig 1.x in PHP versions lower than 7.x. 
This is a fix for tests: mocks were created in wrong way
Before this fix Travis reported errors in PHP 7.x version:
https://travis-ci.org/ezsystems/PlatformUIBundle/jobs/237106321#L474
=> EZP-27438 fixing Twig 2.x compatibility issues in tests

Resources/public/js/apps/ez-platformuiapp.js, Tests/js/apps/assets/ez-platformuiapp-tests.js
**Jira ticket:** https://jira.ez.no/browse/EZP-27421
**Description:**
The `ez:yui-app:ready` was fired too early, before all plugins were loaded. In my case, the event was fired before handlebars helpers were registered and I couldn't use them in handlebars templates.
In this approach, the event is fired after `initialized` attribute has changed what means the whole app is loaded.
Unit tests are passing, and doesn't need to be updated or should I create a test for the alternative path when the `appReady` event is not fired?
=> EZP-27421: ez:yui-app:ready event is fired too early

.travis.yml, Features/ContentActions/CopyContent.feature, Features/ContentActions/MoveContent.feature, Features/ContentActions/RemoveContent.feature, Features/Context/Fields.php, Features/Context/PlatformUI.php, Features/Context/SubContext/CommonActions.php, Features/Context/Users.php, Features/doc/Sentences.md
JIRA : https://jira.ez.no/browse/EZP-27286
With content tree being removed BDD tests are not up-to-date. I'm adding some tests to work with the new content browse.
=> EZP-27286: Fix BDD to work with content browse

Resources/public/css/theme/views/universaldiscovery/selected.css, Resources/public/css/views/universaldiscovery/selected.css
> JIRA: https://jira.ez.no/browse/EZP-27330
This PR fixes the preview box so it can show the full name of selected content. Based on CSS proposed by @inakijv in JIRA issue. 
* https://github.com/ezsystems/PlatformUIBundle/pull/863
=> Fix EZP-27330: Full name in preview box and on hover of the link in UDW

Resources/config/routing.yml, Resources/config/routing_pjax.yml, Tests/Http/PjaxRequestMatcherTest.php
Updates the test for the change to `PjaxRequestMatcher` from 50dcfa6d8061d1a46e331f9e353ab9ca84754d41.
=> EZP-27282: Updated PjaxRequestmatcherTest

Resources/config/yui.yml, Resources/public/css/modules/richtext.css, Resources/public/css/theme/modules/richtext.css, Resources/public/js/alloyeditor/buttons/embed.js, Resources/public/js/alloyeditor/buttons/embed.jsx, Resources/public/js/alloyeditor/buttons/image.js, Resources/public/js/alloyeditor/buttons/image.jsx, Resources/public/js/alloyeditor/buttons/table.js, Resources/public/js/alloyeditor/buttons/table.jsx, Resources/public/js/alloyeditor/plugins/embed.js, Resources/public/js/alloyeditor/toolbars/config/table.js, Resources/public/js/views/fields/ez-richtext-editview.js, Resources/translations/onlineeditor.en.xlf, Tests/js/alloyeditor/buttons/assets/ez-alloyeditor-button-embed-tests.jsx, Tests/js/alloyeditor/buttons/assets/ez-alloyeditor-button-image-tests.jsx, Tests/js/alloyeditor/buttons/assets/ez-alloyeditor-button-table-tests.jsx, Tests/js/alloyeditor/buttons/ez-alloyeditor-button-table.html, Tests/js/alloyeditor/plugins/assets/ez-alloyeditor-plugin-embed-tests.js
> Issue: https://jira.ez.no/browse/EZP-26516
Todo:
=> EZP-26516: As an editor, I want to be able to add/edit tabular data in RichText editor

Resources/views/PlatformUI/ez-yui-app.html.twig
> https://jira.ez.no/browse/EZP-27359
> https://github.com/ezsystems/ezpublish-kernel/pull/2025
> https://github.com/ezsystems/hybrid-platform-ui/pull/23
Routes for FOSJsRouting were loaded from a fragment in PlatformUIBundle.
Moved to HybridPlatformUI layout in order to get the right SiteAccess context
=> [EZP-27359]: Move routes loading to HybridPlatformUI

Notification/NotificationPool.php
See https://github.com/ezsystems/hybrid-platform-ui/pull/30
=> EZP-27543: Run NotificationPool kernel response subscriber before HPUI ones

Resources/public/js/models/ez-locationmodel.js, Tests/js/models/assets/ez-locationmodel-tests.js
JIRA: https://jira.ez.no/browse/EZP-27437
In order to get the ez-browse custom element's browseToLocation method simple, we want to give the url where the app should navigate to in the location Object
=> EZP-27437: Give uri to location toObject()

Features/Context/PlatformUI.php, Features/Context/SubContext/CommonActions.php
JIRA Ticket: https://jira.ez.no/browse/EZEE-1517
Corresponding PRs:
Content on the Fly (main one) - https://github.com/ezsystems/content-on-the-fly-prototype-bundle/pull/34
StudioUI - https://github.com/ezsystems/StudioUIBundle/pull/782
Small changes here, required by "Content on the fly" PR: 
* new step (to switch UDW tab)
* changed visibility of some methods
* added two small improvements.
=> EZEE-1517: Add new scenarios for the content-on-the-fly-prototype-bundle bundle

Resources/views/ContentType/view_content_type.html.twig
Jira : https://jira.ez.no/browse/EZP-26710
This PR uncomment the display of field definition descriptions on content type view.
This PR should be tested with https://github.com/ezsystems/ezpublish-kernel/pull/1876.
How to validate : go on the content type view of the 'Folder' content type.
`composer require ezsystems/ezpublish-kernel:dev-EZP-26710-Error-fielddescription-without-description ezsystems/platform-ui-bundle:dev-EZP-26710-Error-fielddescription-without-description`
=> EZP-26710 : Error on fielddescription without description

Features/Context/PlatformUI.php
> JIRA: [EZEE-1532](https://jira.ez.no/browse/EZEE-1532)
This is really a cosmetic change: currently when returning the findWithWait result from another method the following message can be seen in PHPStorm:
> Return value is expected to be '\Behat\Mink\Element\NodeElement', '\EzSystems\PlatformUIBundle\Features\Context\NodeElement' returned. Return value type is not compatible with declared.
The class `\EzSystems\PlatformUIBundle\Features\Context\NodeElement` does not exist, it was simply missing the namespace in doc.
Discovered in: https://github.com/ezsystems/StudioUIBundle/pull/819 , but in reality content of this PR is unrelated.
=> EZEE-1532: Change PHPDoc for findWithWait

Resources/public/js/views/fields/ez-relation-editview.js, Tests/js/views/fields/assets/ez-relation-editview-tests.js
This is related to this PR: https://github.com/ezsystems/ezpublish-kernel/pull/2022
This just uses the same code from the RelationList, which constraints the selectable content types based on the field setting.
=> EZP-24800 Support allowed classes limitation for object relation fields

Resources/views/ContentType/update_content_type.html.twig
JIRA: https://jira.ez.no/browse/EZP-27572
Requires: https://github.com/ezsystems/hybrid-platform-ui-core-components/pull/30
Same as https://github.com/ezsystems/hybrid-platform-ui/pull/83, ie only enable "Remove Field Definition" button is at least one is checked.
manual test
=> EZP-27572: Enabled remove field definition button only if one is checked

Resources/public/js/models/ez-trashitemmodel.js, Resources/public/js/views/ez-trashview.js, Resources/public/js/views/services/ez-trashviewservice.js, Resources/public/templates/trash.hbt, Resources/translations/trash.en.xlf, Tests/js/models/assets/ez-trashitemmodel-tests.js, Tests/js/views/assets/ez-trashview-tests.js, Tests/js/views/ez-trashview.html, Tests/js/views/services/assets/ez-trashviewservice-tests.js
JIRA issue: [EZP-27750](https://jira.ez.no/browse/EZP-27750).
>After deleting the parent content, the children are also put into the trash. Even after someone restores the parent, the children still cannot be restored (information "Item's ancestors are in Trash" is still showing). This can be circumvented in eZ Platform 1.10 by using the button "Restore under a new parent", but there is no such button in eZ Platform 1.7 and this means that the children cannot be restored at all using the Platform UI.
This PR is the backport of #819. It backported almost cleanly, with one conflict in the Resources/translations/trash.en.xlf file (the date).
It allows circumventing the issue [EZP-27750](https://jira.ez.no/browse/EZP-27750) as the "Restore under a new parent" button would then be available …
=> EZP-27750: Backport of EZP-25478: Restore items whose original location has been deleted

Resources/config/services.yml
> JIRA: -
This PR removes unused parameters: 
* `ezsystems.platformui.translation.extractor.handlebars.class`
* `ezsystems.platformui.translation.extractor.javascript.class` 
form `services.yml`. Original services was removed with corresponding classes in https://github.com/ezsystems/PlatformUIBundle/pull/738
=> Removed unused parameters: ezsystems.platformui.translation.extractor.{handlebars,javascript}.class

Features/Users/users.feature
> JIRA: [EZEE-1710](https://jira.ez.no/browse/EZEE-1710)
The previously used step did not use an existing user account (well known admin) but created a new one, using the following format as name: `User#uniqid()`
Essentially it works the same way, but the created username is long. So long, that in some resolutions it overlaps with the "Admin Panel" button:
The browsers drivers behave differently with such elements: Firefox driver used currently is able to click on Admin Panel, while Chrome driver suggested in https://github.com/ezsystems/ezplatform/pull/203 fails. With this change the username will be "Administrator User", which fits in the available space.
In addition I will create an issue that the layout does not handle very long usernames well.
=> EZEE-1710: Change selenium version

Resources/public/templates/tabs/versions.hbt
JIRA: https://jira.ez.no/browse/EZP-27865
Moved the language column to the right in version tabs.
This is done for the future improvements of version management of multilingual content
=> EZP-27865: Move language to the right in version tabs

Resources/translations/bar.en.xlf
> JIRA: https://jira.ez.no/browse/EZP-27833
In the translation file, there is wrong placeholder for `id` parameter in `Hiding Location "%id"` message (missing closing `%`).
1. Go to "Content" > "Content structure" > "Locations" Tab of any content e.g "eZ Platform"
2. "Hide" any of location 
3. There is not "%id" value parameter in the notification message text (see attached screenshot)
=> Fix EZP-27833: Wrong parameter placeholder in notification text after hiding location

.travis.yml
Using Redis has been more stable on other repos, so changing it here. Also updated docker paths to the new structure introduced in 1.7 and up a month ago _(`docker` is symlinked to `docker-compose` for travis jobs for BC, so this is just cleanup)_.
_Unit tests will still fail_
=> [Travis] Fix Behat stash failure issues by using Redis

Resources/public/js/views/services/ez-locationviewviewservice.js
> JIRA: https://jira.ez.no/browse/EZP-27849
The `failed.sending.to.trash` translation unit expects `%contentName%` parameter. In the https://github.com/ezsystems/PlatformUIBundle/blob/master/Resources/public/js/views/services/ez-locationviewviewservice.js#L195 is passed `%name%` instead of `%contentName%`.
1. Create user without sufficient permissions to delete nodes 
2. Try to delete e.g folder
3. There is not %contentName% value parameter in the error notification message text
=> Fix EZP-27849: Fixed a parameter name in notification after delete content without sufficient permissions

Resources/public/js/alloyeditor/buttons/list.js, Resources/public/js/alloyeditor/buttons/list.jsx, Resources/public/js/alloyeditor/toolbars/config/text.js, Resources/public/js/views/fields/ez-richtext-editview.js
> https://jira.ez.no/browse/EZP-28030
This PR adds ` 'subscript', 'superscript', 'quote', 'strike',` and `'numbered list'`
Enjoy
Todo:
=> EZP-28030: Alloy editor add support for more builtin buttons

.php_cs
Backporting php-cs-fixer config settings aligned with v2.7.1.
Note: this does not seem to affect code, just aligning it with settings in ezsystems/ezpublish-kernel#2107 for the future.
=> [CS] Aligned php-cs-fixer config with changes from v2.7.1

Resources/public/js/views/fields/ez-media-editview.js, Tests/js/views/fields/assets/ez-media-editview-tests.js
JIRA issue: https://jira.ez.no/browse/EZP-28039
As mentioned in the JIRA issue, video width and height params are shown for the user as placeholders, but field values are still empty during content publishing.
After this change, values gathered from the file are set as field values, not as placeholders.
Some unnecessary tests were removed.
=> EZP-28039: Video width and height params are not saved during content creation

Resources/public/js/views/services/ez-locationviewviewservice.js, Resources/public/js/views/services/ez-navigationhubviewservice.js
https://jira.ez.no/browse/EZP-28003
=> EZP-28003: Unable to go back to the Content structure after content move to the Media library

Resources/public/css/modules/embed.css
> Issue: https://jira.ez.no/browse/EZP-28164
This is a PR to fix a bug when inserting a large image in the content editor.
Before :
After : 
Jérémy.
=> EZP-28164: Set max size of OE image previews to avoid breaking right menu

Resources/config/services.yml, Resources/config/yui.yml, Resources/public/js/models/ez-locationmodel.js, Resources/public/js/views/ez-actionbarview.js, Resources/public/js/views/services/plugins/ez-copysubtreeplugin.js, Resources/translations/bar.en.xlf, Resources/translations/locationview.en.xlf, Tests/js/views/assets/ez-actionbarview-tests.js
> JIRA: https://jira.ez.no/browse/EZP-27759
This PR adds a "Copy subtree" functionality to UI. See the related issue for more details.
=> EZP-27759: As an Editor, I want to copy the whole subtree of Content Objects

Resources/public/templates/trash.hbt, Resources/translations/trash.en.xlf
> Fix https://jira.ez.no/browse/EZP-25636
> Ready for review
> Depends on https://github.com/ezsystems/ezpublish-kernel/pull/2146
Inform that there may be stuff in trash that you're not allowed to read.
=> EZP-25636: User can't access trash if 1+ items are not readable

Resources/public/js/alloyeditor/buttons/embed.js, Resources/public/js/alloyeditor/buttons/embed.jsx, Resources/public/js/alloyeditor/buttons/image.js, Resources/public/js/alloyeditor/buttons/image.jsx, Resources/public/js/alloyeditor/buttons/linkedit.js, Resources/public/js/alloyeditor/buttons/linkedit.jsx
> JIRA: https://jira.ez.no/browse/EZP-28078
This PR contains the workaround patch for unwanted page scroll to the top when user embeds a content/image or choose link location from UDW. The solution is to save and restore scroll position after command execution.    
The direct cause of this issue is `focus` call in https://github.com/ckeditor/ckeditor-dev/blob/release/4.5.x/core/editable.js#L90 (in case of embedding content).
=> EZP-28078: Embedding a Content Object in the RichText Editor makes page scroll up

Resources/public/js/views/services/ez-locationviewviewservice.js, Resources/public/js/views/services/ez-navigationhubviewservice.js, Tests/js/views/services/assets/ez-locationviewviewservice-tests.js, Tests/js/views/services/assets/ez-navigationhubviewservice-tests.js
This PR fixes JS unit tests after changes introduced in https://github.com/ezsystems/PlatformUIBundle/pull/913
=> EZP-28003: Fixed tests for Unable to go back to the Content structure after content move to the Media library

Resources/public/js/views/services/plugins/ez-userloadplugin.js, Resources/public/js/views/tabs/ez-locationviewdetailstabview.js, Resources/public/templates/tabs/details.hbt
> JIRA: https://jira.ez.no/browse/EZP-28577
This PR contains patch for "An error occurred while loading the last contributor." message displayed in the "Last contributor" field on "Details" tab when in fact the "Creator" was removed. Both fields were dependent on same variable indicating loading error.
> 1. Create a new installation of eZ Platform.
> 2. In the Platform UI, create new User in the "Editors" User Group with login "test_editor".
> 3. Log out and log in again as "test_editor".
> 4. Under "Home", create new Article Content Object named "Test Article".
> 5. Log out and log in again as "admin".
> 6. Edit and publish a new version of "Test Article".
> 7. Go to the "Details" tab for "Test Article".Confirm that there is "Administrator User" in the "Last contributor" field.
> 8. …
=> EZP-28577: "Last contributor" shouldn't show error when "Creator" is removed

Resources/public/js/alloyeditor/buttons/linkedit.js
> JIRA: https://jira.ez.no/browse/EZP-28565
This PR contains the workaround patch for unwanted page scroll to the top when insert/remove a link from the RichText editor. The solution is to save and restore scroll position after command execution (same as https://github.com/ezsystems/PlatformUIBundle/pull/920)
> 1. Create new content (e.g. article) using Platform UI 
> 2. Write some long text inside Rich Text field with many lines until scrollbar appears on the right
> 3. Select some text in the last line
> 4. Add link to existing content
> 5. Hit "Save"
=> EZP-28565: Insert/remove link from the RichText editor makes page scroll up

Resources/public/js/views/fields/ez-relation-editview.js, Resources/public/js/views/fields/ez-relationlist-editview.js, Resources/public/js/views/services/plugins/ez-objectrelationloadplugin.js, Resources/public/js/views/services/plugins/ez-objectrelationsloadplugin.js, Tests/js/views/fields/assets/ez-relation-editview-tests.js, Tests/js/views/fields/assets/ez-relationlist-editview-tests.js
> JIRA: https://jira.ez.no/browse/EZP-27264
This PR contains a patch for the wrong object loaded as a value of `relation`/`relationlist` field types when a user creates a new draft based on the previous version. Cause of the problem is that ID of the related object(s) was always taken from current version instead of the field value.
> 1. Create two folders (Folder1; Folder2)
> 2. Create one article and in the relation fieldtype, related it with "Folder1"
> 3. Publish. This will create version1
> 4. Edit the created article and update name to "Article2" and replace the relation to "Folder2"
> 5. Publish it. This will create version2
> 6. Go to "versions" tab of the article, and create a new draft based on verison1 (the one that was first related with "Folder1")
> 7. When we edit this new …
=> EZP-27264: New draft based on a selected version should respect relations

Resources/public/css/views/userprofile.css
JIRA issue: https://jira.ez.no/browse/EZEE-1845
This PR fixes issue, that you cant use *More* button in LandingPage editor. 
It is a bug introduced in: https://github.com/ezsystems/PlatformUIBundle/commit/fd65b441c40405e91c23a56b1a27aa7b8e8ae859
The solution is maybe not the prettiest one, but otherwise, we would have to re-build few parent elements to fix it in the cleaner way. 
I'm sorry, I've accidentally closed https://github.com/ezsystems/PlatformUIBundle/pull/939. This one is against 1.7.
=> EZEE-1845: Can't select siteaccess using More button in StudioUI

Resources/public/js/views/tabs/ez-locationviewdetailstabview.js, Tests/js/views/tabs/assets/ez-locationviewdetailstabview-tests.js
> JIRA: https://jira.ez.no/browse/EZP-28577
This PR fixes broken JavaScript unit tests in https://github.com/ezsystems/PlatformUIBundle/pull/937 and reintroduce `loadingError` attribute for BC.
=> EZP-28577: "Last contributor" shouldn't show error when "Creator" is removed (unit tests and BC)

Loader/ComboLoader.php
This PR contains supplement change for #945. 
This problem was figured-out by @micszo during QA tests for #945. This change is required to make it works in the case when some 3rd party bundles are in use (for e.g. Netgen's TagsBundle).
When `webpack-encore` is configured to work with `json_manifest_path` then `$version` might be just `/` what generates a warning from `preg_match` used in `ComboLoader`.
=> EZEE-1850: Supplement for #945

Controller/PlatformUIController.php, Resources/config/services.yml
> JIRA: https://jira.ez.no/browse/EZEE-1851
Platform UI choose interface language based on `Accept-Language` header value, but the translatable config values passed from backend to frontend via `\EzSystems\PlatformUIBundle\ApplicationConfig\Provider`, use language based on siteaccess. 
This inconsistency makes user unable to render the landing page block name and landing page block attribute names in the correct language.
=> EZEE-1851: shell.html.twig should be rendered with language based on Accept-Language header value

Resources/public/js/extensions/ez-draftconflict.js, Resources/public/js/views/services/ez-locationviewviewservice.js, Tests/js/views/services/assets/ez-locationviewviewservice-tests.js
JIRA: https://jira.ez.no/browse/EZP-28847
This allows user to edit a content directly in the languageCode selected in the language switcher of the content view (instead of mainLanguageCode)
https://youtu.be/Fcb5VGW0Wak
=> EZP-28847: Allows user to edit directly in the language displayed

Resources/public/css/theme/views/actions/translate.css, Resources/public/css/views/actions/translate.css, Resources/public/js/models/ez-contentmodel.js, Resources/public/js/views/actions/ez-translateactionview.js, Resources/public/js/views/services/ez-locationviewviewservice.js, Resources/public/templates/translateaction.hbt, Resources/translations/bar.en.xlf, Tests/js/views/actions/assets/ez-translateactionview-tests.js, composer.json
> JIRA: https://jira.ez.no/browse/EZP-27914
> Depends on https://github.com/ezsystems/ez-js-rest-client/pull/86
Impl. of EZP-27914: As an Editor I want to remove permanently a language from a content item
Note:
=> EZP-27914: As an Editor I want to remove permanently a language from a content item

Resources/config/yui.yml, Resources/public/js/views/fields/ez-richtext-editview.js
**Jira ticket:** https://jira.ez.no/browse/EZEE-1882
**Requires:**
- https://github.com/ezsystems/ezplatform-ee-assets/pull/10
- https://github.com/ezsystems/StudioUIBundle/pull/887
**TODO:**
=> EZEE-1882: Unable to load Landing Page

bower.json
> JIRA: -
YUI3 installation attempt on travis/local environment ends up with 
```
bower ECONNREFUSED  connect ECONNREFUSED 74.6.106.13:80
Stack trace:
Error: connect ECONNREFUSED 74.6.106.13:80
at Object._errnoException (util.js:1019:11)
at _exceptionWithHostPort (util.js:1041:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
Console trace:
Error
at StandardRenderer.error (/home/travis/.nvm/versions/node/v8.6.0/lib/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
at Logger.<anonymous> (/home/travis/.nvm/versions/node/v8.6.0/lib/node_modules/bower/lib/bin/bower.js:110:26)
at emitOne (events.js:115:13)
at Logger.emit (events.js:210:7)
at Logger.emit (/home/travis/.nvm/versions/node/v8.6.0/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39) …
```
=> Fixed YUI3 dependency in bower.json

Controller/Rest/ContentController.php, composer.json
JIRA issue: https://jira.ez.no/browse/EZP-27271
Currently, this PR contains only the first step related to the backend: try to DRY and reuse once parsed and created `RestContentCreateStruct` object.
The related changes in the kernel are here https://github.com/ezsystems/ezpublish-kernel/pull/2268/
=> EZP-27271: Unable to upload large binary file using REST / Platform UI

Resources/config/yui.yml, Resources/public/js/views/fields/ez-selection-editview.js, Resources/public/js/views/fields/ez-selection-view.js, Tests/js/views/fields/assets/ez-selection-view-tests.js, Tests/js/views/fields/ez-selection-editview.html, Tests/js/views/fields/ez-selection-view.html
> Fix https://jira.ez.no/browse/EZP-28258
> Sent to QA
Adds a placeholder title for obsoleted selection choices. This has the positive side effect of fixing the 'x' for removal.
So when you try to publish content with a selection using options that have been removed in the type, what happens is:
- You get the same validation error as before: "Option with index -1 does not exist in the field definition." I was considering to add "The option may have been removed", but now I think that's redundant. The "-1" isn't helpful for non-devs, we could perhaps change it. What we can't do is show the title of the removed option, that info is gone.
- Obsoleted selection choices have the placeholder title "Selected option does not exist", or whatever else we translate it to.
- You can click the x to …
=> EZP-28258: Can't publish/save content with missing Selection option

Resources/translations/language.en.xlf, Resources/translations/section.en.xlf
The translation that was duplicated in ezplatform-admin-ui has been removed.
=> EZEE-1875: Wrong table headers in language/section details view.

Resources/public/js/views/confirmbox/ez-draftconflictview.js, Resources/public/templates/confirmbox/draftconflict.hbt
> JIRA: https://jira.ez.no/browse/EZEE-1876
This PR adds id and status of selected version in the `confirm` event data fired by `Y.eZ.DraftConflictView._confirmDraftEdition`
=> EZEE-1876: "Confirm" event data fired by Y.eZ.DraftConflictView._confirmDraftEdition should contain selected version id and status

Resources/public/js/views/fields/ez-relationlist-editview.js, Resources/public/js/views/fields/ez-relationlist-view.js, Resources/public/templates/fields/edit/relationlist.hbt, Resources/public/templates/fields/view/relationlist.hbt, Tests/js/views/fields/assets/ez-relation-editview-tests.js, Tests/js/views/fields/assets/ez-relation-view-tests.js, Tests/js/views/fields/assets/ez-relationlist-editview-tests.js, Tests/js/views/fields/assets/ez-relationlist-view-tests.js
> JIRA: https://jira.ez.no/browse/EZP-28781
This PR hides items which point to content moved to trash from the view/edit of `ezobjectrelationlist`. 
> 1. Create a new content type that contains ezobjectrelationlist FieldType, e.g. "menu".
> 2. Create new content using "menu" content type, name it "test" and select some contents (e.g. articles).
> 3. Publish this new content.
> 4. Select this content and go to one of the articles that is on relation list.
> 5. Send this article to the trash.
> 6. Go back to "test". Note, that deleted article still appears on the list and clicking on it doesn't redirect to this article.
=> EZP-28781: Content shouldn't be visible in ezobjectrelationlist after sending it to trash

Resources/config/yui.yml, Resources/public/css/alloyeditor/general.css, Resources/public/css/theme/alloyeditor/general.css, Resources/public/js/alloyeditor/plugins/floatingtoolbar.js, Resources/public/js/alloyeditor/toolbars/config/block-floating-base.js, Resources/public/js/alloyeditor/toolbars/config/heading.js, Resources/public/js/alloyeditor/toolbars/config/paragraph.js, Resources/public/js/views/fields/ez-richtext-editview.js, Tests/js/alloyeditor/toolbars/config/assets/ez-alloyeditor-toolbar-config-heading-tests.js, Tests/js/alloyeditor/toolbars/config/assets/ez-alloyeditor-toolbar-config-paragraph-tests.js, Tests/js/alloyeditor/toolbars/config/ez-alloyeditor-toolbar-config-heading.html, Tests/js/alloyeditor/toolbars/config/ez-alloyeditor-toolbar-config-paragraph.html, Tests/js/views/fields/assets/ez-richtext-editview-tests.js
>JIRA: https://jira.ez.no/browse/EZP-28953
Video presenting how the patch works:  https://youtu.be/BdwGLoTe6qw 
1. Create the new Article
2. Into the Intro/Body (or any other RichText field) paste some dummy text in few paragraphs
3. Click on text to get RichText editor toolbox. You will see, that toolbox obscures some parts of the text as shown in the screenshot.
=> EZP-28953: RichText editor's toolbox obscures the preceding paragraph's content

Resources/public/js/alloyeditor/plugins/floatingtoolbar.js
>JIRA: https://jira.ez.no/browse/EZP-28953
Added debounce for updating the position of the floating toolbar as @sunpietro suggested in https://github.com/ezsystems/PlatformUIBundle/pull/962#discussion_r181637986
=> EZP-28953: Added debounce for updating position of the floating toolbar

Resources/config/yui.yml, Resources/public/css/alloyeditor/general.css, Resources/public/css/theme/alloyeditor/general.css, Resources/public/js/alloyeditor/plugins/floatingtoolbar.js, Resources/public/js/alloyeditor/toolbars/config/block-floating-base.js, Resources/public/js/alloyeditor/toolbars/config/heading.js, Resources/public/js/alloyeditor/toolbars/config/paragraph.js, Resources/public/js/views/fields/ez-richtext-editview.js, Tests/js/alloyeditor/toolbars/config/assets/ez-alloyeditor-toolbar-config-heading-tests.js, Tests/js/alloyeditor/toolbars/config/assets/ez-alloyeditor-toolbar-config-paragraph-tests.js, Tests/js/alloyeditor/toolbars/config/ez-alloyeditor-toolbar-config-heading.html, Tests/js/alloyeditor/toolbars/config/ez-alloyeditor-toolbar-config-paragraph.html, Tests/js/views/fields/assets/ez-richtext-editview-tests.js
> JIRA: https://jira.ez.no/browse/EZP-28953 
Backport of https://github.com/ezsystems/PlatformUIBundle/pull/962 and https://github.com/ezsystems/PlatformUIBundle/pull/963 to 1.7
=> Backport of EZP-28953: RichText editor's toolbox obscures the preceding paragraph's content to 1.7

DependencyInjection/Compiler/ValueObjectVisitorPass.php, EzSystemsPlatformUIBundle.php, Resources/config/services.yml, Resources/public/js/models/extensions/ez-contentinfo-base.js, Resources/public/js/models/ez-versioninfomodel.js, Resources/public/js/views/services/plugins/ez-contenteditplugin.js, Resources/public/js/views/services/plugins/ez-versionsplugin.js, Resources/public/templates/confirmbox/draftconflict.hbt, Resources/public/templates/tabs/versions.hbt, Rest/Generator/Json.php, Rest/ValueObjectVisitor/VersionInfo.php, Rest/ValueObjectVisitorDispatcher.php, Tests/DependencyInjection/Compiler/ValueObjectVisitorPassTest.php, Tests/Rest/Generator/JsonTest.php, Tests/Rest/ValueObjectVisitorDispatcherTest.php, Tests/js/models/extensions/assets/ez-contentinfo-base-tests.js, composer.json
> JIRA: https://jira.ez.no/browse/EZP-29106
> **Depends on: https://github.com/ezsystems/ez-js-rest-client/pull/89, https://github.com/ezsystems/ezpublish-kernel/pull/2319** 
Currently, there is API path displayed only instead of full username in the "Versions" tab of location view and in the draft conflict dialog. This is raised _(understandably)_ as a large issue for editors of prominent customers.
In general the idea is to extend the response of `GET /api/ezp/v2/content/objects/52/versions` for the Platform UI needs. This approach allow us to avoid:
- Additional REST requests
- Problems with lack of permissions to read user data by non-administrators
The customization is made by intoducting new media type `application/vnd.ez.platformui.RESOURCE+json` handled by …
=> EZP-29106: Show author name in version list / draft conflict dialog

Resources/public/js/views/services/plugins/ez-objectrelationsloadplugin.js, Tests/js/views/services/plugins/assets/ez-objectrelationsloadplugin-tests.js
> JIRA: https://jira.ez.no/browse/EZP-29239
Related content objects are loaded asynchronous which might lead to the wrong order of elements when rendering value of ezrelationlist field type.
=> EZP-29239: Keeping correct order while loading RelationList items

Resources/public/js/views/fields/ez-relation-editview.js, Resources/public/js/views/fields/ez-relation-view.js, Resources/public/templates/fields/edit/relation.hbt, Resources/public/templates/fields/view/relation.hbt, Tests/js/views/fields/assets/ez-relation-editview-tests.js, Tests/js/views/fields/assets/ez-relation-view-tests.js
> JIRA: https://jira.ez.no/browse/EZP-29281
Same as https://github.com/ezsystems/PlatformUIBundle/pull/955 but for `ezobjectrelation` field type
=> EZP-29281: Content shouldn't be visible in ezobjectrelation after sending it to trash

Resources/public/js/views/universaldiscovery/ez-universaldiscoveryfinderview.js
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-29353](https://jira.ez.no/browse/EZP-29353)
| **Bug/Improvement**| yes
| **Target version** | 1.13
This PR fixes unwanted highlighting of the content in UDW on Firefox 60.0.1+
=> EZP-29353 UDW: unwanted highlight when clicking on content items in Firefox

Resources/public/js/alloyeditor/plugins/embed.js, Resources/public/js/alloyeditor/plugins/yui3.js, Resources/public/js/views/fields/ez-richtext-editview.js, Resources/public/js/views/fields/richtext/ez-richtext-resolveembed.js, Resources/public/js/views/fields/richtext/ez-richtext-resolveimage.js
**Jira ticket:** https://jira.ez.no/browse/EZP-29254
The timeout is for multiple `cmd-z` clicks. I think 1sec is ok, but I'm open to suggestions.
=> EZP-29254: Images embedded in RichText editor dissapear after undo

Features/Standard/platformui.feature
All tests of PlatformUI are passing when run on ezplatform-ee, except for this one. 
I'm currently setting up running these tests here: https://github.com/ezsystems/StudioUIBundle/pull/906 and this test will be filtered out.
=> EZP-29455: Mark test as Platform only

Resources/public/js/views/services/ez-contentcreateviewservice.js, Tests/js/views/services/assets/ez-contentcreateviewservice-tests.js
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-28785](https://jira.ez.no/browse/EZP-28785)
| **Bug/Improvement**| yes
| **Target version** | 1.7
| **BC breaks**      | no
| **Tests pass**     | no
| **Doc needed**     | no
After saving new content item we are no longer "creating" content, but editing - so option to change Draft language should not be available (same behavior as editing Draft that was created before). This fix makes new content Language Dialog aware of content status, so It won't allow changing Languages after pressing "save".
**TODO**:
=> EZP-28785: Unable to publish draft after changing its translation

Resources/public/js/views/fields/ez-date-editview.js, Resources/public/js/views/fields/ez-date-view.js
JIRA ticket: [EZP-29279](https://jira.ez.no/browse/EZP-29279)
Currently the value for Date Field Type displayed in the backoffice is affected by the browser's timezone, meaning that if the browser has timezone below (west of) UTC, then the previous day is displayed.
Value stored in the database is always midnight in UTC. 
Javascript automatically uses the browser's timezone when handling Date objects, so in this PR I fix the issue by manually adding the offset.
=> EZP-29279: Fix value displayed by the Date Field Type being affected by browser time zone

Resources/config/yui.yml, Resources/public/js/views/fields/ez-relationlist-editview.js, Resources/public/templates/fields/edit/relationlist.hbt, Tests/js/views/fields/assets/ez-relationlist-editview-tests.js, Tests/js/views/fields/ez-relationlist-editview.html
This PR is a continuation of https://github.com/ezsystems/PlatformUIBundle/pull/771 in relation to this issue https://jira.ez.no/browse/EZP-26523. 
This PR has been reopened with a few changes to the original approach. Comments left on the older PR should have been addressed.
Notably, the `gallery-debounce` module is now used to initialize the `Y.Sortable` UI element the dom changes too quickly for it to properly load when the field is initially populated with related items. `Y.later` could be used but conflicts with how events bind to the dom here https://yuilibrary.com/yui/docs/api/files/dd_js_delegate.js.html#l148 making Y.debounce a safer choice.
Tests are missing pending an initial round of code review on this approach.
=> EZP-26523: Sorting UI for relation list edit view
