ezsystems/PlatformUIBundle

- Resources/public/js/models/ez-restmodel.js
- Resources/public/js/views/ez-selectionfilterview.js
> Fix Doc issues

- Helper/SystemInfoHelper.php
- Resources/config/services.yml
- Resources/translations/systeminfo.en.xlf
- Resources/views/SystemInfo/info.html.twig
> https://jira.ez.no/browse/EZP-23707
> Fix EZP-23707: Remove dependency on legacy kernel for system information page

- Resources/public/js/views/services/ez-locationviewviewservice.js
- Tests/js/views/services/assets/ez-locationviewviewservice-tests.js
The goal here was to give the config of the route to the locationviewViewService parameters. This will be needed for the country field view issue.
Jira: https://jira.ez.no/browse/EZP-22247
> EZP-22247 Adding config to _getViewParameters() of locationViewViewservice

- Resources/public/js/views/fields/ez-url-view.js
- Tests/js/views/fields/assets/ez-url-view-tests.js
Link: https://jira.ez.no/browse/EZP-23905
Manual and update of unit test
> Fix EZP-23905: JS error displaying a content with an empty Url field

- Resources/public/js/views/actions/ez-treeactionview.js
- Tests/js/views/actions/assets/ez-treeactionview-tests.js
JIRA: https://jira.ez.no/browse/EZP-24033
Regression caused by https://github.com/ezsystems/PlatformUIBundle/pull/169
unit tests + manual test
> EZP-24033: Impossible to navigate with the content tree

- Resources/public/js/views/ez-contenteditformview.js
- Resources/public/js/views/ez-contenteditview.js
- Resources/public/js/views/services/ez-contenteditviewservice.js
- Resources/views/PlatformUI/shell.html.twig
- Tests/js/views/assets/ez-contenteditformview-tests.js
- Tests/js/views/assets/ez-contenteditview-tests.js
- Tests/js/views/services/assets/ez-contenteditviewservice-tests.js
In this first part we want to give configuration from the application to the field edit views.
https://jira.ez.no/browse/EZP-21715
unit tests
> EZP-21715: As an editor, I want to be able edit country fields. 1rst part: Give route config to fieldEditViews

- Resources/config/yui.yml
- Resources/public/css/theme/modules/selection-filter.css
- Resources/public/css/theme/views/fields/edit/selection.css
- Resources/public/js/views/ez-selectionfilterview.js
- Resources/public/js/views/fields/ez-country-editview.js
- Resources/public/js/views/fields/ez-selection-editview.js
- Resources/public/templates/fields/edit/country.hbt
- Resources/views/PlatformUI/shell.html.twig
- Tests/js/views/assets/ez-selectionfilterview-tests.js
- Tests/js/views/fields/assets/ez-country-editview-tests.js
- Tests/js/views/fields/ez-country-editview.html
This is the second part of the edit part of the contry field (first part was mostly done to import the country list from the application : https://github.com/ezsystems/PlatformUIBundle/pull/177).
youtube: http://youtu.be/cpLNMrW65lA
jira: https://jira.ez.no/browse/EZP-21715
> EZP-21715: As an editor, I want to be able edit country fields

- Resources/views/PlatformUI/shell.html.twig
Currently we only provided the country list to editContent, now it will be also done to createContent (see: https://github.com/ezsystems/PlatformUIBundle/pull/177 )
Jira : https://jira.ez.no/browse/EZP-21715
> EZP-21715: Add routeConfig country list to create country field

- Resources/config/css.yml
- Resources/config/yui.yml
- Resources/public/css/theme/views/studiopluspresentation.css
- Resources/public/css/theme/views/studiopresentation.css
- Resources/public/js/apps/ez-platformuiapp.js
- Resources/public/js/views/ez-studiopluspresentationview.js
- Resources/public/js/views/ez-studiopresentationview.js
- Resources/public/js/views/services/ez-navigationhubviewservice.js
- Resources/public/templates/studiopluspresentation.hbt
- Resources/public/templates/studiopresentation.hbt
- Tests/js/views/assets/ez-studiopluspresentationview-tests.js
- Tests/js/views/assets/ez-studiopresentationview-tests.js
- Tests/js/views/ez-studiopluspresentationview.html
- Tests/js/views/ez-studiopresentationview.html
- Tests/js/views/services/assets/ez-navigationhubviewservice-tests.js
Link: https://jira.ez.no/browse/EZP-24007
Add presentation pages for "eZ Studio" and "eZ Studio Plus".
> EZP-24007: As an editor, I want to see a description of Studio and Studio Plus

- Resources/public/js/views/ez-navigationhubview.js
Link: https://jira.ez.no/browse/EZP-24293
Just changed the title
Manual tests
> EZP-24293: Rename the navigation zone "Studio Plus" to "Studio+"

- Resources/public/css/theme/app.css
- Resources/public/css/theme/views/notification.css
- Resources/public/js/apps/plugins/ez-positionplugin.js
- Resources/public/js/models/structs/ez-notification.js
- Resources/public/js/views/ez-notificationview.js
- Tests/js/apps/plugins/assets/ez-positionplugin-tests.js
- Tests/js/apps/plugins/ez-positionplugin.html
- Tests/js/views/assets/ez-notificationview-tests.js
JIRA: https://jira.ez.no/browse/EZP-24327
This patch adds the ability for a component triggering a notification to decide the duration after which the notification should disappear. While working on that, I also noticed that after some time, an offset in the notifications position appears because the height of the notifications was sometimes incorrectly computed due to the CSS transtions. So 6e9db7a also fixes that.
**Screencast: https://www.youtube.com/watch?v=5G7KKNgW1OQ**
> EZP-24327: As an editor, I want the notifications to automatically disappear

- Resources/public/css/theme/views/notification.css
- Resources/public/js/views/ez-notificationview.js
- Resources/public/js/views/services/plugins/ez-savedraftplugin.js
- Tests/js/views/services/plugins/assets/ez-savedraftplugin-tests.js
JIRA: https://jira.ez.no/browse/EZP-23512
This patchs adds some notifications when the editor uses the *Save* button. Please also review the related pull requests on the JavaScript REST client:
* https://github.com/ezsystems/ez-js-rest-client/pull/55
* https://github.com/ezsystems/ez-js-rest-client/pull/56
**Screencast: http://youtu.be/iM3rT62L_so**
> EZP-23512: As an editor, I want to have a visual feedback when I click on save draft

- Resources/public/js/views/serverside/ez-sectionserversideview.js
- Resources/public/js/views/services/ez-sectionserversideviewservice.js
- Resources/views/Section/list.html.twig
- Resources/views/Section/view.html.twig
- Tests/js/views/serverside/assets/ez-sectionserversideview-tests.js
- Tests/js/views/serverside/ez-sectionserversideview.html
- Tests/js/views/services/assets/ez-sectionserversideviewservice-tests.js
JIRA: https://jira.ez.no/browse/EZP-24335
Adding notification when assigning section to contents.
> EZP-24335: Notifications displayed when assigning section to contents

- Controller/ContentTypeController.php
- Controller/PjaxController.php
- Controller/PlatformUIController.php
- Controller/SectionController.php
- Controller/SystemInfoController.php
- Controller/TemplateController.php
- DependencyInjection/Configuration.php
- DependencyInjection/Configuration/PlatformUIMapper.php
- DependencyInjection/EzPlatformUIExtension.php
- Entity/SectionList.php
- Entity/SectionListItem.php
- Form/Processor/ContentTypeFormProcessor.php
- Form/Type/SectionDeleteType.php
- Form/Type/SectionListType.php
- Form/Type/SectionType.php
- Helper/SectionHelper.php
- Helper/SectionHelperInterface.php
- Helper/SystemInfoHelper.php
- Resources/config/image_variations.yml
- Tests/DependencyInjection/EzPlatformUIExtensionTest.php
- Tests/Twig/TwigYuiExtensionTest.php
- Tests/bootstrap.php
- Twig/TwigYuiExtension.php
Jenkins updated for ezrobot to test against PSR-2 as well.
Made with [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer):
`php-cs-fixer --level=psr2`
> Switched to PSR-2

- Resources/public/css/theme/views/actions/button.css
- Resources/public/js/models/ez-locationmodel.js
- Resources/public/js/views/ez-actionbarview.js
- Resources/public/js/views/services/ez-locationviewviewservice.js
- Tests/js/models/assets/ez-locationmodel-tests.js
- Tests/js/views/services/assets/ez-locationviewviewservice-tests.js
Jira: https://jira.ez.no/browse/EZP-24385
The goal of that story is to create button in the action bar view which allows sending content to trash. User should be asked to confirm sending content to trash. Notifications are sent when sending content to trash process is started, when the content is successfully sent to trash and when an error occurs. After sending content to trash app should navigate to location view of parent location.
> EZP-24385: As an editor, I want to be able to remove a content

- Gruntfile.js
- Resources/config/yui.yml
- Resources/public/js/external/ez-capi.js
- Resources/views/PlatformUI/shell.html.twig
- Tests/js/external/assets/capi.js
- Tests/js/external/assets/ez-capi-tests.js
- Tests/js/external/ez-capi.html
This patch improves the way the REST API Client is *imported* in the YUI sandbox. Now, this is unit tested and in addition, we and external contributor can use the same strategy when an external library is needed.
manual + unit test
> Changed the way the REST API Client is imported in YUI sandbox

- Form/Processor/ContentTypeFormProcessor.php
> https://jira.ez.no/browse/EZP-24452
Depends on https://github.com/ezsystems/repository-forms/pull/29
> Fix EZP-24452: Add cancel button in ContentType edition form

- Controller/ContentTypeController.php
- Resources/config/services.yml
- Resources/translations/content_type.en.xlf
- Resources/views/ContentType/view_content_type.html.twig
> https://jira.ez.no/browse/EZP-24439
Pretty straight forward.
HTML markup follows legacy one. I guess that it will be changed at some point :smile:
> Fix EZP-24439: Implement ContentType view

- Gruntfile.js
- Resources/config/yui.yml
- Resources/public/js/views/ez-locationviewtabview.js
- Resources/public/js/views/ez-locationviewview.js
- Resources/public/js/views/tabs/ez-locationviewviewtabview.js
- Resources/public/templates/locationview.hbt
- Resources/public/templates/tabs/view.hbt
- Tests/js/views/assets/ez-locationviewview-tests.js
- Tests/js/views/ez-locationviewview.html
- Tests/js/views/tabs/assets/ez-locationviewviewtabview-tests.js
- Tests/js/views/tabs/ez-locationviewviewtabview.html
JIRA: https://jira.ez.no/browse/EZP-24438
The patch makes the tabs in the location view extensible so we and the extension developers can implement new tabs and add/remove the displayed tabs.
> EZP-24438: As a UI developer, I want to be able to add new tabs in the locationView

- Gruntfile.js
- yuidoc.json
New logo is here, @SylvainGuittard spotted the old one on my screen and almost lost it :)
> Updated livedoc logo

- Resources/public/css/theme/views/actions/button.css
- Resources/public/css/theme/views/languageswitcher.css
- Resources/public/css/views/languageswitcher.css
- Resources/public/js/apps/ez-platformuiapp.js
- Resources/public/js/views/ez-actionbarview.js
- Resources/public/js/views/ez-navigationhubview.js
- Resources/public/templates/languageswitcher.hbt
Some slight style changes, most of those changes are visible in this screenshot:
> Workshop UI refinements

- README.md
- Resources/config/routing.yml
- Tests/js/apps/assets/ez-platformuiapp-tests.js
https://jira.ez.no/browse/EZP-24579
Changing the url to call, to load the PlatformUI application. It's now "myDomainName"/ez#/ instead of "myDomainName"/shell#/
> EZP-24579 Change URL pattern to call PlatformUI

- Resources/public/js/apps/ez-platformuiapp.js
- Resources/public/js/views/services/ez-contenteditviewservice.js
- Resources/public/js/views/services/ez-locationviewviewservice.js
- Tests/js/views/services/assets/ez-contentcreateviewservice-tests.js
- Tests/js/views/services/assets/ez-contenteditviewservice-tests.js
- Tests/js/views/services/assets/ez-locationviewviewservice-tests.js
Jira: https://jira.ez.no/browse/EZP-24549
When viewing the content we are viewing it in given language. When clicking the "Edit" button placed on Action bar we should edit the content in currently selected language.
> EZP-24549: edit content in given language

- Resources/public/js/views/ez-actionbarview.js
- Tests/js/views/assets/ez-actionbarview-tests.js
Edit content button was lacking the content passed to attribute.
> Fix edit content button

- Features/CopyMoveDelete/CopyContent.feature
BDD scenarios for Copy Content feature - https://jira.ez.no/browse/EZP-24188
The current BDD scenarios aim to reflect the behaviour of copying a content in PlatformUI
The situations reflected below are not yet reflected in BDD scenarios 
Todo:
Later follow up:
- Try to copy an object that is read-only for the user
- Try to copy an object to a read-only location
- Try to copy one object that has one child inaccessible to the user.
- Try to copy into a non-container
- Copy multiple objects
- Copy objects to hidden locations
> BDD Copy Content Feature file

- Resources/public/css/theme/views/loginform.css
Just small tweaks here.
Was:
Is:
Review ping @dpobel @mhyndle @yannickroger
> [Login] Small tweaks to login screen

- Features/Context/PlatformUI.php
- Features/Context/SubContext/Authentication.php
- Features/Context/SubContext/CommonActions.php
- Features/Context/SubContext/Copy.php
- Features/Context/SubContext/Move.php
- Features/Context/SubContext/Remove.php
- Features/CopyMoveDelete/CopyContent.feature
- Features/CopyMoveDelete/MoveContent.feature
- Features/CopyMoveDelete/RemoveContent.feature
Implementations of the Move/Copy/Remove sentences for PlatfomUI BDD.
Jira Issues:
https://jira.ez.no/browse/QA-436
https://jira.ez.no/browse/QA-437
https://jira.ez.no/browse/QA-438
depends on:
ezsystems/behatbundle#28
> QA-436 / QA-437 / QA-438 Move, Copy and Remove sentences implementations

- Features/Context/SubContext/CommonActions.php
This PR fixes the problem when the mink node element changes in the browser, and the reference in memory becomes stale - causing an exception.
> Mink stale reference fix

- Resources/views/Section/edit.html.twig
Merge in master and apply formating like other forms.
For merge into #288, only last commit is relevant here as the others comes from the merge from master and will be gone if #288 and then this is rebased before review and merge.
How it looks:
> EZP-24727: Admin form formating/styling for sections

- Features/Context/SubContext/Authentication.php
- Features/Context/SubContext/Fields.php
Small refactor in function name that reflects it's functionality better
> Refactor loggedAsAdminPlaformUi function name

- Features/Context/PlatformUI.php
- Features/Context/SubContext/Remove.php
- Features/CopyMoveDelete/RemoveContent.feature
Missing sentence implementation and some minor fixes to the sentences syntax.
> Minor fixes for Copy/Move/Delete Sentences

- .travis.yml
- Features/Standard/platformui.feature
Changed travis.yml to run PlatformUI behat tests.
Added a `common` tag to the standard feature, for now we should try to run the standard feature and add the rest later
> Travis configurations for PlatformUI Behat tests

- Resources/public/js/views/services/ez-serversideviewservice.js
- Tests/js/views/services/assets/ez-serversideviewservice-tests.js
JIRA: [EZP-24781](https://jira.ez.no/browse/EZP-24781) (sub-task of [EZP-23700](https://jira.ez.no/browse/EZP-23700))
Currently, most sever side form processing do an HTTP redirection to make the application display the result after the form submission. (for instance [redirecting to the section list after deleting a section](https://github.com/ezsystems/PlatformUIBundle/blob/master/Controller/SectionController.php#L137)). This kind of works except that the PlatformUI Application has no way detect such redirection (it's done transparently by the browser/XmlHTTPRequest object), as a result the application gets in an inconsistent state, the URI does not match what is actually displayed and this breaks some buttons/links.
To avoid that, the server side processing of the forms should not …
> EZP-23700: As an editor, I want to see an accurate url and title when I submit a form in the admin part of the PlatformUI

- Controller/ContentTypeController.php
- Controller/Controller.php
- Controller/DashboardController.php
- Controller/PjaxController.php
- Controller/PlatformUIController.php
- Controller/RoleController.php
- Controller/SectionController.php
- Controller/SystemInfoController.php
- Controller/TemplateController.php
- Form/Processor/RoleFormProcessor.php
- Notification/NotificationPoolAware.php
- Resources/config/services.yml
This PR introduces a new `NotificationPoolAware` trait, used in the base controller.
This eases use of notifications.
Also cleaned up RoleController a bit
> Clean up RoleController / SectionController

- Gruntfile.js
- Tests/js/alloyeditor/buttons/assets/ez-alloyeditor-button-embed-tests.jsx
so the auto-generated files are checked by jshint on Travis.
> Update the tasks order when running the test

- Controller/Controller.php
- DependencyInjection/EzPlatformUIExtension.php
- Resources/config/security.yml
- Resources/config/services.yml
Fixes regression mentioned by @wizhippo in https://github.com/ezsystems/PlatformUIBundle/commit/9743e7479cc462ccdfeca9fc6e60af67b8f11fc5#commitcomment-13160311
> Fix security override

- Controller/ContentTypeController.php
- Controller/RoleController.php
- Resources/config/routing_pjax.yml
- Resources/translations/content_type.en.xlf
- Resources/translations/role.en.xlf
- Resources/views/ContentType/view_content_type_group.html.twig
- Resources/views/Role/list_roles.html.twig
> https://jira.ez.no/browse/EZP-24786
> Fix EZP-24786: ContentType and Role creation must use POST

- Controller/ContentTypeController.php
- Form/Processor/ContentTypeGroupFormProcessor.php
- Resources/config/routing_pjax.yml
- Resources/config/services.yml
- Resources/translations/content_type.en.xlf
- Resources/views/ContentType/edit_content_type_group.html.twig
- Resources/views/ContentType/list_content_type_groups.html.twig
> https://jira.ez.no/browse/EZP-24454
Depends on: 
* https://github.com/ezsystems/repository-forms/pull/45
* https://github.com/ezsystems/ezpublish-kernel/pull/1408
> Fix EZP-24454: ContentType group CRUD

- Resources/config/yui.yml
- Resources/public/css/theme/alloyeditor/buttons/labeled-button.css
- Resources/public/js/alloyeditor/buttons/paragraph.js
- Resources/public/js/alloyeditor/buttons/paragraph.jsx
- Resources/public/js/alloyeditor/plugins/addcontent.js
- Resources/public/js/views/fields/ez-richtext-editview.js
- Tests/js/alloyeditor/buttons/assets/ez-alloyeditor-button-paragraph-tests.jsx
- Tests/js/alloyeditor/buttons/ez-alloyeditor-button-paragraph.html
- Tests/js/alloyeditor/plugins/assets/ez-alloyeditor-plugin-addcontent-tests.js
JIRA: https://jira.ez.no/browse/EZP-24723
This patch adds a button to add paragraphs element to editor, basically the same as for heading.
Screencast: https://www.youtube.com/watch?v=tcNziaImsxU
manual + unit test
> EZP-24723: Added the ezparagraph button to add paragraphs

- Controller/RoleController.php
- Form/Processor/RoleFormProcessor.php
- Resources/config/services.yml
- Resources/views/Role/update_role.html.twig
Makes use of role draft features added in main PR in ezpublish-kernel.
Requirement for https://github.com/ezsystems/ezpublish-kernel/pull/1376
Also see https://github.com/ezsystems/repository-forms/pull/41
https://jira.ez.no/browse/EZP-24701
> Fix EZP-24701: Role versioning

- Resources/public/js/views/services/plugins/ez-publishdraftplugin.js
- Tests/js/views/services/plugins/assets/ez-publishdraftplugin-tests.js
JIRA: https://jira.ez.no/browse/EZP-24850
For whatever reason, the error handling was only added when using the "Save draft" button, not the "Publish" one. This patch adds a basic error handling so that the application does not stay in loading mode forever when a server side error occurs.
Screencast: http://youtu.be/2pxvK-lgKmA
manual + unit test
> EZP-24850: Handle error while publishing a content

- Features/Authentication/UsersLogin.feature
- Features/Context/SubContext/Authentication.php
- Features/CopyMoveDelete/CopyContent.feature
- Features/CopyMoveDelete/MoveContent.feature
- Features/CopyMoveDelete/RemoveContent.feature
- Features/Stories/FieldTypes/IntegerFieldType.feature
Added implementation for user with diferent roles login.
relates to jira issue: https://jira.ez.no/browse/EZP-24753
depends on: ezsystems/BehatBundle#33
> Added BDD User login sentences/implementation

- Resources/config/css.yml
- Resources/config/yui.yml
- Resources/public/css/theme/app.css
- Resources/public/css/theme/views/fields/edit/user.css
- Resources/public/css/views/fields/edit/user.css
- Resources/public/js/views/fields/ez-user-editview.js
- Resources/public/js/views/services/plugins/ez-loginavailableplugin.js
- Resources/public/templates/fields/edit/user.hbt
- Tests/js/views/fields/assets/ez-user-editview-tests.js
- Tests/js/views/fields/ez-user-editview.html
- Tests/js/views/services/plugins/assets/ez-loginavailableplugin-tests.js
- Tests/js/views/services/plugins/ez-loginavailableplugin.html
JIRA: https://jira.ez.no/browse/EZP-21821
This patch provides the User edit view which allows to have complete form to edit user. It implements all the needed browser validation (including the login availability check added in https://github.com/ezsystems/ezpublish-kernel/pull/1415 / https://github.com/ezsystems/ez-js-rest-client/pull/65).
But actually, this PR is not be enough to be able to create/edit users because any content with a ezuser has to be saved through the User REST API.
Screencast: http://youtu.be/zodmsr0SP48
> EZP-21821: As an editor, I want to be able to edit content with an User field

- Resources/public/js/apps/ez-platformuiapp.js
- Resources/public/js/views/services/ez-navigationhubviewservice.js
- Resources/translations/content_type.en.xlf
- Resources/translations/section.en.xlf
- Tests/js/views/services/assets/ez-navigationhubviewservice-tests.js
Small fixes to make sure terminology is same on dashboard as well as in menu, also add the missing Roles menu option.
> Admin menu fixes

- Features/Context/PlatformUI.php
- Features/Context/SubContext/CommonActions.php
- Features/Context/SubContext/Role.php
- Features/RoleUI/RoleUI.feature
- Resources/views/Role/list_roles.html.twig
RoleUI BDD sentences and implentations cherry-picked and squashed from #296
> Added Role UI BDD feature file and implementations

- ApplicationConfig/Providers/Languages.php
- Resources/config/services.yml
- Tests/ApplicationConfig/Providers/LanguagesTest.php
Issue: https://jira.ez.no/browse/EZP-24875
Needed for #355
> Fix EZP-24875: Add a LanguageList Application Config Provider

- Resources/config/yui.yml
- Resources/public/css/theme/views/editpreview.css
- Resources/public/css/views/editpreview.css
- Resources/public/js/views/ez-editpreviewview.js
- Resources/public/templates/editpreview.hbt
- Tests/js/views/assets/ez-editpreviewview-tests.js
- Tests/js/views/ez-editpreviewview.html
JIRA: https://jira.ez.no/browse/EZP-24916
This patch fixes the display of the preview. With it, we also handle better handle the preview on a device bigger than the one used by the editor.
Screencast: http://youtu.be/NeOrEjiODWA
> EZP-24916: Platform UI Preview broken

- Controller/RoleController.php
- Controller/SystemInfoController.php
- Form/Processor/PolicyFormProcessor.php
- Resources/config/routing_pjax.yml
- Resources/config/services.yml
- Resources/translations/role.en.xlf
- Resources/views/Role/edit_policy.html.twig
- Resources/views/Role/update_role.html.twig
- Resources/views/Role/view_role.html.twig
> https://jira.ez.no/browse/EZP-24711
> EZP-24711: Role policy editing step 1 & 2

- Resources/config/yui.yml
- Resources/public/css/theme/views/tabs/locations.css
- Resources/public/js/models/ez-locationmodel.js
- Resources/public/js/views/services/plugins/ez-visibilityswitcherplugin.js
- Resources/public/js/views/tabs/ez-locationviewlocationstabview.js
- Resources/public/templates/tabs/locations.hbt
- Tests/js/models/assets/ez-locationmodel-tests.js
- Tests/js/views/services/plugins/assets/ez-visibilityswitcherplugin-tests.js
- Tests/js/views/services/plugins/ez-visibilityswitcherplugin.html
- Tests/js/views/tabs/assets/ez-locationviewlocationstabview-tests.js
- Tests/js/views/tabs/ez-locationviewlocationstabview.html
Link: https://jira.ez.no/browse/EZP-24814
In the locations tab, for every location add a button allowing to hide or reveal it.
Manual and update of unit test
> EZP-24814: Add the hide/reveal buttons in the locations tab

- Resources/public/templates/contentedit.hbt
jira link: https://jira.ez.no/browse/EZP-24801
This PR only consist in renaming labels on content edit header's info.
> EZP-24801 Labels change on content edit header infos

- Features/Context/PlatformUI.php
- Features/Context/SubContext/Authentication.php
- Features/Context/SubContext/Copy.php
- Features/Context/SubContext/Fields.php
- Features/Context/SubContext/Move.php
- Features/Context/SubContext/Remove.php
- Features/Context/SubContext/Users.php
- Features/Users/users.feature
BDD test for the fields view of ezusers.
PS: also minor doc comment fix of the name of the files
> EZP-21821- BDD for edit view for ezuser fields

- behat.yml
> BDD: moved home behat.yml demobundle config

- Resources/public/js/views/actions/ez-previewactionview.js
- Resources/public/js/views/ez-contenteditview.js
- Resources/public/js/views/ez-editactionbarview.js
- Resources/public/js/views/ez-editpreviewview.js
- Tests/js/views/actions/assets/ez-previewactionview-tests.js
- Tests/js/views/assets/ez-contenteditview-tests.js
- Tests/js/views/assets/ez-editactionbarview-tests.js
- Tests/js/views/assets/ez-editpreviewview-tests.js
jira : https://jira.ez.no/browse/EZP-24929
The language code was hardcoded in the URI, now the language code is given to the editPreviewView
> EZP-24929 eng-GB hardcoded in the preview URI

- Resources/public/js/views/fields/ez-selection-editview.js
- Tests/js/views/fields/assets/ez-selection-editview-tests.js
jira : https://jira.ez.no/browse/EZP-24716
Selection field errors display was wrong while editing a content. The problem came from the position of the validate() method, which couldn't covver every use cases.
> EZP-24716 Selection field validation display is wrong while editing

- Controller/RoleController.php
- Resources/config/routing_pjax.yml
- Resources/config/yui.yml
- Resources/public/js/apps/ez-platformuiapp.js
- Resources/public/js/views/serverside/ez-roleserversideview.js
- Resources/public/js/views/services/ez-roleserversideviewservice.js
- Resources/translations/role.en.xlf
- Resources/views/Role/list_roles.html.twig
- Resources/views/Role/view_role.html.twig
- Tests/js/views/serverside/assets/ez-roleserversideview-tests.js
- Tests/js/views/serverside/ez-roleserversideview.html
- Tests/js/views/services/assets/ez-roleserversideviewservice-tests.js
- Tests/js/views/services/ez-roleserversideviewservice.html
TODO:
https://jira.ez.no/browse/EZP-24700
> Fix EZP-24700: Role assignment CRUD

- Resources/public/css/alloyeditor/content.css
- Resources/public/css/theme/alloyeditor/content.css
JIRA: https://jira.ez.no/browse/EZP-25013
This fixes a small regression introduced in https://github.com/ezsystems/PlatformUIBundle/pull/359 where the embed element are not correctly styled in the editor.
manual test
> Fix EZP-25013: Embed elements not correctly styled in the editor

- Controller/RoleController.php
- Resources/views/Role/edit_policy.html.twig
> https://jira.ez.no/browse/EZP-24713
See https://github.com/ezsystems/repository-forms/pull/50
> Fix EZP-24713: Policy limitations edition

- Resources/public/css/views/fields/view/richtext.css
JIRA: https://jira.ez.no/browse/EZP-24970
Before/After:
manual test
> Fix EZP-24970: "Heading1" created with Richtext can't be fully viewed

- Controller/LanguageController.php
- Form/Processor/LanguageFormProcessor.php
- Resources/config/routing_pjax.yml
- Resources/config/services.yml
- Resources/public/js/apps/ez-platformuiapp.js
- Resources/public/js/views/services/ez-navigationhubviewservice.js
- Resources/translations/language.en.xlf
- Resources/views/Dashboard/dashboard.html.twig
- Resources/views/Language/edit.html.twig
- Resources/views/Language/list.html.twig
- Resources/views/Language/view.html.twig
- Tests/bootstrap.php
- Tests/js/views/services/assets/ez-navigationhubviewservice-tests.js
https://jira.ez.no/browse/EZP-22658
Depends on https://github.com/ezsystems/repository-forms/pull/51
> EZP-22658: Add Language managment to Platform UI

- Resources/public/css/theme/views/actions/create-content.css
Just make sure the loading animation is spinning smoothly :)
> Fix: make sure the loader is spinning smoothly

- Resources/views/Role/edit_policy.html.twig
> https://jira.ez.no/browse/EZP-25062
> Fix EZP-25062: "Add a new policy" button raises an exception

- Resources/public/js/models/ez-locationmodel.js
- Resources/public/js/views/services/ez-locationviewviewservice.js
- Tests/js/models/assets/ez-locationmodel-tests.js
- Tests/js/views/services/assets/ez-locationviewviewservice-tests.js
Jira: https://jira.ez.no/browse/EZP-24871
Currently breadcrumb in location view is builded by recursively loading parent locations, which is not very efficient.
This PR introduces `loadPath` method in location model which is loading the path using location query and then it is used for setting the `path` attribute in location view service. Thanks to that number of calls to API can be reduced to single one.
Small comparision of number of REST API calls needed to get the path:
Number of REST API calls | previous method | introduced method
----------------------------------- | ---------------------- | -----------------
Depth 0 (Home) | 0 | 1
Depth 1 (/2/14) | 1 | 1
Depth 2 (/2/14/23) | 2 | 1
Depth 5 (/2/14/23/51/62/72) | 5 | 1
> EZP-24871: use ancestor criterion for getting breadcrumb

- Resources/config/yui.yml
- Resources/public/css/theme/views/tabs/locations.css
- Resources/public/js/models/ez-locationmodel.js
- Resources/public/js/views/services/plugins/ez-locationsloadplugin.js
- Resources/public/js/views/tabs/ez-locationviewlocationstabview.js
- Resources/public/templates/tabs/locations.hbt
- Tests/js/models/assets/ez-locationmodel-tests.js
- Tests/js/models/assets/ez-restmodel-tests.js
- Tests/js/models/ez-locationmodel.html
- Tests/js/views/services/plugins/assets/ez-locationsloadplugin-tests.js
- Tests/js/views/services/plugins/ez-locationsloadplugin.html
- Tests/js/views/tabs/assets/ez-locationviewlocationstabview-tests.js
Link: https://jira.ez.no/browse/EZP-24864
Display a breacrumbs instead of the pathstring. See screenshot.
> EZP-24864: Add breadcrumbs for each location in the Location tab

- Resources/translations/section.en.xlf
jira: https://jira.ez.no/browse/EZP-25153
Changing the button label "Assign to contents" in "Assign to content" in section management part
Manual test done
> EZP-25153: Adjust button label in section management

- Controller/SectionController.php
- Resources/views/Section/list.html.twig
- Resources/views/Section/view.html.twig
> Fixes https://jira.ez.no/browse/EZP-23733
> Also requires https://github.com/ezsystems/ezpublish-kernel/pull/1493
Uses new method for counting policies using section in limitations.
> Fix EZP-23733: The delete button in section view/list should be disabled if the section can not be removed

- Loader/ComboLoader.php
- Resources/config/services.yml
- Tests/Loader/ComboLoaderTest.php
- Tests/fixtures/template_module.js
- Twig/TwigYuiExtension.php
> Jira issue: https://jira.ez.no/browse/EZP-24961
> Status: ready for review
> Dependencies: #427
Enables combining template modules in combo loader.
> EZP-24961: Combine template modules

- .ez.yml
> [bdd] Updated .ez.yml to use clean install

- Features/Context/SubContext/CommonActions.php
- Features/Standard/platformui.feature
> Updates BDD broken by the dashboard change in http://jira.ez.no/browse/EZP-25173
> Fixed failing dashboard BDD

- Features/Context/SubContext/CommonActions.php
- Features/RoleUI/RoleUI.feature
- Features/Standard/platformui.feature
- Features/Users/users.feature
See the commit messages for what was fixed in each case.
> BDD: fixed various failures

- Resources/views/Language/list.html.twig
- Resources/views/Section/list.html.twig
JIRA: https://jira.ez.no/browse/EZP-25126
Before:
After:
manual tests
> Fix EZP-25126: Visually unfinished language list (and Section list)

- Controller/LanguageController.php
> Fixes https://jira.ez.no/browse/EZP-25241
This applies the same fix for Language, as https://jira.ez.no/browse/EZP-24942 did for Content type, Content type group, Role, Policy, and Section. Ref https://github.com/ezsystems/PlatformUIBundle/pull/403
> Fix EZP-25241: Pressing <Enter> in the language form gives an error

- Resources/public/js/views/ez-contenteditview.js
- Resources/public/js/views/fields/ez-maplocation-editview.js
- Resources/public/js/views/services/ez-locationviewviewservice.js
- Resources/public/js/views/services/ez-loginformviewservice.js
- Resources/public/js/views/services/plugins/ez-copycontentplugin.js
- Resources/public/js/views/services/plugins/ez-publishdraftplugin.js
- Resources/public/js/views/services/plugins/ez-savedraftplugin.js
JIRA: https://jira.ez.no/browse/EZP-25245
```bash
$ find Resources/public -type f -exec sed -i 's/occured/occurred/g' {} \;
```
waiting for Travis
> Fix EZP-25245: Notification error message - misspelling

- .travis.yml
- Gruntfile.js
- bin/travis/generate_apidoc.sh
- package.json
- yuidoc.json
JIRA: https://jira.ez.no/browse/EZP-25259
Similar to https://github.com/ezsystems/ez-js-rest-client/pull/70 but for PlatformUI.
The JavaScript API doc is generated and pushed so that it's available at http://ezsystems.github.io/platformui-javascript-api/
this PR :)
> EZP-25259: As a developer, I want to have access to the API doc of PlatformUI

- Resources/public/js/alloyeditor/plugins/addcontent.js
- Resources/public/js/alloyeditor/plugins/embed.js
- Resources/public/js/alloyeditor/plugins/focusblock.js
- Resources/public/js/alloyeditor/plugins/removeblock.js
- Resources/public/js/apps/plugins/ez-registerlanguagehelpersplugin.js
- Resources/public/js/extensions/ez-asynchronousview.js
- Resources/public/js/models/ez-locationmodel.js
- Resources/public/js/services/ez-googlemapapiloader.js
- Resources/public/js/views/actions/ez-translateactionview.js
- Resources/public/js/views/ez-contenteditformview.js
- Resources/public/js/views/ez-languageselectionboxview.js
- Resources/public/js/views/ez-navigationhubview.js
- Resources/public/js/views/ez-notificationhubview.js
- Resources/public/js/views/ez-rawcontentview.js
- Resources/public/js/views/fields/ez-author-editview.js
- Resources/public/js/views/services/ez-contenteditviewservice.js
- Resources/public/js/views/services/ez-locationviewviewservice.js
- Resources/public/js/views/services/ez-roleserversideviewservice.js
- Resources/public/js/views/services/ez-sectionserversideviewservice.js
- Resources/public/js/views/services/plugins/ez-savedraftplugin.js
- Resources/public/js/views/universaldiscovery/ez-universaldiscoverysearchview.js
It's a test for API doc implemented in https://github.com/ezsystems/PlatformUIBundle/pull/476 so this will have to be merged after this one.
> Various API doc fixes

- Resources/public/js/models/ez-contentmodel.js
- Tests/js/models/assets/ez-contentmodel-tests.js
Link: https://jira.ez.no/browse/EZP-24872
Using a rest view instead of fetching locations one by one. This will improve the performances as less REST request will be needed.
Manual tests on locations tab and update of unit tests
> EZP-24872: Use a REST view to load the locations of a content

- Resources/public/css/theme/views/locationview.css
- Resources/public/css/views/locationview.css
- Resources/public/js/views/ez-locationviewview.js
- Resources/public/templates/locationview.hbt
- Tests/js/views/assets/ez-locationviewview-tests.js
jira: https://jira.ez.no/browse/EZP-25223
The goal here was to display the contentType name into the locationViewView.
- Manual tests 
- Unit Tested
> EZP-25223: Display content type in locationviewview

- Controller/ContentTypeController.php
- Resources/translations/content_type.en.xlf
- Resources/views/ContentType/view_content_type.html.twig
- Resources/views/ContentType/view_content_type_group.html.twig
> Fixes https://jira.ez.no/browse/EZP-24848
> Also requires https://github.com/ezsystems/ezpublish-kernel/pull/1539
Checks for existing content, if there is any it disables delete buttons and shows an alt text.
> Fix EZP-24848: Content Type removal does not take into account Contents in the trash

- Resources/config/yui.yml
- Resources/public/js/views/services/plugins/ez-locationsearchplugin.js
- Tests/js/views/services/plugins/assets/ez-locationsearchplugin-tests.js
JIRA: https://jira.ez.no/browse/EZP-25169
Taking over https://github.com/ezsystems/PlatformUIBundle/pull/492 so that it's quickly merged to avoid conflicts with https://github.com/ezsystems/PlatformUIBundle/pull/493
manual and unit tests
> EZP-25169: Optimize content loading in the location search plugin

- Resources/public/css/theme/views/fields/edit/binaryfile.css
- Resources/public/css/theme/views/fields/edit/image.css
- Resources/public/css/theme/views/fields/edit/media.css
- Resources/public/css/theme/views/fields/edit/relation.css
- Resources/public/css/theme/views/fields/edit/relationlist.css
- Resources/public/css/views/fieldedit.css
jira: https://jira.ez.no/browse/EZP-25055
Improving descriptiion text styling for descriptions that are in the edit field infos (image/media/relations...)
- Manually tested
> EZP-25055: Improving description text styling

- Tests/js/alloyeditor/buttons/assets/ez-alloyeditor-button-blockremove-tests.jsx
- Tests/js/alloyeditor/buttons/assets/ez-alloyeditor-button-blocktextaligncenter-tests.jsx
- Tests/js/alloyeditor/buttons/assets/ez-alloyeditor-button-blocktextalignjustify-tests.jsx
- Tests/js/alloyeditor/buttons/assets/ez-alloyeditor-button-blocktextalignleft-tests.jsx
- Tests/js/alloyeditor/buttons/assets/ez-alloyeditor-button-blocktextalignright-tests.jsx
- Tests/js/alloyeditor/buttons/assets/ez-alloyeditor-button-embed-tests.jsx
- Tests/js/alloyeditor/buttons/assets/ez-alloyeditor-button-embedhref-tests.jsx
- Tests/js/alloyeditor/buttons/assets/ez-alloyeditor-button-heading-tests.jsx
- Tests/js/alloyeditor/buttons/assets/ez-alloyeditor-button-image-tests.jsx
- Tests/js/alloyeditor/buttons/assets/ez-alloyeditor-button-imagehref-tests.jsx
- Tests/js/alloyeditor/buttons/assets/ez-alloyeditor-button-imagevariation-tests.jsx
- Tests/js/alloyeditor/buttons/assets/ez-alloyeditor-button-paragraph-tests.jsx
Deprecated calls forgotten in https://github.com/ezsystems/PlatformUIBundle/pull/499
> Make sure to not use deprecated React methods

- Resources/translations/fr/content_type.fr.xlf
- Resources/translations/fr/dashboard.fr.xlf
- Resources/translations/fr/fieldtypes.fr.yml
- Resources/translations/fr/general.fr.xlf
- Resources/translations/fr/language.fr.xlf
- Resources/translations/fr/role.fr.xlf
- Resources/translations/fr/section.fr.xlf
- Resources/translations/fr/systeminfo.fr.xlf
- Resources/translations/fr/validators.fr.xlf
Link: https://jira.ez.no/browse/EZP-25427
Hello ! 
I just translated the language files in French  and organized them in a fr sub-directory in the translations one.
I hope this helps.
Regards
> Created French Translations

- Resources/public/js/views/serverside/ez-roleserversideview.js
- Resources/public/js/views/services/ez-roleserversideviewservice.js
- Tests/js/views/serverside/assets/ez-roleserversideview-tests.js
- Tests/js/views/serverside/ez-roleserversideview.html
- Tests/js/views/services/assets/ez-roleserversideviewservice-tests.js
> Implements https://jira.ez.no/browse/EZP-25159
> Required by https://github.com/ezsystems/repository-forms/pull/64
Javascript methods for the UDW buttons used by the...
...limitation mappers.
> Fix EZP-25159: Implement missing limitation mappers Node and Subtree

- Resources/public/js/views/services/ez-navigationhubviewservice.js
- Tests/js/views/services/assets/ez-navigationhubviewservice-tests.js
**Jira ticket**: https://jira.ez.no/browse/EZP-25522
Now we do not throw an error when user don't have permission to load image variation.
> EZP-25522: User is not able to get variation of his profile image

- .travis.yml
- Features/ContentActions/CopyContent.feature
- Features/ContentActions/MoveContent.feature
- Features/Context/ContentActions.php
- bin/travis/prepare_behat.sh
- bin/travis/runbehat.sh
Come on Travis!
requires https://github.com/ezsystems/ezplatform/pull/95 to have a router for the behat environment and more independent shell scripts to initialize the environment.
> Run Bdd tests on Travis CI

- Resources/config/yui.yml
- Resources/public/css/theme/views/actions/button.css
- Resources/public/css/theme/views/trash.css
- Resources/public/js/models/ez-trashitemmodel.js
- Resources/public/js/views/ez-trashbarview.js
- Resources/public/js/views/ez-trashview.js
- Resources/public/js/views/services/ez-trashviewservice.js
- Resources/public/templates/trash.hbt
- Tests/js/models/assets/ez-trashitemmodel-tests.js
- Tests/js/views/assets/ez-trashbarview-tests.js
- Tests/js/views/assets/ez-trashview-tests.js
- Tests/js/views/ez-trashview.html
- Tests/js/views/services/assets/ez-trashviewservice-tests.js
Link: https://jira.ez.no/browse/EZP-25249
Allow to restore selected items from trash.
Screencast: https://drive.google.com/file/d/0B5amepf6EkXbeG1ObktCQkxtSlk/view?usp=sharing
> EZP-25249: Restore items from trash

- Resources/public/css/layout.css
>  EZP-25546: Pointer events block scrolling after loading is finished in Google Chrome

- Resources/public/templates/loginform.hbt
ping @dpobel @yannickroger 
just a change in the copyright year. let me know if you need a issue in the tracker for it.
> say hello to 2016

- Resources/config/css.yml
- Resources/config/yui.yml
- Resources/public/css/theme/app.css
- Resources/public/css/theme/modules/button.css
- Resources/public/css/theme/modules/form.css
- Resources/public/css/theme/views/subitemlist.css
- Resources/public/css/views/subitemlist.css
- Resources/public/js/models/ez-locationmodel.js
- Resources/public/js/views/ez-subitemlistview.js
- Resources/public/js/views/services/ez-locationviewviewservice.js
- Resources/public/templates/subitemlist.hbt
- Tests/js/models/assets/ez-locationmodel-tests.js
- Tests/js/views/assets/ez-subitemlistview-tests.js
- Tests/js/views/ez-subitemlistview.html
- Tests/js/views/services/assets/ez-locationviewviewservice-tests.js
jira: https://jira.ez.no/browse/EZP-25451
Goal is to be able to set priority for each sub item directly in a subitem list.
https://youtu.be/6Vu48QK3XFs
- Unit tested
- Manually tested
> EZP-25451: Set priority on sub item in sub item list

- Resources/public/js/views/fields/ez-binarybase-editview.js
- Tests/js/views/fields/assets/ez-binaryfile-editview-tests.js
- Tests/js/views/fields/assets/ez-image-editview-tests.js
- Tests/js/views/fields/assets/ez-media-editview-tests.js
Same as https://github.com/ezsystems/PlatformUIBundle/pull/554 for master.
Just waiting for Travis CI to eventually succeed...
> Ezp 25641 image missing on translation

- Resources/public/js/models/ez-locationmodel.js
- Resources/public/js/views/ez-actionbarview.js
- Tests/js/models/assets/ez-locationmodel-tests.js
- Tests/js/views/assets/ez-actionbarview-tests.js
Link: https://jira.ez.no/browse/EZP-25597
It disables the send to trash action button when viewing a location with depth === 1. 
Added two more tests. 
p.s. should i try to add behat tests?
ping @andrerom @bdunogier @dpobel @SylvainGuittard @yannickroger
> EZP-25597: Disable send to Trash action if root location

- Resources/public/js/alloyeditor/buttons/blockremove.js
- Resources/public/js/alloyeditor/buttons/blockremove.jsx
- Resources/public/js/alloyeditor/buttons/embedhref.js
- Resources/public/js/alloyeditor/buttons/embedhref.jsx
- Resources/public/js/alloyeditor/buttons/imagehref.js
- Resources/public/js/alloyeditor/buttons/imagehref.jsx
- Resources/public/js/alloyeditor/buttons/mixins/embeddiscovercontent.js
- Tests/js/alloyeditor/buttons/assets/ez-alloyeditor-button-blockremove-tests.jsx
- Tests/js/alloyeditor/buttons/assets/ez-alloyeditor-button-embedhref-tests.jsx
- Tests/js/alloyeditor/buttons/assets/ez-alloyeditor-button-imagehref-tests.jsx
JIRA: https://jira.ez.no/browse/EZP-25415
* Adds a title on the "block remove" button
* while at it, also adds a title on the select content/image buttons for embeds
unit test + manual test
> EZP-25415: PlatformUI RichText editing bar missing remove tittle/tooltip

- Tests/Twig/TwigYuiExtensionTest.php
- Twig/TwigYuiExtension.php
> JIRA: http://jira.ez.no/browse/EZP-25704
See https://github.com/ezsystems/ezpublish-kernel/pull/1637 for a description.
> EZP-25704: removed deprecated twig initRuntime() usage

- Resources/public/js/views/subitem/ez-subitemgridview.js
- Tests/js/views/subitem/assets/ez-subitemgridview-tests.js
jira: https://jira.ez.no/browse/EZP-25671
Items were duplicated up to 10 when using the "loading more" button for less than 10 items.
- Unit tests & manual tests
> EZP-25671: Duplicate item in grid view when loading more

- Resources/public/js/views/subitem/ez-subitemgridview.js
- Tests/js/views/subitem/assets/ez-subitemgridview-tests.js
jira: https://jira.ez.no/browse/EZP-25671
**PR on master related to https://github.com/ezsystems/PlatformUIBundle/pull/576 (1.3)**
Items were duplicated up to 10 when using the "loading more" button for less than 10 items.
- Unit tests & manual tests
> EZP-25671: Duplicate items in grind view

- Resources/config/yui.yml
- Resources/public/js/alloyeditor/plugins/yui3.js
- Resources/public/js/views/fields/ez-richtext-editview.js
- Tests/js/alloyeditor/plugins/assets/ez-alloyeditor-plugin-yui3-tests.js
- Tests/js/alloyeditor/plugins/ez-alloyeditor-plugin-yui3.html
- Tests/js/views/fields/assets/ez-richtext-editview-tests.js
Replaces https://github.com/ezsystems/PlatformUIBundle/pull/577 to first fix the issue in 1.3
> Fix EZP-25718: Unable to remove inline style

- Controller/ContentTypeController.php
- Tests/Controller/ContentTypeControllerTest.php
> [CI] merge of #585 into master

- ApplicationConfig/Providers/Languages.php
- Resources/config/services.yml
- Resources/public/js/apps/ez-platformuiapp.js
- Resources/public/js/views/ez-contenttypeselectorview.js
- Resources/public/js/views/services/ez-contentcreateviewservice.js
- Resources/public/js/views/services/plugins/ez-contentcreateplugin.js
- Tests/ApplicationConfig/Providers/LanguagesTest.php
- Tests/js/apps/assets/ez-platformuiapp-tests.js
- Tests/js/views/services/assets/ez-contentcreateviewservice-tests.js
- Tests/js/views/services/plugins/assets/ez-contentcreateplugin-tests.js
JIRA: https://jira.ez.no/browse/EZP-25678
#581 against 1.3
> Fix EZP-25678: respect default content language on content create

- Resources/config/yui.yml
- Resources/public/css/views/tabs/locations.css
- Resources/public/js/models/ez-locationmodel.js
- Resources/public/js/views/services/plugins/ez-locationswapplugin.js
- Resources/public/js/views/tabs/ez-locationviewlocationstabview.js
- Resources/public/templates/tabs/locations.hbt
- Tests/js/models/assets/ez-locationmodel-tests.js
- Tests/js/views/services/plugins/assets/ez-locationswapplugin-tests.js
- Tests/js/views/services/plugins/ez-locationswapplugin.html
- Tests/js/views/tabs/assets/ez-locationviewlocationstabview-tests.js
- Tests/js/views/tabs/ez-locationviewlocationstabview.html
Implements https://jira.ez.no/browse/EZP-25501
Actually the feature seems to be working.
Here's an screencast
[![Screencast](https://img.youtube.com/vi/wblOWpBpEt0/0.jpg)](https://www.youtube.com/watch?v=wblOWpBpEt0)
ping @dpobel @StephaneDiot @yannickroger @rolandbenedetti
> EZP-25501: As an editor i want to be able to Swap locations

- Resources/config/yui.yml
- Resources/public/js/models/ez-usermodel.js
- Tests/js/models/assets/ez-usermodel-tests.js
- Tests/js/models/ez-usermodel.html
https://jira.ez.no/browse/EZP-25859
**TO DO:**
Requires: https://jira.ez.no/browse/EZP-25753
> EZP-25859: Add loadDrafts method to User model

- Resources/config/css.yml
- Resources/public/css/modules/loadmorepagination.css
- Resources/public/css/theme/modules/loadmorepagination.css
- Resources/public/css/theme/views/subitem/listitem.css
- Resources/public/css/theme/views/subitem/listmore.css
- Resources/public/css/theme/views/subitembox.css
- Resources/public/css/views/subitem/listitem.css
- Resources/public/css/views/subitem/listmore.css
- Resources/public/css/views/subitembox.css
- Resources/public/js/views/subitem/ez-subitemlistitemview.js
- Resources/public/templates/subitem/listitem/priority.hbt
- Resources/public/templates/subitem/listmore.hbt
- Resources/public/templates/subitembox.hbt
- Tests/js/views/subitem/assets/ez-subitemlistitemview-tests.js
JIRA: https://jira.ez.no/browse/EZP-25795
This patch updates the style of the subitem list. See screencast:
[![](https://img.youtube.com/vi/Qhy002zR_wo/0.jpg)](http://www.youtube.com/watch?v=Qhy002zR_wo "Click to play on Youtube.com")
manual tests
> EZP-25795: Refresh the style of the subitem list view

- Resources/public/js/views/services/plugins/ez-userdraftsplugin.js
- Tests/js/views/services/plugins/assets/ez-userdraftsplugin-tests.js
JIRA: https://jira.ez.no/browse/EZP-25884
This patch makes sure we correctly handle the case where the user has less than 10 drafts. Without this patch, the block just display an error.
> Fix EZP-25884: My Draft block raises an error if the user has less than 10 drafts

- Resources/config/css.yml
- Resources/config/yui.yml
- Resources/public/css/theme/views/dashboard/allcontent.css
- Resources/public/css/theme/views/dashboard/asynchronous.css
- Resources/public/css/theme/views/dashboard/mycontent.css
- Resources/public/js/models/ez-usermodel.js
- Resources/public/js/views/dashboard/ez-dashboardblockmycontentview.js
- Resources/public/js/views/ez-dashboardblocksview.js
- Resources/public/js/views/services/ez-dashboardblocksviewservice.js
- Resources/public/templates/dashboard/allcontent.hbt
- Resources/public/templates/dashboard/mycontent.hbt
- Resources/public/templates/dashboard/mydrafts.hbt
- Tests/js/views/assets/ez-dashboardblocksview-tests.js
- Tests/js/views/dashboard/assets/ez-dashboardblockmycontentview-tests.js
- Tests/js/views/dashboard/ez-dashboardblockmycontentview.html
- Tests/js/views/services/assets/ez-dashboardblocksviewservice-tests.js
JIRA: https://jira.ez.no/browse/EZP-25769
This is the dashboard "My content" block which gives the content made or modified by the logged on user.
> EZP-25769: Dashboard mycontent block

- Resources/public/js/alloyeditor/plugins/addcontent.js
- Tests/js/alloyeditor/plugins/assets/ez-alloyeditor-plugin-addcontent-tests.js
- Tests/js/alloyeditor/plugins/assets/ez-alloyeditor-plugin-embed-tests.js
- Tests/js/alloyeditor/plugins/ez-alloyeditor-plugin-addcontent.html
- Tests/js/alloyeditor/plugins/ez-alloyeditor-plugin-embed.html
JIRA: https://jira.ez.no/browse/EZP-25705
The previous fix for EZP-25705 implemented in #620 was incomplete/buggy...
manual tests (really this time ;)) + unit tests
> EZP-25705: Additional fix so that elements are really added after the list

- Tests/js/views/services/assets/ez-locationviewviewservice-tests.js
JIRA: https://jira.ez.no/browse/EZP-24953
Very low hanging fruit, the patch just adds 2 tests to fully cover the LocationView view service.
unit tests
> Fix EZP-24953: Missing code coverage in ez-locationviewviewservice.js

- Resources/config/yui.yml
- Resources/public/js/apps/ez-platformuiapp.js
- Resources/public/js/apps/plugins/ez-universaldiscoveryplugin.js
- Resources/public/js/views/ez-contenteditview.js
- Tests/js/apps/assets/ez-platformuiapp-tests.js
- Tests/js/apps/ez-platformuiapp.html
- Tests/js/apps/plugins/assets/ez-universaldiscoveryplugin-tests.js
- Tests/js/views/assets/ez-contenteditview-tests.js
https://github.com/ezsystems/PlatformUIBundle/pull/629 into master
> EZP-25874: Press ESC exits content edit mode. merge in master

- Resources/config/yui.yml
- Resources/public/js/apps/ez-platformuiapp.js
- Resources/public/js/apps/plugins/ez-universaldiscoveryplugin.js
- Resources/public/js/views/ez-contenteditview.js
- Tests/js/apps/assets/ez-platformuiapp-tests.js
- Tests/js/apps/ez-platformuiapp.html
- Tests/js/apps/plugins/assets/ez-universaldiscoveryplugin-tests.js
- Tests/js/views/assets/ez-contenteditview-tests.js
https://github.com/ezsystems/PlatformUIBundle/pull/629 to 1.4
> EZP-25874 : Press ESC exits content edit mode 1.4

- Resources/public/css/views/tabs/versions.css
- Resources/public/js/models/ez-versioninfomodel.js
- Resources/public/js/models/ez-versionmodel.js
- Resources/public/js/views/services/plugins/ez-versionsplugin.js
- Resources/public/js/views/tabs/ez-locationviewversionstabview.js
- Resources/public/templates/tabs/versions.hbt
- Tests/js/models/assets/ez-versioninfomodel-tests.js
- Tests/js/views/services/plugins/assets/ez-versionsplugin-tests.js
- Tests/js/views/services/plugins/ez-versionsplugin.html
- Tests/js/views/tabs/assets/ez-locationviewversionstabview-tests.js
- Tests/js/views/tabs/ez-locationviewversionstabview.html
Link: https://jira.ez.no/browse/EZP-25463
Allows to delete drafts displayed in the version tab
> EZP-25463: Delete drafts in version tab

- Resources/public/js/views/services/plugins/ez-versionsplugin.js
- Resources/public/js/views/tabs/ez-locationviewversionstabview.js
- Resources/public/templates/tabs/versions.hbt
- Tests/js/views/services/plugins/assets/ez-versionsplugin-tests.js
- Tests/js/views/tabs/assets/ez-locationviewversionstabview-tests.js
- Tests/js/views/tabs/ez-locationviewversionstabview.html
Link: https://jira.ez.no/browse/EZP-25462
Adds a delete button allowing deleting archived versions.
> EZP-25462: Delete an archived in Version tab

- Resources/public/js/views/services/plugins/ez-versionsplugin.js
- Resources/public/js/views/tabs/ez-locationviewversionstabview.js
- Resources/public/templates/tabs/versions.hbt
- Tests/js/views/services/plugins/assets/ez-versionsplugin-tests.js
- Tests/js/views/tabs/assets/ez-locationviewversionstabview-tests.js
- Tests/js/views/tabs/ez-locationviewversionstabview.html
Link: https://jira.ez.no/browse/EZP-26089
Adds an edit button to the draft list.
> EZP-26089: Edit a draft from version tab

- Resources/public/css/theme/views/actions/button.css
- Resources/public/js/apps/ez-platformuiapp.js
- Resources/public/js/views/ez-discoverybarview.js
- Resources/public/js/views/services/ez-discoverybarviewservice.js
- Tests/js/views/assets/ez-discoverybarview-tests.js
- Tests/js/views/services/assets/ez-discoverybarviewservice-tests.js
JIRA: https://jira.ez.no/browse/EZP-26003
First part of the search epic : this only add the search button in the discoverybar and the route to the app
> EZP-26003: Add search button in PlatformUI

- Resources/public/css/views/universaldiscovery.css
- Resources/public/css/views/universaldiscovery/search.css
**Jira ticket:** https://jira.ez.no/browse/EZP-26124
**Screen**
**Description**
Added overflow auto on results container.
**Tests**
manual tests
> EZP-26124: Results of search in UDW overflow

- Resources/public/css/theme/views/contentcreationwizard.css
- Resources/public/css/theme/views/dashboard-blocks.css
- Resources/public/css/views/contentcreationwizard.css
- Resources/public/css/views/dashboard-blocks.css
- Resources/public/templates/contentcreationwizard.hbt
JIRA: https://jira.ez.no/browse/EZP-26090
This patch improves the style of the Content Creation Wizard.
See the following screencast:
[![](https://img.youtube.com/vi/S6asFcTOOhU/0.jpg)](http://www.youtube.com/watch?v=S6asFcTOOhU "Click to play on Youtube.com")
manual tests
> EZP-26090: Improved the style of the Content Creation Wizard

- Controller/ContentTypeController.php
- Controller/LanguageController.php
- Controller/RoleController.php
- Controller/SectionController.php
- Resources/config/services.yml
- Resources/config/yui.yml
- phpunit.xml
Status: **WIP**
JIRA Story: [EZP-26128](https://jira.ez.no/browse/EZP-26128)
**TODO**:
> EZP-26128: As a Developer I want deprecation issues resolved, so that application logs are clean

- Resources/public/js/alloyeditor/plugins/yui3.js
- Tests/js/alloyeditor/plugins/assets/ez-alloyeditor-plugin-yui3-tests.js
Same as https://github.com/ezsystems/PlatformUIBundle/pull/664 for 1.4
> EZP-26145: Unable to undo in the RichText editor (1.4)

- Resources/public/js/alloyeditor/plugins/yui3.js
- Tests/js/alloyeditor/plugins/assets/ez-alloyeditor-plugin-yui3-tests.js
Same as https://github.com/ezsystems/PlatformUIBundle/pull/664 for master
> EZP-26145: Unable to undo in the RichText editor (master)

- Resources/public/js/views/services/plugins/ez-searchplugin.js
- Tests/js/views/services/plugins/assets/ez-searchplugin-tests.js
jira: https://jira.ez.no/browse/EZP-26130
The searchPlugin was not made to be able to search content with multiple location. This is now fixed
- Manual & unit tests
> Fix EZP-26130: Search for content with many locations

- Resources/public/css/theme/views/search.css
- Resources/public/css/theme/views/searchlist.css
- Resources/public/css/theme/views/subitem/listitem.css
- Resources/public/css/views/search.css
- Resources/public/css/views/searchlist.css
- Resources/public/templates/searchlistview.hbt
- Resources/public/templates/searchview.hbt
Jira : https://jira.ez.no/browse/EZP-26005
Goal here was to have a search list looking like the subitem list.
> EZP-26005: Align the style of the search on the subitem

- Resources/translations/content_type.en.xlf
- Resources/translations/ezrepoforms_content_type.en.xlf
- Resources/translations/fieldtypes.en.xlf
- Resources/translations/general.en.xlf
- Resources/translations/language.en.xlf
- Resources/translations/role.en.xlf
- Resources/translations/section.en.xlf
- Resources/translations/systeminfo.en.xlf
- Resources/translations/validators.en.xlf
Working on #525 I had to run `php app/console translation:update` on PlatformUI.
I had a huge "backlog" diff that was not part of what I am working on and would mess up my diff, so I am opening this PR to deal with it.
Command ran : `php app/console translation:update --dump-messages --force --output-format=xlf --no-backup en eZPlatformUIBundle`
> Ran translation:update command

- Resources/public/css/theme/views/loginform.css
- Resources/public/templates/loginform.hbt
JIRA: https://jira.ez.no/browse/EZP-26371
Removes currently unused link, which should be reintroduced once the feature is done/available.
> Fix EZP-26371: "Reset password" link does nothing.

- Resources/public/js/views/services/ez-navigationhubviewservice.js
- Resources/public/js/views/services/plugins/ez-locationswapplugin.js
- Resources/public/js/views/subitem/ez-asynchronoussubitemview.js
- Resources/translations/section.en.xlf
JIRA: https://jira.ez.no/browse/EZP-26293
Just fixing a few typos
> Fix EZP-26293: Typos in Platform UI

- Resources/public/css/views/universaldiscovery/selected.css
JIRA: https://jira.ez.no/browse/EZP-26415
Small regression caused by https://github.com/ezsystems/PlatformUIBundle/pull/686
manual tests
> Fix EZP-26415: Animation issue when selecting a content in the UDW

- Resources/public/js/views/fields/ez-binarybase-editview.js
- Resources/public/js/views/fields/ez-image-editview.js
- Tests/js/views/fields/assets/binarybase-tests.js
- Tests/js/views/fields/assets/ez-image-editview-tests.js
jira : https://jira.ez.no/browse/EZP-26193
The patch correct a bug giving the possibility to upload 'false' images ( like any file renamed with a valid image extension).
> EZP-26193: Invalid image upload

- Resources/public/js/views/fields/ez-binarybase-editview.js
- Resources/public/js/views/fields/ez-image-editview.js
- Tests/js/views/fields/assets/binarybase-tests.js
- Tests/js/views/fields/assets/ez-image-editview-tests.js
jira : https://jira.ez.no/browse/EZP-26193
> Ezp 26193 upload invalid image 1.6.1

- Resources/public/js/views/fields/ez-binarybase-editview.js
- Resources/public/js/views/fields/ez-image-editview.js
- Tests/js/views/fields/assets/binarybase-tests.js
- Tests/js/views/fields/assets/ez-image-editview-tests.js
jira : https://jira.ez.no/browse/EZP-26193
> EZP-26193 :Upload invalid image into master

- Resources/public/templates/confirmbox.hbt
- Resources/public/templates/confirmbox/draftconflict.hbt
- Resources/public/templates/fields/edit/author.hbt
- Resources/public/templates/fields/edit/authorinput.hbt
- Resources/public/templates/fields/edit/binaryfile.hbt
- Resources/public/templates/fields/edit/date.hbt
- Resources/public/templates/fields/edit/image.hbt
- Resources/public/templates/fields/edit/maplocation.hbt
- Resources/public/templates/fields/edit/media.hbt
- Resources/public/templates/fields/edit/relation.hbt
- Resources/public/templates/fields/edit/relationlist.hbt
- Resources/public/templates/fields/edit/richtext.hbt
- Resources/public/templates/fields/edit/url.hbt
- Resources/public/templates/fields/edit/user.hbt
- Resources/public/templates/navigationhub.hbt
- Resources/translations/confirm.en.xlf
- Resources/translations/fieldedit.en.xlf
- Resources/translations/navigationhub.en.xlf
- Resources/views/PlatformUI/shell.html.twig
We split the fun of adding the keys in template in 3 with @dpobel (#689) and @StephaneDiot (#692)
This is my part of the work.
Basic sanity on the most complex templates
> EZP-25428 Adding translation keys (1/3)

- Resources/public/templates/dashboard-blocks.hbt
- Resources/public/templates/dashboard/allcontent.hbt
- Resources/public/templates/dashboard/mycontent.hbt
- Resources/public/templates/dashboard/mydrafts.hbt
- Resources/public/templates/editpreview.hbt
- Resources/public/templates/rawcontent.hbt
- Resources/public/templates/searchlistview.hbt
- Resources/public/templates/searchview.hbt
- Resources/public/templates/subitem/grid.hbt
- Resources/public/templates/subitem/griditem.hbt
- Resources/public/templates/subitem/list.hbt
- Resources/public/templates/subitem/listmore.hbt
- Resources/public/templates/subitembox.hbt
- Resources/public/templates/tabs/details.hbt
- Resources/public/templates/tabs/locations.hbt
- Resources/public/templates/tabs/relations.hbt
- Resources/public/templates/tabs/versions.hbt
- Resources/public/templates/universaldiscovery.hbt
- Resources/public/templates/universaldiscovery/browse.hbt
- Resources/public/templates/universaldiscovery/confirmedlist.hbt
- Resources/public/templates/universaldiscovery/search.hbt
- Resources/public/templates/universaldiscovery/selected.hbt
- Resources/translations/contentedit.en.xlf
- Resources/translations/dashboardblocks.en.xlf
- Resources/translations/locationview.en.xlf
- Resources/translations/search.en.xlf
- Resources/translations/subitem.en.xlf
- Resources/translations/universaldiscovery.en.xlf
my part of this boring work... :)
Some strings are not translated yet because we need support parameters, the following templates have such strings:
* searchlistview.hbt
* universaldiscovery/search.hbt
* universaldiscovery/confirmedlist.hbt
* contentedit.hbt
* subitem/grid.hbt
* subitem/listmore.hbt
> EZP-25428 translate changes (Damien)

- Resources/public/css/theme/views/subitem/listitem.css
- Resources/public/css/views/subitem/listitem.css
- Resources/public/templates/subitem/listitem/priority.hbt
JIRA: https://jira.ez.no/browse/EZP-25879
Style update of the update priority buttons to take the full height of the subitem list row + a few details.
Screencast:
[![](https://img.youtube.com/vi/TatEq9sHzgo/0.jpg)](http://www.youtube.com/watch?v=TatEq9sHzgo "Click to play on Youtube.com")
manual tests
> EZP-25879: Improve edit priority buttons style

- .travis.yml
Not supported anymore, and failing because of requirements.
> EZP-26728: [travis] Removed php 5.5

- Resources/public/css/theme/modules/embed.css
- Resources/public/js/alloyeditor/processors/emptyembed.js
- Resources/public/js/views/fields/richtext/ez-richtext-resolveembed.js
- Resources/public/js/views/fields/richtext/ez-richtext-resolveimage.js
- Resources/translations/fieldedit.en.xlf
- Tests/js/alloyeditor/processors/assets/ez-editorcontentprocessoremptyembed-tests.js
- Tests/js/views/fields/richtext/assets/ez-richtext-resolveembed-tests.js
- Tests/js/views/fields/richtext/assets/ez-richtext-resolveimage-tests.js
Same as https://github.com/ezsystems/PlatformUIBundle/pull/744 but for master so with the following changes:
* correct use of `Content#getField` to indicate in which language the field should be taken
* error message can be translated
No need for review, just waiting for TravisCI to pass.
> EZP-26475: Infinite loader if embed Content item is unreachable

- Resources/public/js/views/services/ez-searchviewservice.js
- Tests/js/views/services/assets/ez-searchviewservice-tests.js
jira: https://jira.ez.no/browse/EZP-26570
When accessing to the search an empty request was sent.
Unit an manually tested
> Fix EZP-26570: Accessing the search triggers an empty request

- Resources/public/js/views/services/ez-searchviewservice.js
- Tests/js/views/services/assets/ez-searchviewservice-tests.js
jira : https://jira.ez.no/browse/EZP-26570
> Fix-EZP-26570: Search trigger empty request  (master)

- Controller/ContentTypeController.php
- Resources/config/css.yml
- Resources/public/css/theme/views/serverside.css
- Resources/public/css/views/serverside.css
- Resources/translations/content_type.en.xlf
- Resources/views/ContentType/view_content_type.html.twig
Against PR : #728
Depends on : https://github.com/ezsystems/ezpublish-kernel/pull/1832
https://jira.ez.no/browse/EZP-26662
Here is what it looks like :
> EZP-26662: Content type view data and design

- Resources/views/ContentType/update_content_type.html.twig
https://jira.ez.no/browse/EZP-26520
> EZP-26520: add content group link in content edition breadcrumb

- Resources/public/js/models/ez-contentmodel.js
- Resources/public/js/models/ez-locationmodel.js
- Resources/public/js/views/dashboard/ez-dashboardblockallcontentview.js
- Resources/public/js/views/dashboard/ez-dashboardblockmycontentview.js
- Resources/public/js/views/fields/richtext/ez-richtext-resolveembed.js
- Resources/public/js/views/fields/richtext/ez-richtext-resolveimage.js
- Resources/public/js/views/services/ez-searchviewservice.js
- Resources/public/js/views/services/plugins/ez-contenttreeplugin.js
- Resources/public/js/views/services/plugins/ez-searchplugin.js
- Resources/public/js/views/subitem/ez-asynchronoussubitemview.js
- Resources/public/js/views/universaldiscovery/ez-universaldiscoverysearchview.js
- Tests/js/models/assets/ez-contentmodel-tests.js
- Tests/js/models/assets/ez-locationmodel-tests.js
- Tests/js/views/dashboard/assets/ez-dashboardblockallcontentview-tests.js
- Tests/js/views/dashboard/assets/ez-dashboardblockmycontentview-tests.js
- Tests/js/views/fields/richtext/assets/ez-richtext-resolveembed-tests.js
- Tests/js/views/fields/richtext/assets/ez-richtext-resolveimage-tests.js
- Tests/js/views/services/assets/ez-searchviewservice-tests.js
- Tests/js/views/services/plugins/assets/ez-contenttreeplugin-tests.js
- Tests/js/views/services/plugins/assets/ez-searchplugin-tests.js
- Tests/js/views/services/plugins/assets/ez-universaldiscoverycontenttreeplugin-tests.js
- Tests/js/views/subitem/assets/ez-asynchronoussubitemview-tests.js
- Tests/js/views/universaldiscovery/assets/ez-universaldiscoverysearchview-tests.js
- composer.json
jira : https://jira.ez.no/browse/EZP-26325
> EZP-26325: Platform ui search sorting (master)

- Resources/public/js/models/extensions/ez-contentinfo-base.js
- Resources/public/js/models/ez-versionmodel.js
- Resources/public/js/views/services/plugins/extensions/ez-draftserversidevalidation.js
- Tests/js/extensions/assets/ez-draftserversidevalidation-tests.js
- Tests/js/models/assets/ez-versionmodel-tests.js
- Tests/js/models/extensions/assets/ez-contentinfo-base-tests.js
- Tests/js/views/services/plugins/assets/ez-savedraftplugin-tests.js
https://github.com/ezsystems/PlatformUIBundle/pull/769 for master
> Fix EZP-26550: Infinite loading when editing unallowed content (master)

- Resources/translations/bar.en.xlf
- Resources/translations/confirm.en.xlf
- Resources/translations/content_type.en.xlf
- Resources/translations/contentedit.en.xlf
- Resources/translations/contenttypeselector.en.xlf
- Resources/translations/dashboard.en.xlf
- Resources/translations/dashboardblocks.en.xlf
- Resources/translations/ezrepoforms_content_type.en.xlf
- Resources/translations/fieldedit.en.xlf
- Resources/translations/fieldview.en.xlf
- Resources/translations/general.en.xlf
- Resources/translations/language.en.xlf
- Resources/translations/languageselection.en.xlf
- Resources/translations/locationview.en.xlf
- Resources/translations/login.en.xlf
- Resources/translations/messages.en.xlf
- Resources/translations/navigationhub.en.xlf
- Resources/translations/onlineeditor.en.xlf
- Resources/translations/role.en.xlf
- Resources/translations/search.en.xlf
- Resources/translations/section.en.xlf
- Resources/translations/subitem.en.xlf
- Resources/translations/systeminfo.en.xlf
- Resources/translations/trash.en.xlf
- Resources/translations/tree.en.xlf
- Resources/translations/universaldiscovery.en.xlf
- Resources/translations/validators.en.xlf
- bin/extract-translations.sh
Jira: https://jira.ez.no/browse/EZP-26835
Simplify sed command to clean file reference + make path relative
> EZP-26835 : Fix file reference in extract translations + update files

- Resources/public/js/views/ez-contenttypeselectorview.js
- Resources/public/js/views/services/ez-contentcreateviewservice.js
- Resources/public/js/views/services/plugins/ez-contentcreateplugin.js
- Tests/js/views/services/assets/ez-contentcreateviewservice-tests.js
- Tests/js/views/services/plugins/assets/ez-contentcreateplugin-tests.js
jira: https://jira.ez.no/browse/EZP-26862 
https://github.com/ezsystems/PlatformUIBundle/pull/792 (for master)
> Fix EZP-26862: Force language create content master

- Resources/config/yui.yml
- Resources/public/js/views/tabs/ez-locationviewdetailstabview.js
- Resources/public/js/views/tabs/ez-locationviewlocationstabview.js
- Resources/public/js/views/tabs/ez-locationviewrelationstabview.js
- Resources/public/js/views/tabs/ez-locationviewversionstabview.js
- Resources/public/js/views/tabs/ez-locationviewviewtabview.js
- Resources/translations/locationview.en.xlf
- Tests/js/views/tabs/ez-locationviewlocationstabview.html
- Tests/js/views/tabs/ez-locationviewrelationstabview.html
- Tests/js/views/tabs/ez-locationviewversionstabview.html
- Tests/js/views/tabs/ez-locationviewviewtabview.html
JIRA: https://jira.ez.no/browse/EZP-26917
Make sure Location view tab's label are translatable.
manual tests
> Fix EZP-26917: Tabs for content item view are not translatable

- Resources/public/js/views/universaldiscovery/ez-universaldiscoveryfinderexplorerlevelview.js
- Tests/js/views/universaldiscovery/assets/ez-universaldiscoveryfinderexplorerlevelview-tests.js
> Fix ezp 26997 finder gradual loading fix master

- Resources/public/js/apps/ez-platformuiapp.js
- Resources/public/js/views/ez-navigationhubview.js
- Tests/js/apps/assets/ez-platformuiapp-tests.js
- Tests/js/views/assets/ez-locationviewview-tests.js
- Tests/js/views/assets/ez-navigationhubview-tests.js
jira : https://jira.ez.no/browse/EZP-26044 and https://jira.ez.no/browse/EZP-26470 (for master)
> EZP-26044: Navigation hub hidding upper part of the screen (master)

- Resources/config/yui.yml
- Resources/public/css/theme/views/actions/button.css
- Resources/public/css/theme/views/universaldiscovery/explorerlevel.css
- Resources/public/js/apps/plugins/ez-updatetreeplugin.js
- Resources/public/js/models/structs/ez-contenttree.js
- Resources/public/js/views/actions/ez-treeactionview.js
- Resources/public/js/views/ez-discoverybarview.js
- Resources/public/js/views/ez-treeview.js
- Resources/public/js/views/ez-universaldiscoveryview.js
- Resources/public/js/views/services/ez-discoverybarviewservice.js
- Resources/public/js/views/services/ez-universaldiscoveryviewservice.js
- Resources/public/js/views/services/plugins/ez-contenttreeplugin.js
- Resources/public/js/views/services/plugins/ez-discoverybarcontenttreeplugin.js
- Resources/public/js/views/services/plugins/ez-universaldiscoverycontenttreeplugin.js
- Resources/public/js/views/universaldiscovery/ez-universaldiscoveryfinderexplorerlevelview.js
- Resources/public/js/views/universaldiscovery/ez-universaldiscoveryfinderexplorerview.js
- Resources/public/js/views/universaldiscovery/ez-universaldiscoveryfinderview.js
- Resources/public/templates/universaldiscovery.hbt
- Resources/translations/bar.en.xlf
- Resources/translations/universaldiscovery.en.xlf
- Tests/js/views/assets/ez-discoverybarview-tests.js
- Tests/js/views/assets/ez-universaldiscoveryview-tests.js
- Tests/js/views/ez-universaldiscoveryview.html
- Tests/js/views/services/assets/ez-discoverybarviewservice-tests.js
- Tests/js/views/services/ez-discoverybarviewservice.html
- Tests/js/views/universaldiscovery/assets/ez-universaldiscoveryfinderexplorerlevelview-tests.js
- Tests/js/views/universaldiscovery/assets/ez-universaldiscoveryfinderexplorerview-tests.js
- Tests/js/views/universaldiscovery/assets/ez-universaldiscoveryfinderview-tests.js
jira : https://jira.ez.no/browse/EZP-27010
Goal was to add a parameter to the 'contentDiscover' event (event which fires the UDW) to allow to configure the label of the confirm button. This parameter is named 'confirmLabel'
> EZP-27010: Allow to configure UDW confirm label button

- Resources/public/js/alloyeditor/plugins/paste.js
> Issue: https://jira.ez.no/browse/EZP-26976
_( link to kernel PR will be added where most of the work is done for both tfoot and thead )_
> EZP-26976: Keep tfoot element

- Resources/config/yui.yml
- Resources/public/js/models/ez-contentmodel.js
- Resources/public/js/models/ez-sectionmodel.js
- Resources/public/js/views/services/plugins/ez-sectionloadplugin.js
- Resources/public/js/views/tabs/ez-locationviewdetailstabview.js
- Resources/public/templates/tabs/details.hbt
- Resources/translations/locationview.en.xlf
- Tests/js/models/assets/ez-contentmodel-tests.js
- Tests/js/models/assets/ez-sectionmodel-tests.js
- Tests/js/models/ez-sectionmodel.html
- Tests/js/views/services/plugins/assets/ez-sectionloadplugin-tests.js
- Tests/js/views/services/plugins/ez-sectionloadplugin.html
- Tests/js/views/tabs/assets/ez-locationviewdetailstabview-tests.js
JIRA: https://jira.ez.no/browse/EZP-27057
Be able to view section details in detail tab.
https://youtu.be/7z6SjTz7M-4
Unit & manually tested.
> EZP-27057: Section details in details tab

- Resources/translations/fieldedit.en.xlf
JIRA: https://jira.ez.no/browse/EZP-26974
Just fixing a typo in translation
unit test
> Fix EZP-26974: Typo in ISBN validation English message

- Resources/public/js/views/ez-serversideview.js
- Tests/js/views/assets/ez-serversideview-tests.js
JIRA: https://jira.ez.no/browse/EZP-25393 (and various duplicates)
With Safari or Firefox under OSX, the Content Type edit form (or any multi button form in the admin interface) does not work as expected. This is happening because those browsers do not correctly update `document.activeElement` (it is supposed to reference the HTML element having the focus) and we use that property to detect which button is used to submit the form to properly serialize the form.
This patch changes the way we are detecting the button that was used to submit the form. With this patch, we are tracking click on those buttons to store a reference to the used button.
unit tests and manual tests with Firefox for MacOS (with SauceLabs)
> Fix EZP-25393: Impossible to add a field definition with Safari or Firefox under OSX

- Resources/public/js/apps/ez-platformuiapp.js
- Resources/public/js/views/services/ez-discoverybarviewservice.js
- Tests/js/apps/assets/ez-platformuiapp-tests.js
- Tests/js/views/services/assets/ez-discoverybarviewservice-tests.js
Reverts ezsystems/PlatformUIBundle#840
> Revert "Fix EZP-27143 Fixed custom UDW to work with content on the fly."

- Resources/public/webcomponents/js/ez-subitem.js
- Tests/webcomponents/js/ez-subitem.js
See https://github.com/ezsystems/hybrid-platform-ui-core-components/pull/8
> EZP-27361: Add form support to ez-platform-ui-app

- Resources/public/templates/subitem/grid.hbt
- Resources/public/templates/subitem/listitem/priority.hbt
- Resources/public/templates/subitem/listmore.hbt
- Resources/public/templates/subitembox.hbt
- Resources/public/templates/universaldiscovery.hbt
- Resources/public/templates/universaldiscovery/search.hbt
- Resources/public/webcomponents/ez-subitem.html
- Resources/views/ContentType/edit_content_type_group.html.twig
- Resources/views/ContentType/list_content_type_groups.html.twig
- Resources/views/ContentType/update_content_type.html.twig
- Resources/views/ContentType/view_content_type.html.twig
- Resources/views/ContentType/view_content_type_group.html.twig
- Resources/views/Language/edit.html.twig
- Resources/views/Language/list.html.twig
- Resources/views/Language/view.html.twig
- Resources/views/Role/assign_role_by_section.html.twig
- Resources/views/Role/edit_policy.html.twig
- Resources/views/Role/list_roles.html.twig
- Resources/views/Role/update_role.html.twig
- Resources/views/Role/view_role.html.twig
- Resources/views/Section/edit.html.twig
- Resources/views/Section/list.html.twig
- Resources/views/Section/view.html.twig
- Resources/views/components/breadcrumbs.html.twig
See https://github.com/ezsystems/hybrid-platform-ui/pull/6
> EZP-27401: Styles for Hybrid Platform UI

- Tests/Twig/TwigYuiExtensionTest.php
Fixes the travis errors due to twig 2.0.
> Fixed twig 2.0 unit tests errors

- Resources/config/yui.yml
- Resources/public/js/views/services/ez-universaldiscoveryviewservice.js
- Tests/js/views/services/assets/ez-universaldiscoveryviewservice-tests.js
- Tests/js/views/services/ez-universaldiscoveryviewservice.html
JIRA: https://jira.ez.no/browse/EZP-27423
Universal discovery view service should be able to handle location id instead of REST id to load the starting location.
Manually and unit tested
> EZP-27423: UDW view service should accept location Id

- Resources/public/css/views/universaldiscovery.css
- Resources/public/js/models/ez-contentinfomodel.js
- Resources/public/js/models/ez-contentmodel.js
- Resources/public/js/models/ez-contenttypemodel.js
- Resources/public/js/models/ez-locationmodel.js
- Resources/public/js/models/ez-restmodel.js
- Resources/public/webcomponents/demo/ez-universal-discovery.html
- Resources/public/webcomponents/ez-subitem.html
- Resources/public/webcomponents/ez-universal-discovery.html
- Resources/public/webcomponents/js/ez-subitem.js
- Resources/public/webcomponents/js/ez-universal-discovery.js
- Resources/public/webcomponents/mixins/ez-sandbox-yui-component.html
- Resources/public/webcomponents/mixins/js/ez-sandbox-yui-component.js
- Tests/js/models/assets/ez-contentinfomodel-tests.js
- Tests/js/models/assets/ez-contentmodel-tests.js
- Tests/js/models/assets/ez-contenttypemodel-tests.js
- Tests/js/models/assets/ez-locationmodel-tests.js
- Tests/webcomponents/ez-universal-discovery.html
- Tests/webcomponents/js/ez-universal-discovery.js
- Tests/webcomponents/mixins/ez-sandbox-yui-component.html
- Tests/webcomponents/mixins/js/ez-sandbox-yui-component.js
jira: https://jira.ez.no/browse/EZP-27352
This is the base implementation of the universal discovery widget custom element : <ez-universal-discovery>
Goes with: https://github.com/ezsystems/hybrid-platform-ui/pull/16 and https://github.com/ezsystems/hybrid-platform-ui-core-components/pull/16
> EZP-27352: Implement <ez-universal-discovery> 

- Resources/public/templates/subitem/listmore.hbt
- Resources/public/webcomponents/ez-subitem.html
- Resources/views/ContentType/list_content_type_groups.html.twig
- Resources/views/ContentType/view_content_type_group.html.twig
- Resources/views/Language/list.html.twig
- Resources/views/Role/list_roles.html.twig
- Resources/views/Role/view_role.html.twig
- Resources/views/Section/list.html.twig
See https://github.com/ezsystems/hybrid-platform-ui/pull/41
> Improved styling in tabs and admin panel

- Resources/translations/content_type.en.xlf
- Resources/translations/language.en.xlf
- Resources/translations/role.en.xlf
- Resources/translations/section.en.xlf
- Resources/views/ContentType/list_content_type_groups.html.twig
- Resources/views/ContentType/view_content_type.html.twig
- Resources/views/ContentType/view_content_type_group.html.twig
- Resources/views/Language/list.html.twig
- Resources/views/Language/view.html.twig
- Resources/views/Role/view_role.html.twig
- Resources/views/Section/list.html.twig
- Resources/views/Section/view.html.twig
- bin/extract-translations.sh
- composer.json
JIRA: https://jira.ez.no/browse/EZP-27573
Requires: https://github.com/ezsystems/hybrid-platform-ui/pull/85
Requires: https://github.com/ezsystems/hybrid-platform-ui-core-components/pull/31
See https://github.com/ezsystems/hybrid-platform-ui/pull/85 for a screencast.
Adds a confirm dialog when removing something in the admin panel
manual tests
> EZP-27573: Confirmation before removing in admin panel

- Resources/public/css/views/universaldiscovery/confirmedlist.css
- Resources/public/css/views/universaldiscovery/selected.css
- Resources/public/js/models/ez-contenttypemodel.js
- Resources/public/templates/universaldiscovery.hbt
- Resources/public/templates/universaldiscovery/confirmedlist.hbt
- Resources/public/templates/universaldiscovery/explorerlevel.hbt
- Resources/public/templates/universaldiscovery/search.hbt
- Resources/public/templates/universaldiscovery/selected.hbt
- Resources/public/webcomponents/ez-universal-discovery.html
- Tests/js/models/assets/ez-contenttypemodel-tests.js
JIRA: https://jira.ez.no/browse/EZP-27657
This patch makes sure the UDW is usable in 2.0:
* Make sure the UDW gives the Content Type `identifier` and `isContainer` so that we can check those
* Make sure the UDW configured to allow a multiple selection can be used (various CSS fix)
unit test + manual test in https://github.com/ezsystems/hybrid-platform-ui/pull/87
> EZP-27657: Fix UDW to be usable in Hybrid Platform UI

- Resources/public/js/views/ez-subitemboxview.js
- Resources/public/js/views/services/ez-subitemboxviewservice.js
- Resources/public/js/views/subitem/ez-asynchronoussubitemview.js
- Resources/public/js/views/subitem/ez-subitemlistmoreview.js
- Resources/public/webcomponents/ez-subitem.html
- Resources/public/webcomponents/js/ez-subitem.js
- Resources/public/webcomponents/mixins/js/ez-sandbox-yui-component.js
- Tests/js/views/assets/ez-subitemboxview-tests.js
- Tests/js/views/services/assets/ez-subitemboxviewservice-tests.js
- Tests/js/views/subitem/assets/ez-asynchronoussubitemview-tests.js
- Tests/js/views/subitem/assets/ez-subitemlistmoreview-tests.js
- Tests/webcomponents/js/ez-subitem.js
See https://github.com/ezsystems/hybrid-platform-ui/pull/103
> EZP-27586: Added a refresh method on <ez-subitem> custom element

- Resources/public/js/views/tabs/ez-locationviewversionstabview.js
- Resources/public/templates/tabs/versions.hbt
- Tests/js/views/tabs/assets/ez-locationviewversionstabview-tests.js
- Tests/js/views/tabs/ez-locationviewversionstabview.html
JIRA: https://jira.ez.no/browse/EZP-27867
Remove button and associated methods to create draft from archived version.
> EZP-27867: Remove button 'Create draft from archived version'

- .travis.yml
- Tests/DependencyInjection/EzPlatformUIExtensionTest.php
- Unit tests: mark current failing test as incomplete from the point where it fails until that is looked into
- Travis config: Small change to prepare for https://github.com/ezsystems/ezplatform/pull/205#discussion_r139614898
> [Travis] Mark failing tests as incomplete & prepare for changes on docker config

- Resources/public/templates/confirmbox/draftconflict.hbt
**Jira ticket:** https://jira.ez.no/browse/EZP-28006
> EZP-28006: More user friendly date format in draft conflict pop-up

- Resources/public/css/theme/views/serverside.css
- Resources/public/css/views/serverside.css
- Resources/translations/role.en.xlf
- Resources/views/Role/view_role.html.twig
> JIRA: https://jira.ez.no/browse/EZP-24699
> **Requires merge first**: https://github.com/ezsystems/repository-forms/pull/159
This PR makes the values of policy limitations readable to humans. See https://github.com/ezsystems/repository-forms/pull/159 for more details
> EZP-24699: Enrich policy limitations view with human readable names

- Resources/public/js/alloyeditor/plugins/caret.js
**Jira ticket:** https://jira.ez.no/browse/EZP-28130
> EZP-28130: Console error when moving empty richText field

- Resources/public/js/alloyeditor/buttons/imagehref.js
- Resources/public/js/alloyeditor/buttons/imagehref.jsx
**Jira ticket:** https://jira.ez.no/browse/EZP-28146
> EZP-28146: Unable to replace an image - UDW does not allow me to confirm an image selection

- Resources/public/js/alloyeditor/buttons/embedhref.js
- Resources/public/js/alloyeditor/buttons/embedhref.jsx
**Jira ticket:** https://jira.ez.no/browse/EZP-28182
> EZP-28182: Cannot replace emedded content in AlloyEditor

- Features/Context/Role.php
- Features/Context/SubContext/CommonActions.php
- Features/RoleUI/RoleUI.feature
- Resources/translations/messages.en.xlf
> JIRA: https://jira.ez.no/browse/EZP-27366
This PR improve Behat scenarios related to changes in validation of the role creating/updating form introduces in https://github.com/ezsystems/repository-forms/pull/122: In detail:
|                           Scenario                            |    Description    |
|---------------------------------------------------------------|-------------------|
| Creating a Role with an existing identifier fails validation  | Fixed             |
| Creating a Role with an too long identifier fails validation  | Added             |
| Updating a Role with an existing identifier fails validation  | Fixed and enabled             |
| Updating a Role with an too long identifier fails validation  |  Added |
> EZP-27366: Update Behat scenarios related to the validation of role creating/updating form

- Resources/public/js/alloyeditor/toolbars/config/block-base.js
- Resources/public/js/apps/ez-platformuiapp.js
- Resources/public/js/apps/plugins/ez-positionplugin.js
- composer.json
**Requires:** https://github.com/ezsystems/ez-js-rest-client/pull/87
> Update CAPI config

- Controller/PlatformUIController.php
- Resources/config/services.yml
- Resources/views/PlatformUI/shell.html.twig
> JIRA: https://jira.ez.no/browse/EZP-27751
Builds upon research done by @adamwojs in #891 _(so for performance numbers and context see that PR)_ to make this hopefully into a more ready state.
Todo:
> EZP-27751: combining stylesheets in dev env & cache combined js in prod

- ApplicationConfig/Providers/RootInfo.php
- Controller/PlatformUIController.php
- Loader/ComboLoader.php
- Loader/Loader.php
- Resources/views/PlatformUI/shell.html.twig
- Tests/Loader/ComboLoaderTest.php
JIRA issue: https://jira.ez.no/browse/EZP-28398
Fix for 1.12.x.
> Fix-EZP-28398: Using Assetic versioning breaks Platform Admin UI

- Resources/public/js/views/services/plugins/ez-contentcreateplugin.js
- Resources/public/templates/navigationhub.hbt
- jshint.json
**Jira ticket:** https://jira.ez.no/browse/EZEE-1812
**TODO:**
> EZEE-1812: eZPlatform EE v2 improvements

- Resources/config/yui.yml
- Resources/public/js/apps/ez-platformuiapp.js
- Resources/public/js/views/serverside/ez-linkviewserversideview.js
- Resources/public/js/views/services/ez-linkviewserversideviewservice.js
- Resources/public/js/views/services/ez-navigationhubviewservice.js
- Resources/views/LinkManager/view.html.twig
> JIRA: https://jira.ez.no/browse/EZP-28657
This PR contains patch for non working redirection to the main location of content in "Content">"Link Manager">"Link detail">"Content items using the URL (X)"
> EZP-28657: Link to content object should redirect to the main location of content

- Tests/js/views/services/assets/ez-navigationhubviewservice-tests.js
> JIRA: https://jira.ez.no/browse/EZP-28495
This PR fixes broken JavaScript unit tests in https://github.com/ezsystems/PlatformUIBundle/pull/926.
> EZP-28495: As Editor I want UI for external links management (js unit  tests)

- ApplicationConfig/Providers/SiteaccessList.php
- Resources/config/services.yml
- Resources/config/yui.yml
- Resources/public/css/views/editpreview.css
- Resources/public/js/helpers/ez-strictcomparisonhelper.js
- Resources/public/js/views/actions/ez-previewactionview.js
- Resources/public/js/views/ez-actionbarview.js
- Resources/public/js/views/ez-contenteditview.js
- Resources/public/js/views/ez-editactionbarview.js
- Resources/public/js/views/ez-editpreviewview.js
- Resources/public/js/views/services/ez-contenteditviewservice.js
- Resources/public/templates/editpreview.hbt
- Tests/js/views/assets/ez-actionbarview-tests.js
- Tests/js/views/assets/ez-editpreviewview-tests.js
https://jira.ez.no/browse/EZP-28754
> EZP-28754: As a v1 Editor, I want to select a SiteAccess in the Preview mode

- .travis.yml
JIRA: https://jira.ez.no/browse/EZP-29107
This is a parallel follow-up (😉 ) to https://github.com/ezsystems/StudioUIBundle/pull/898
Running Behat tests on Varnish.
> EZP-29017: Run tests on Varnish

- .travis.yml
- DependencyInjection/Compiler/ValueObjectVisitorPass.php
- EzSystemsPlatformUIBundle.php
- Features/ContentActions/CopyContent.feature
- Features/ContentActions/MoveContent.feature
- Features/ContentActions/RemoveContent.feature
- Resources/config/services.yml
- Resources/public/js/models/extensions/ez-contentinfo-base.js
- Resources/public/js/models/ez-versioninfomodel.js
- Resources/public/js/views/services/plugins/ez-contenteditplugin.js
- Resources/public/js/views/services/plugins/ez-versionsplugin.js
- Resources/public/templates/confirmbox/draftconflict.hbt
- Resources/public/templates/tabs/versions.hbt
- Rest/Generator/Json.php
- Rest/ValueObjectVisitor/VersionInfo.php
- Rest/ValueObjectVisitorDispatcher.php
- Tests/DependencyInjection/Compiler/ValueObjectVisitorPassTest.php
- Tests/Rest/Generator/JsonTest.php
- Tests/Rest/ValueObjectVisitorDispatcherTest.php
- Tests/js/models/extensions/assets/ez-contentinfo-base-tests.js
- bin/travis/runbehat.sh
- composer.json
Merging 1.13 up to 2.1 - it might require additional changes to .travis.yml to adapt it for v2.
> [JUST FOR TESTING] Merge up 1 13 to 2 1

- Resources/config/services.yml
> JIRA: -
Deleted obsolete services definitions which was accidentally merged up to 2.1 in d60f7da142f4ee92812a03e5019de215b97a36e5
> Deleted obsolete services definitions

- Resources/public/js/alloyeditor/plugins/embed.js
**Jira ticket:** https://jira.ez.no/browse/EZP-29254
> EZP-29254: Images embedded in RichText editor dissapear after undo

- Resources/public/js/alloyeditor/plugins/embed.js
Reverts ezsystems/PlatformUIBundle#975
> Revert "EZP-29254: Images embedded in RichText editor dissapear after undo"

- Controller/PlatformUIController.php
- Resources/public/js/apps/ez-platformuiapp.js
- Resources/public/js/views/services/ez-contentcreateviewservice.js
- Resources/public/js/views/services/ez-contenteditviewservice.js
- Resources/public/js/views/services/ez-viewservice.js
- Resources/translations/contentedit.en.xlf
- Resources/views/PlatformUI/shell.html.twig
- Tests/js/apps/assets/ez-platformuiapp-tests.js
https://jira.ez.no/browse/EZP-29286
~https://github.com/ezsystems/ez-js-rest-client/pull/92~ _Merged, need to be tagged as 1.5.4 once passed by QA_
> EZP-29286: As a Platform UI User, I would like my session to be extended while I still use Platform UI
